### ISSUE TITLE
Trying shapeless with `try-shapeless` script fails with unexpected newline

### ISSUE THREAD

**Issue by mtjon** [milessabin/shapeless#1047]
# Situation
Trying out shapeless by running:

`curl -s https://raw.githubusercontent.com/milessabin/shapeless/master/scripts/try-shapeless.sh | bash`

As indicated in the README fails with:

```
~/.coursier/coursier: line 6: syntax error near unexpected token `newline'
~/.coursier/coursier: line 6: `<!DOCTYPE html>'
```

# Expected result
Being dropped into the Ammonite shell

# Tried to resolve by
Cloning the repo and running the script directly from there results in the same error.

# System
```
❯ lsb_release -va
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal
```
running in WSL2 on Windows10

**Comment by Alabme** [comment]
Looks like Your coursier is invalid. Try:
`curl -L -o coursier https://get-coursier.io/coursier`
