### ISSUE TITLE
Add a field type member to FieldOf trait and use in tests.

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#117]

**Comment by frroliveira** [comment]
@milessabin Can you give an usage example?

**Comment by milessabin** [comment]
Yes, of course :-)

At the moment we have constructions this this in tests
```scala
typed[FieldType[intField1.type, Int]](v1)
typed[FieldType[boolField1.type, Boolean]](v2)
```
(see [here](https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/records.scala#L103-L104)). It would be nice to add an appropriately defined type member to `FieldOf` named `FieldType` so that the following is equivalent to the above,
```scala
typed[intField1.FieldType](v1)
typed[boolField1.FieldType]](v2)
```

**Comment by frroliveira** [comment]
Just noticed that the test you mentioned puts a string into an [integer field](https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/records.scala#L97).
This is a bug, right?

**Comment by milessabin** [comment]
Yes, that does look like a bug!

Cheers,


Miles

On Mon, May 9, 2016 at 12:15 PM, Filipe Oliveira <notifications@github.com>
wrote:

> Just noticed that the test you mentioned puts a string into an integer
> field
> <https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/records.scala#L97>
> .
> This is a bug, right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/milessabin/shapeless/issues/117#issuecomment-217838080>
>



-- 
Miles Sabin
tel: +44 7813 944 528
skype: milessabin
gtalk: miles@milessabin.com
http://milessabin.com/blog
http://twitter.com/milessabin
