### ISSUE TITLE
Split out HKernel.

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#125]

**Comment by vil1** [comment]
@milessabin is this issue still active ?

If so, can you specify what you mean by "split out"? Is the purpose of that issue to extract `HKernel`* from its current location in `shapeless/ops/hlists.scala` and make it a first-class citizen (eg in a `shapeless/hkernel.scala` file), potentially with its own ops/syntax? Or is it something broader than that?

**Comment by joroKr21** [comment]
Shapeless 3 is here: https://github.com/typelevel/shapeless-3
