### ISSUE TITLE
Add <: HList bounds to HList ops wherever appropriate.

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#136]

**Comment by ceedubs** [comment]
@milessabin I think this can be closed due to #204.

**Comment by milessabin** [comment]
I think I left this open because there were a few more. But I've had a complete change of heart, and I now think that all the `<: HList` and `<: Coproduct` bounds are verbose and overly constraining ... come shapeless 3.0 they'll all go.

So I'm happy to close this ticket ...
