### ISSUE TITLE
Lazy pack factors out (co-)product recursion.

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#145]

**Comment by milessabin** [comment]
This probably needs to be rethought as part of the SMC/CPS reworking for shapeless 3.0.0.

**Comment by alexarchambault** [comment]
I'm currently trying various ways of doing this... Using representations of products and sums as nested `Tuple2` and `Either`s, yes.

**Comment by alexarchambault** [comment]
FYI, the -1 (minus one) version is on [this branch](https://github.com/alexarchambault/shapeless/tree/topic/derive).

Illustrated [here](https://github.com/alexarchambault/shapeless/blob/topic/derive/core/src/main/scala/shapeless/derive.scala#L362-L368), along with [this](https://github.com/alexarchambault/shapeless/blob/topic/derive/core/src/main/scala/shapeless/derive.scala#L373-L374), and used in [this notebook](https://github.com/alexarchambault/shapeless/blob/topic/derive/shapeless%20derive.ipynb) (that I'm using to debug this).

**Comment by alexarchambault** [comment]
In particular, I'm trying to have a loose enough implementation, in particular:
- `product` and `sum` methods with optional arguments like `name` (name of the field / constructor), `default` (default value of the field, if any - half done), maybe `someNameAnnotation` that would look for annotation `@someName(value1, value2)`, and supply `Some((value1, value2))` (not done yet),
- all methods accept optional implicit arguments,
- all arguments can optionally be by-name,
- ...

The only constraints in the current implementation are:
- the methods must be put in a member called `typeClass` of the companion of the type class,
- method names (must be `point`, `product`, `sum`, `map`),
- their first type arguments must be the ones of the example above (one type parameter for `point`, 2 for `product`, `sum`, `map`), in the exact same order,
- if `map` needs `from` and/or `to` functions, it must accept argument(s) with these exact name and signature,
- the first parameter list of `point` must consist in only one argument with the type of the example,
- ...

**Comment by alexarchambault** [comment]
Also, note that:
- it's implemented as a `Lazy` extension (those of https://github.com/milessabin/shapeless/pull/435), so it should deal well with `Lazy` / `Strict`, and has to be used through them,
- it uses a shapeless-3 like (?) `Generic`, with representations made of nested `Tuple2` / `Either`, terminated by `Unit` or `Nothing`.

**Comment by milessabin** [comment]
This is sounding more ambitious than the title (and original intention behind) this ticket ;-)

From your description, this sounds a lot like a reworking of `TypeClass`. My main comment at this point is that when I was attempting to generalize `TypeClass`, before hitting on `Lazy` I also tried to deal with additional possibly implicit arguments. In the end this all dropped out of `Lazy` combined with vanilla implicit resolution.

**Comment by alexarchambault** [comment]
Yes, I think that's what I'm about to get :-), an optimized (and generalized too) rework of `TypeClass` in terms of `Lazy` - as a `Lazy` extension. I'd like to quickly benchmark it against hand written macros (through https://github.com/alexarchambault/auto-type-class-benchmark), to assess possible compile time speed ups.

**Comment by milessabin** [comment]
Shall I put this back on the backlog?

**Comment by alexarchambault** [comment]
If it's a different thing than https://github.com/milessabin/shapeless/pull/459, yes!

**Comment by milessabin** [comment]
Okey doke ... backlogged :-)

**Comment by joroKr21** [comment]
Shapeless 3 is out at https://github.com/typelevel/shapeless-3
