### ISSUE TITLE
Polymorphic functions on HList not working

### ISSUE THREAD

**Issue by wedens** [milessabin/shapeless#162]
shapless 2.0.0
scala 2.11.1

from "Feature overview: shapeless 2.0.0"
```scala
import shapeless._
import poly._

object choose extends (Set ~> Option) {
  def apply[T](s : Set[T]) = s.headOption
}
val sets = Set(1) :: Set("foo") :: HNil
val opts = sets map choose 
```
exception:

```
java.lang.AbstractMethodError: choose$.caseUniv()Lshapeless/PolyDefns$Case;
  ... 43 elided
```

**Comment by milessabin** [comment]
I can't reproduce this with Scala 2.11.7, so I'm going to attribute it to a now-fixed REPL bug.

**Comment by travisbrown** [comment]
As I mentioned [here](https://gitter.im/milessabin/shapeless?at=562fb9eda752d57c01916c10), I'm seeing this error on this code on a fresh checkout of Shapeless on both 2.11.7 and 2.12.0-M3 (and Java 7 and Java 8).

I know I've defined natural transformations in a REPL in the last few months, and I'm not sure what could have changed either in Shapeless or my system to be causing this.

**Comment by milessabin** [comment]
I'll take another look before 2.3.0.

**Comment by milessabin** [comment]
@travisbrown I just tried your example on a 2.11.7 REPL with the latest 2.3.0-SNAPSHOT and I'm not seeing a problem. Could you check again?

**Comment by travisbrown** [comment]
@milessabin Looks fine to me, thanks!

**Comment by milessabin** [comment]
Thanks :-)

**Comment by milessabin** [comment]
This is a Scala compiler bug, mimimized as [SI-9689](https://issues.scala-lang.org/browse/SI-9689).

**Comment by milessabin** [comment]
A (runtime) workaround is to use `-Yno-load-impl-class` as a `scala` command line option, or as a flag for the sbt Scala console.
