### ISSUE TITLE
Add tests for Sized.Exact when 2.11 bug is fixed

### ISSUE THREAD

**Issue by travisbrown** [milessabin/shapeless#188]
The `Sized.Exact` extractor I've added in #184 is designed not to compile `val Sized.Exact(a, b) = Sized('foo)` or `val Sized.Exact(a) = Sized('foo, 'bar)`. It works, but we can't confirm that with `illTyped` because of [a bug](https://issues.scala-lang.org/browse/SI-8719) in 2.11. When that's fixed we'll want to add something like the following to the tests for `Sized`:

``` scala
illTyped("""
  val Sized.Exact(x, y) = ss
""")

illTyped("""
 val Sized.Exact(w, x, y, z) = ss
""")
```

**Comment by joroKr21** [comment]
`Sized.Exact` doesn't exist

**Comment by milessabin** [comment]
FTR, it was from a rejected PR: https://github.com/milessabin/shapeless/pull/187.
