### ISSUE TITLE
Add Nat ranges and zipWithIndex to HList and tuples

### ISSUE THREAD

**Issue by travisbrown** [milessabin/shapeless#190]
As discussed [here](http://stackoverflow.com/a/24814753/334519). Three questions:

Do we want to allow the user to specify the step for ranges? It adds a lot of complexity for something that's questionably useful.

Any thoughts on whether `(1 :: 'a :: HNil).zipWithIndex` should be `(1 :: _0 :: HNil) :: ('a :: _1 :: HNil) :: HNil` or `(1, _0) :: ('a, _1) :: HNil`? My vote's for the latter but the former might be more consistent.

Is there really any reason to provide this for `Coproduct`?

**Comment by milessabin** [comment]
Fixed by @AndreasKostler in #450.
