### ISSUE TITLE
Add 'injectable' type class instances to TypeClass

### ISSUE THREAD

**Issue by pierzchalski** [milessabin/shapeless#196]
The ability to use custom instances would be very useful for common use-case instances, such as pretty-printers and codecs.

Currently, the generic type class constructors (`shapeless.TypeClass`) use macros to fully expand the product/coproduct representation of a sealed trait family, which means it isn't possible to 'inject' custom instances of type classes into the resulting generated typeclass instance.

Original discussion [here](https://groups.google.com/forum/#!topic/shapeless-dev/SbWqIsr3oWE).

**Comment by pierzchalski** [comment]
@milessabin Sorry about the late response, although I haven't really got any useful input at this point. Exposing the Typeclass interface through implicits ended up having some other benefits on the side: since I can now use the full power of shapeless's type-level operations on the (co)product type arguments, I ended up making a generic uniform-probability distribution function over a trait tree, which was exciting.

I ended up testing the new TC stuff on a bunch of weird trait trees, and it seemed to handle them fine (by 'weird', I mean things like the following:
```scala
sealed trait T
sealed trait T1 extends T
case class A(x: T2) extends T1 //intermediate type filters out part of T tree
sealed trait T2 extends T
...
```
and
```scala
sealed trait T
sealed trait T1
case class A(x: T1) extends T1 with T //intermediate filtering type is not a child of T
sealed trait T2
...
```
which might have a use case, for instance when using types to 'tag' subsets of nodes in a trait tree for ASTs).

**Comment by milessabin** [comment]
Awesome ... thanks for the feedback :-) I'd be very interested in seeing your generic probability distribution stuff if it's public.

**Comment by pierzchalski** [comment]
I may have over-sold how fancy it was... it was mostly just using access to ```ops.coproduct.Length``` to ensure that types like ```A :+: B :+: C :+: CNil``` are actually uniform over the three types. It's technically in one of my public repos, but from recent experience, I should probably stick it in a [gist instead](https://gist.github.com/pierzchalski/c2ae38718b53cdfaf33e).

If I were to follow this further, I'd be interested in non-uniform distributions that guarantee expected size of instances (for instance, even a simple binary tree doesn't have a finite expected size if you just naively choose a leaf or a branch with even odds). That would probably involve sticking an optimization engine in a type-providing macro or something, which kind of puts it out of scope of this discussion about typeclasses :-)

**Comment by milessabin** [comment]
Keep me posted if you explore that bounded size case. I think it might be possible to do something along those lines consistently with a type class based approach (eg. we might be able to materialize a proof that a type has a given bound).

Are you OK with me tweeting a link to your gist? If so, what's your twitter handle so I can mention you?

**Comment by pierzchalski** [comment]
I'm perfectly fine with you tweeting the gist, if you think it's interesting enough. My handle is [@eapi_](https://twitter.com/eapi_), although I don't really use twitter much.

I also thought that the bounded expected size case might have been feasible with typeclasses, however I think there might be a need for some form of numeric optimization for the weights of each type, which would be both fun and eye-gougingly difficult to do at the type level.

I say there might be some numeric stuff involved because (considering something simple like the binary tree case):
```scala
sealed trait Tree
case class Leaf(s: String) extends Tree
case class Branch(left: Tree, right: Tree) extends Tree
```
If we choose ```Leaf``` with relative weight ```p``` and ```Branch``` with weight ```q```, the expected size (in terms of nodes) of an instance of ```T``` is ```(p + q)/(p - q)``` (which is a value that would be an adventure in itself to try and derive automatically!). 

Since there are several solutions for any given 'target' size for ```T```, we need another criterion for the choice of ```p``` and ```q```. That's probably going to be something like minimum variance, or maximum entropy, or just the weight vector norm ```p^2 + q^2```, which would all be easiest with a numeric optimizer or SMT solver.

**Comment by milessabin** [comment]
Right. I think it's a good idea to hide this kind of thing behind type classes with implicit macro materializers ... I think that way there's a good chance of being able support fine grained composition.
