### ISSUE TITLE
Example request: apply implicit operation on impls of a sealed trait

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#238]
let's say we have the following hierarchy

```scala
sealed trait MyTrait
case class Foo() extends MyTrait
case class Bar() extends MyTrait
```

and we can provide implementations for

```scala
trait Thing[T] {
  def thing(t: T): Double
  def unthing(d: Double): T
}
implicit val tf: Thing[Foo]
implicit val tb: Thing[Bar]
```

we'd like to avoid creating boilerplate laden code such as this (imagine how bad it gets with 10 case classes implementing the trait)

```scala
def stuff(t: MyTrait): Double =  t match {
  case f: Foo => implicitly[Thing[Foo]].thing(f)
  case f: Bar => implicitly[Thing[Bar]].thing(f)
}

def cram(s: String, d: Double): MyTrait = s match {
  // strings here are whatever the LabelledGeneric would give
  case "Foo" => implicitly[Thing[Foo]].unthing(d)
  case "Bar" => implicitly[Thing[Bar]].unthing(d)
  case _ => ??? // no type safety here
}
```

can shapless be used to automagically create `stuff` and `cram`? (assuming I can give some form of thunk that says "get the implicit for the implementation and call a method on that").

@cage433

**Comment by milessabin** [comment]
We have a number of examples of the general pattern now, so I'm going to declare victory on this one.
