### ISSUE TITLE
Use sensible names for the ops implicits

### ISSUE THREAD

**Issue by reactormonk** [milessabin/shapeless#240]
A lot of the implicits in ops are just numbered, which makes the code harder to read. A sensible naming scheme or comments which explain when which implicit is chosen would help.

Eg. https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/ops/hlists.scala#L767

    implicit def hlistFilter1[L <: HList, H]
      (implicit f : Filter[L, H]): Aux[H :: L, H, H :: f.Out] = ...

    implicit def hlistFilter2[H, L <: HList, U]
      (implicit f : Filter[L, U], e : U =:!= H): Aux[H :: L, U, f.Out] = ...
      
Would be way easier to read with

    implicit def found[L <: HList, H]
      (implicit f : Filter[L, H]): Aux[H :: L, H, H :: f.Out] = ...

    implicit def notFound[H, L <: HList, U]
      (implicit f : Filter[L, U], e : U =:!= H): Aux[H :: L, U, f.Out] = ...

**Comment by milessabin** [comment]
Fixed in #240. Plenty of scope for more along the same lines as this.
