### ISSUE TITLE
Sized[Array] of value elements

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#241]
When creating a `Sized[Array]`, of `Boolean`-s say, one gets the following error at runtime:

```scala
    scala> val s = Sized[Array](true, false, false)
    java.lang.ClassCastException: [Z cannot be cast to [Ljava.lang.Boolean;
      ... 48 elided
```
It seems to happen only for Arrays of value types (not reference ones). One gets the same error outside the REPL.

Dropping the `extends AnyVal` on `Sized` solves the issue. The 2.10.x branch is not impacted, as `Sized` doesn't extend `AnyVal` on it. So the sometimes weird behaviour of `AnyVal` seems to be incriminated. Don't know if we can do something about it.

**Comment by milessabin** [comment]
This was fixed accidentally by the dropping of the `extends AnyVal` which was done to accommodate 2.10.x in the single branch build. See also #600.
