### ISSUE TITLE
Witness to provide scala name

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#256]
it would be great if a Witness could provide the Symbol for the thing it is witnessing, e.g. the scala name for a singleton.

**Comment by fommil** [comment]
any more thoughts about this one?

**Comment by milessabin** [comment]
Can you remind me what the motivation for this is?

**Comment by fommil** [comment]
when writing a marshaller for a singleton, it would be good to have access to the Scala name. Currently one can ask for the `value` and then `getClass.getSimpleName` etc but that's the Java name rather than the Scala one (plus it's all runtime lookup).

**Comment by milessabin** [comment]
Right, but I think that in any context where the type is known precisely enough for the name to be read off it, the name is also known statically (ie. you could always use a string literal).

Is the motivation to avoid duplication like,

```scala
object Foo {
  def label = "Foo"
}
```
I think it might be possible to make something like,
```scala
object Foo {
  def label = NameOf[this.type]
}
```
work, but it seems like a very marginal win, particularly as you probably shouldn't be tying serialization form quite so closely to program text.

Can you make that example seem more compelling? Or do you have a different example in mind?

**Comment by fommil** [comment]
in ENSIME we absolutely want it to be tightly coupled :smile: because it could be input to the presentation compiler.

`NameOf` sounds good! It would be great if it had both Java and Scala names available (we use those in the lucene index)

**Comment by milessabin** [comment]
OK. This will be for 2.3.0 though.

**Comment by stacycurl** [comment]
This will be handy for [delta](http://github.com/stacycurl/delta) too.

It would allow code like this:
```
case class Foo(firstInt: Int, secondInt: Int)
Foo(1, 2).delta(Foo(1, 3)).toString == "Foo(secondInt: 2 -> 3)"
```

**Comment by milessabin** [comment]
@stacycurl can't you get that already from `LabelledGeneric`?

**Comment by stacycurl** [comment]
No idea, haven't used LabelledGeneric before, I'll give it a try.

**Comment by fommil** [comment]
Doesn't `Typeable[T].describe` do this now in 2.2? If you agree, I'm happy for you to close.

**Comment by fommil** [comment]
oh but that's the type, not the instance name.
