### ISSUE TITLE
Lazy & case object constructors

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#306]
I couldn't get `Lazy` implicits to work with simple examples of sealed hierarchies having case object constructors, like in:
```scala
sealed trait Base
case object Foo extends Base
case object Bar extends Base
```
(full example at https://gist.github.com/alexarchambault/86de91eb158c5f485522).

**Comment by milessabin** [comment]
Thanks, that's very helpful. I think it might very well be a reproduction of a problem that @mpilquist and I have seen in Scodec.
