### ISSUE TITLE
Lazy and generics

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#314]
I've been trying to get `Lazy` to work with generic types (generic like in `def func[T](t: T)`, not `shapeless.Generic`), without success so far.

When working with labels, it seems that an implicit ``Lazy[TC[Record.`...`.T]]`` (with some generic type `T` in `...`) cannot be found, although an implicit ``TC[Record.`...`.T]`` can.

And without labels, looking for an implicit ``Lazy[TC[HList.`...`.T]]`` makes scalac fail with

    [error] (compile:compile) scala.tools.nsc.typechecker.Infer$NoInstance: undetermined type

when an implicit ``TC[HList.`...`.T]`` seems to be ok.

Full example here: https://gist.github.com/alexarchambault/e447943272bd5c0ae9b8

**Comment by milessabin** [comment]
I can't reproduce this WRT shapeless 2.2.0-SNAPSHOT.

Also, where you say,
> Goal here is to have
> TC[Wrapper[T]]

I think that would now covered by something derived in terms of `Generic1[Wrapper]`.

**Comment by alexarchambault** [comment]
Indeed, seems to be fixed in 2.2. That's great! No need for `Generic1`, just `[T: TC]` is enough to get a `TC[Wrapper[T]]`.

**Comment by milessabin** [comment]
Thanks for the update! :-)
