### ISSUE TITLE
implicit Lenses not found if the classes are defined afterwards, within the same source file. 

### ISSUE THREAD

**Issue by Baccata** [milessabin/shapeless#322]
My knowledge of the scala compiler and macros being quite limited, I'm not sure whether the problem comes from shapeless or from the compiler, but the following is a bit strange : 

this compiles 

```scala 

import shapeless._
import lens._, syntax.singleton._, tag.@@

sealed trait BGraph[T]
case class BTerm[T](value: T) extends BGraph[T]

class BNode[T](left0: => BGraph[T], right0: => BGraph[T]) extends BGraph[T] {
	lazy val left = left0
	lazy val right = right0
}

class Trythings {
	val g = optic[BGraph[Int]]
	val l = g.left
}

```
while this doesn't : 

```scala 

import shapeless._
import lens._, syntax.singleton._, tag.@@

class Trythings {
	val g = optic[BGraph[Int]]
	val l = g.left
}

sealed trait BGraph[T]
case class BTerm[T](value: T) extends BGraph[T]

class BNode[T](left0: => BGraph[T], right0: => BGraph[T]) extends BGraph[T] {
	lazy val left = left0
	lazy val right = right0
}

``` 
I would have assumed it to work, no matter the order. It's not a big problem, but it got me confused as I tried the latter first.

**Comment by ritschwumm** [comment]
could be related to https://issues.scala-lang.org/browse/SI-7755 or https://issues.scala-lang.org/browse/SI-7046

**Comment by milessabin** [comment]
As @ritschwumm says, this is a issue with `knownDirectSubclasses`. I'm afraid there's not a lot to be done here.

**Comment by milessabin** [comment]
OK, closing this for now. Please reopen if you think there's something I've missed.
