### ISSUE TITLE
2.1.0 breaks use of scala.reflect.Manifest

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#323]
I am migrating some legacy code, e.g.

```scala
class RichAny[T](protected val value: T) {
  def as[V: Manifest]: V = implicitly[Manifest[V]].as[V](value)
}

class RichList[A](list : List[A]) {
  def castValues[T](error : Any => T)(implicit m : Manifest[T]) : List[T] = m.castAll(list, error)
}
```

and these lines are failing when `shapeless.Typeable` is imported for other uses in the same file with an error along the lines of

```
class type required but V found
```

I am planning to just remove these definitions, but this might be hinting at a bug in shapeless.

**Comment by stacycurl** [comment]
2.1.0 is supported from 2.10 onwards; Manifests were deprecated in 2.10, do you get the same error if you use ClassTag instead ? (fantastic pimps btw, can't imagine where they came from ;p )

**Comment by milessabin** [comment]
That's very odd ... can you show an actual example of the source lines which are failing and the exact error in that case?

**Comment by fommil** [comment]
those are the exact lines above

**Comment by milessabin** [comment]
Err ... then can you show me the exact error?

**Comment by fommil** [comment]
```
 class type required but V found
[error]   def as[V: Manifest]: V = implicitly[Manifest[V]].as(value)
```

**Comment by fommil** [comment]
@stacycurl good thinking, that does help.

**Comment by stacycurl** [comment]
I think the problem might be in RichManifest, if memory serves it looks something like this:

```
class RichManifest[T](manifest : Manifest[T]) {
    /** Replacement for asInstanceOf, logs more information upon failure */
    def as(any: Any)(implicit t: Typeable[T]): T = any.cast[T].getOrElse(
      throw new RuntimeException("%s [%s] is not of type %s" % (any, getClassOf(any), manifest.erasure)))
}
```

**Comment by stacycurl** [comment]
Which of course (if you are preserving the 'as' pimp) would need to be ported to a 'RichClassTag'.

**Comment by fommil** [comment]
we have so many uses of Manifest it is depressing

**Comment by fommil** [comment]
anyway, I'm off to the SLUG talk now :smile:

**Comment by milessabin** [comment]
Which versions of Scala and shapeless did this actually work with?

**Comment by fommil** [comment]
2.0.0 with Scala 2.11 was good

**Comment by milessabin** [comment]
It's not easy to say without a reproducible example, but I think it's probably due to `Typeable` being stricter (ie. not broken) about what it can safely cast. Previously there was a fallback instance which might have been picked up in your case before but which is now forbidden. See #69.

**Comment by fommil** [comment]
Now that I know where the problem is (too many pimps!) I think I can workaround this, thanks!

Will hopefully have a good stress test of everywhere for you in the next few days.
