### ISSUE TITLE
`everywhere` doesn't like BigDecimal

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#325]
I have a domain model that has a `BigDecimal` somewhere in it, and any application of `everywhere` gives this warning (shapeless 2.1, scala 2.11):

```
[warn] ...: method apply in object BigDecimal is deprecated: This method appears to round a java.math.BigDecimal but actually doesn't.  Use new BigDecimal(bd, mc) instead for no rounding, or BigDecimal.decimal(bd, mc) for rounding.
[warn]     everywhere(validator)(entry)
[warn]                          ^
[warn] one warning found
[info] Compiling 1 Scala source 
```

**Comment by milessabin** [comment]
!?!

That's a deprecation warning from `BigDecimal`! How is that a shapless issue?

**Comment by fommil** [comment]
I don't get this unless I use `everywhere`. I don't know how it managing to trigger the deprecation warning, but I'm concerned that it's accessing something bad.

**Comment by fommil** [comment]
maybe a workaround is needed for `BigDecimal` ?

**Comment by milessabin** [comment]
Not really sure where to go with this. I think the only suggestion I have is to define a `validateEverywhere` poly directly (you can reuse all the SYB infrastructure to do that) and make sure that it is only instantiated in one place. That should limit the deprecation warnings to just the instantiation site.

Does that help?

**Comment by alexknvl** [comment]
Have you tried adding a separate case for `java.math.BigDecimal` in your `validator`? This deprecation warning is triggered by `def apply(bd: java.math.BigDecimal): BigDecimal` and I am guessing that it is called because something inside of `everywhere` / `poly` is trying to convert a java BigDecimal to scala BigDecimal using an implicit conversion.

**Comment by alexknvl** [comment]
The only two functions that could somehow trigger that warning are:
```scala
   def apply(bd: BigDec): BigDecimal = apply(bd, defaultMathContext)
  
  @deprecated("This method appears to round a java.math.BigDecimal but actually doesn't.  Use new BigDecimal(bd, mc) instead for no rounding, or BigDecimal.decimal(bd, mc) for rounding.", "2.11")
  def apply(bd: BigDec, mc: MathContext): BigDecimal = new BigDecimal(bd, mc)
```
However, AFAIU calling `apply(bd: BigDec)` is not supposed to trigger it. It must be triggered by a call to `def apply(bd: BigDec, mc: MathContext): BigDecimal`, which is weird to say the least. This deprecation was added in https://github.com/scala/scala/pull/3316 (2.11.x).

I could not reproduce this warning though, at least not with:
```scala
import shapeless._
import shapeless.poly._

case class A(a: java.math.BigDecimal, b: BigDecimal)
case class B(x: A, a: java.math.BigDecimal, b: BigDecimal)

object validator1 extends Poly1 {
	implicit val bigDecimal = 
		at[BigDecimal](_ + BigDecimal(1))
}

object validator2 extends Poly1 {
	implicit val bigDecimal = 
		at[BigDecimal](_ + BigDecimal(1))
	implicit val bigDecimal2 = 
		at[java.math.BigDecimal](BigDecimal(_))
}

object validator3 extends Poly1 {
	implicit val bigDecimal = 
		at[java.math.BigDecimal](BigDecimal(_))
}

object TestMain {
	def main(args: Array[String]): Unit = {
		val b: B = B(A(java.math.BigDecimal.valueOf(10), BigDecimal(10)), 
			         java.math.BigDecimal.valueOf(10), 
			         BigDecimal(10))
		println(everywhere(validator1)(b))
		println(everywhere(validator2)(b))
		println(everywhere(validator3)(b))
	}
}
```
