### ISSUE TITLE
`everywhere` ignores implicit `at[T]` where `T` is a sealed trait

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#326]
`everywhere` ignores implicit `at[T]` where `T` is a sealed trait in shapeless 2.1 on scala 2.11.

I have a domain model made out of sealed traits and case classes. I'm interested in applying a side-effecting validation function to an instance by looking at one the components: e.g.

```scala
sealed trait StringEnum {
  def label: String
}

case class Grouping(label: String) extends StringEnum
case class Channel(label: String) extends StringEnum
case class Thing(label: String) extends StringEnum
...
```

but defining a `Poly1` like this:

```scala
  object validator extends Poly1 {
    implicit def caseStringEnum = at[StringEnum] (s => {add(s) ; s})
  }
```

means that my `add` side effect is never called.

However, looking for specific case classes seems to work ok on my limited test cases (but that is both very verbose and prone to omission error!)

**Comment by milessabin** [comment]
Nope, it's just that cases are invariant.

If you want a single case to handle all of your case classes you'll need something like,

```scala
object validator extends Poly1 {
  implicit def default[S <: StringEnum] = at[S] (s => {add(s) ; s})
}
```

**Comment by fommil** [comment]
:smile: I'll reopen if that doesn't work... but this sounds perfect and I'll go home having achieved something.

**Comment by fommil** [comment]
Incidentally, since I'm just doing a side effect, is everywhere smart enough to do a no-op when it sees that I am performing the identity function?

**Comment by milessabin** [comment]
If you're just traversing then you might be better off using `everything` and yielding `Unit`.

**Comment by fommil** [comment]
I'll try that tomorrow :smile: Yay! I'm using polymorphic functions for something very useful in PROD code :smile:
