### ISSUE TITLE
Odd issue with coproduct

### ISSUE THREAD

**Issue by tpolecat** [milessabin/shapeless#328]
When I do this

```scala
import shapeless._

case class Foo(msg: String)
case class Bar(msg: String)

object Stuff {
  type Blah = Foo :+: Bar :+: Int :+: CNil
  val t = Coproduct[Blah](Foo("hi"))
  t.select[Foo]
}
```

and compile with sbt I get the following:

```
> compile
[info] Compiling 1 Scala source to /Users/rnorris/Scala/copro/target/scala-2.11/classes...
[error] /Users/rnorris/Scala/copro/stuff.scala:9: diverging implicit expansion for type shapeless.ops.coproduct.Selector[Stuff.Blah,Foo]
[error] starting with method hdSelector in object Selector
[error]   t.select[Foo]
[error]           ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 0 s, completed Feb 18, 2015 12:45:26 PM
```

If I remove `Int` from the coproduct or if I replace the `Bar` with `String` it works.

**Comment by milessabin** [comment]
This appears to be caused by the use of a default-to-`null` implicit argument in one of the implicits for `Selector`.

Splitting the method into two, one to handle the present case and one to handle the absent case fixes the problem ... I have no idea why this should affect `Bar` vs. `String`.

**Comment by milessabin** [comment]
I tentatively conclude that this is a scalac bug ... aside from eliminating the default-to-`null` implicit you can also avoid the problem by moving the case class definitions inside `object Stuff`, which shouldn't have any semantic impact at all.

Anyhow, eliminating the `null` is the right thing to do and that appears to fix the problem wherever the case classes are defined. I'll push that shortly.
