### ISSUE TITLE
Weird implicit search failure with ops.hlist.At and Nat._0

### ISSUE THREAD

**Issue by ceedubs** [milessabin/shapeless#336]
Sorry to just point to code, but I think that a small code example can describe this much better than I could with prose. See fairly minimal example [here](https://gist.github.com/ceedubs/119f5fc72c4acd22e52a).

I think Scalac is _probably_ to blame here, but I don't know why this is failing. It's weird to me that it's just for the case of zero, which makes me wonder if the problem lies in the way Nat._0 is defined. If there's not a way to fix it is there a way to work around it?

**Comment by milessabin** [comment]
Sorry ... this one slipped through the cracks.

Very odd ... do you need a fix urgently?

**Comment by ceedubs** [comment]
Well it is blocking my development of typelevel tic-tac-toe, but I think all of my paying clients for that project could wait a bit before shipping it to production ;)

**Comment by milessabin** [comment]
It appears that the constraint on the `Out` parameter of `At.Aux` is to blame. This doesn't completely surprise me ... you're asking scalac to unify `Out` with `Row[R]` and simultaneously infer `R` ... I guess I'm more surprised that it works for non-`_0` than that it doesn't work for `_0`. I have no explanation for the difference between the two cases either.

I do have [a workaround](https://gist.github.com/milessabin/cefecdb4a0fe63d07a0d) though ... it's the usual trick of removing the constraint on the `Out` type. If you do need more structure in `RR` further down a line of chained implicits then you should be able to recover it with additional evidence parameters.

**Comment by ceedubs** [comment]
Thanks for investigating, @milessabin. I haven't yet tried out the workaround when chaining is involved, but if I run into trouble when I get to it, I'll just post a question to the Gitter channel.
