### ISSUE TITLE
Macro error when mapping over an HList with Predef.identity

### ISSUE THREAD

**Issue by pkinsky** [milessabin/shapeless#340]
```scala
scala> (1::HNil).map(Predef.identity _) == (1::HNil)
res1: Boolean = true

scala> (1 :: HNil).map(Predef.identity _) == (1::HNil)
java.lang.AbstractMethodError: fresh$macro$2$2$.caseUniv()Lshapeless/PolyDefns$Case;
  ... 43 elided

scala> (1 :: HNil).map(Predef.identity _) == (1 :: HNil)
java.lang.AbstractMethodError: fresh$macro$3$2$.caseUniv()Lshapeless/PolyDefns$Case;
  ... 43 elided
```

Weirdly enough, this works when there are no spaces surrounding ```::``` in the first HList.

**Comment by milessabin** [comment]
This is a relic of the experimental support for lifting polymorphic methods to Polys. The latter should probably be removed completely and reworked in the light of the recently added support for SAMs.

**Comment by khronnuz** [comment]
This issue still manifests itself when using poly on REPL. Here are steps to reproduce:


1 open sbt
2 > scratchJVM/console
3 > `import poly._`
4 > 
```
object choose extends (Set ~> Option) {
  def apply[T](s : Set[T]) = s.headOption
}
```
5 > `val sets = Set(1) :: Set("foo") :: HNil`
6 > `val opts = sets map choose`
7 that results in `java.lang.AbstractMethodError: choose$.caseUniv()Lshapeless/PolyDefns$Case;`

Note that if steps 3 and 4 are executed together in a single `:paste` block, then it works and no exception is thrown.

**Comment by milessabin** [comment]
This is a Scala compiler bug, mimimized as [SI-9689](https://issues.scala-lang.org/browse/SI-9689).

**Comment by milessabin** [comment]
It also appears that this problem isn't reproducible using the Ammonite REPL.
