### ISSUE TITLE
Derived type classes defined on companion object result in NullPointerException after migrating to 2.1

### ISSUE THREAD

**Issue by sgrif** [milessabin/shapeless#345]
I've been experimenting with using the type class feature in shapeless to remove some boilerplate in the Android framework. After migrating to 2.1, [these lines](https://github.com/sgrif/scala-android-parceling/blob/124f5b23bcfebf15319c1d0f201f3cdc1d03ff3d/src/test/scala/CompositionTest.scala#L39-L45) result in `null` being passed as the implicit parameter [here](https://github.com/sgrif/scala-android-parceling/blob/124f5b23bcfebf15319c1d0f201f3cdc1d03ff3d/src/main/scala/Parceler.scala#L18)

While I can remove the explicit definition of the type class instance and things work, this seems like a very odd behavior.

**Comment by milessabin** [comment]
You need to remove the explicit type annotations on the cached implicits,

```scala
object Foo {
  implicit val parceler = Parceler[Foo]
}

object Bar {
  implicit val parceler = Parceler[Bar]
}
```
If you don't then the val being defined on the LHS will be in scope for the derivation on the RHS and you'll end up seeing the default-initialized `null`.

I appreciate that the normal rule for implicit definition is to _always_ specify a type explicitly, however caching scenarios like this are an exception (I believe the only one).

**Comment by sgrif** [comment]
Removing the explicit type parameter works.

**Comment by sgrif** [comment]
It looks like removing the explicit type parameter causes additional issues. I'm periodically finding that I get an error looking something along the lines of `symbol value inst$macro$48 does not exist in MyClass$$anonfun$3.apply` -- it's resolved by adding an explicit type parameter here, but that brings back the null pointer issue.

**Comment by milessabin** [comment]
Could you try bumping your shapeless dependency to 2.2.0-RC6 and using the new `cachedImplicit` infrastructure,

```scala
object Foo {
  implicit val parceler: Parceler[Foo] = cachedImplicit
}

object Bar {
  implicit val parceler: Parceler[Bar] = cachedImplicit
}
```

**Comment by sgrif** [comment]
I just receive `not found: value cachedImplicit`

**Comment by milessabin** [comment]
Did you update your shapeless dependency to 2.2.0-RC6?

**Comment by sgrif** [comment]
Yes

**Comment by milessabin** [comment]
`cachedImplicit` is part of that release ... have you imported it?

**Comment by sgrif** [comment]
Looks like I needed to add some additional imports. I get the null pointer exception again using the `cachedImplicit`

**Comment by milessabin** [comment]
Ping ...

**Comment by milessabin** [comment]
I'm going to close this now. Please reopen if you can provide a reproduction.
