### ISSUE TITLE
"Higher Rank Polymorphism" pdf link in README is broken

### ISSUE THREAD

**Issue by Daenyth** [milessabin/shapeless#351]
I get a 404: http://www.cs.rutgers.edu/~ccshan/cs252/usage.pdf

**Comment by milessabin** [comment]
Well spotted! It seems to have moved [here](http://camlunity.ru/swap/ocaml/Sexy%20Types.pdf).

README updated ... many thanks :-)

**Comment by Daenyth** [comment]
Thanks :)

**Comment by dk14** [comment]
@milessabin currently the UPDATED link you specified: 
http://camlunity.ru/swap/ocaml/Sexy%20Types.pdf

Redirects here:
https://mp3clips.info/swap/ocaml/Sexy%20Types.pdf

"DOWNLOAD POLYMORPHIC MP3 FOR FREE" and without sms :-D

**Comment by milessabin** [comment]
Oh good grief ...

Thanks for the heads up ... fixed :-)
