### ISSUE TITLE
Change Double.toString syntax in tests for JS

### ISSUE THREAD

**Issue by InTheNow** [milessabin/shapeless#352]
In JS, Double.toString has different semantics than in JVM, especially that a trailing `.0` is omitted - see [Semantics of Scala.js](http://www.scala-js.org/doc/semantics.html)

As a consequence, tests [such as this] (https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/poly.scala#L469) fail in JS

**Comment by milessabin** [comment]
Wasn't this one fixed a while back?

**Comment by milessabin** [comment]
Fixed in 2e1a48ef5826e9df3b0aff66ea0d84341450a4a0.
