### ISSUE TITLE
Release JS RC version 

### ISSUE THREAD

**Issue by InTheNow** [milessabin/shapeless#353]
It would be good to get a RC release for JS, rebased on master

**Comment by InTheNow** [comment]
From gitter:

```
milessabin May 7 2015  
@InTheNow @japgolly sounds good ... can you create a shapeless issue to track whatever's involved in getting a shapeless-2.2.0/Scala.js-0.6.3 release published?
```

Although I've self assigned this on [waffle](https://waffle.io/milessabin/shapeless/cards/552a7788ad9f4c03000a2b24), it would perhaps make more sense if @japgolly could drive this as he has done this previously?

From my viewpoint, my initial thoughts are  something along the lines of:

- @japgolly Get the js branches synced with the jvm ones, still on sjs 0.6 .2. 
- @InTheNow forks locally and forward port test commits to make sure tests pass.
- @InTheNow also tests with local build of sjs0.6.3
- scalajs 0.6.3 is released
- @japgolly upgrades to sjs 0.6 .3.
-  @InTheNow forks locally and forward port test commits to make sure tests pass on 0.6.3
- the rest of the _final_ release process is perhaps best left to @japgolly, as mentioned above

What do you think?

**Comment by japgolly** [comment]
@benhutchison Hey mate, are you able to do this? I'm flooded with work and sickness at the moment.

Also I'd recommend keeping Scala.JS on 0.6.2 as 0.6.3's IR isn't backwards-compatible (where as 0.6.2 will work with any 0.6.x).

**Comment by benhutchison** [comment]
So happens I have a day off work tomorrow, so I'll have a go. First time,
so may proceed slowly, double check a few things etc.

**Comment by InTheNow** [comment]
Thanks for feedback :) It would be a shame if we could not move to 0.6.3 as it has some important changes. Is there no way we could get a 0.6.3 release?

**Comment by benhutchison** [comment]
Re the 0.6.2 v 0.6.3 question:

- IIUC, a shapeless release built on 0.6.2 would still be compatible & useable in projects using 0.6.3

- From a scan of the changes & fixes here [http://www.scala-js.org/news/2015/05/12/announcing-scalajs-0.6.3/], I coudln't see anything obvious that would affect a shapeless library build. 

- OTOH, I'd prefer to releases against the latest published version of Scala.js if possible. I don't properly understand the case for _not_ using 0.6.3. Where is info on "IR isn't backwards-compatible" and the impact this would have?

**Comment by benhutchison** [comment]
@InTheNow Both SJS branches have been freshened from corresponding JVM branches, item 1 in your earlier list. PR 386/7. I believe the next step rests with you?

**Comment by InTheNow** [comment]
Yep, I'm now the critical path :) Apologies for delay, had internet blackout since Wed, only on mobile.

**Comment by InTheNow** [comment]
> Where is info on "IR isn't backwards-compatible" and the impact this would have? 

It's in the release notes on  [the announcement](http://www.scala-js.org/news/2015/05/12/announcing-scalajs-0.6.3/) . I'm also asking on the gitter

**Comment by sjrd** [comment]
Scala.js 0.6.3 contains an obscure compiler fix that was prompted by Shapeless' examples: https://github.com/scala-js/scala-js/issues/1581

If you build Shapeless with 0.6.3, the binaries won't be usable with Scala.js 0.6.{0-2}. On the other hand, upgrading minor versions of Scala.js is supposed to always work trivially, without any source change or build definition change, besides changing the version number. That's why we allow ourselves to break forward binary compatibility: the outcome is only forcing clients to upgrade their Scala.js version, which--barring regressions--is always safe.

**Comment by InTheNow** [comment]
my paralled comment on gitter - "actually... I've found that we need 0.6.3 because of scala-js/scala-js#1581"

I suggest we go with 0.6.3

**Comment by antonkulaga** [comment]
ScalaJS community is very fast in terms of updating, so I suggest to release against the latest SJS version avliable

**Comment by InTheNow** [comment]
Ok - we are now on the penultimate stage above, applying tests to a new branch. I will not have enough time to complete this tonight, but it will be done tomorrow

**Comment by InTheNow** [comment]
Ok - I have tested all plus the new changes on 0.6.3 so LGTM

**Comment by benhutchison** [comment]
Hi @milessabin I pinged you a couple of times on the gitter channel about the SJS release but didn't get a response? Not sure if my meaning was unclear...

So, to restate: I think the release of Shapeless/JS is near ready for publish. The SJS artifact version needs to be set, I think to `2.2.0-RC6`? I can do that if you could confirm that version. 

@InTheNow @japgolly Call out if you see anything else that needs doing before an RC?

Then, the actual publish is done by yourself, IIUC, as you have the appropriate sonatype credentials: I think its checkout the `scalajs-2.11.x` and `scalajs-2.10.x` branches, and in each run `shapeless/publishSigned` within SBT. Ive tried `publishLocal` and the artifacts have the expected name (eg `shapeless_sjs0.6_2.11-2.2.0-SNAPSHOT`) and contents, ie both `.class` and `.sjsir` files.

**Comment by InTheNow** [comment]
Main release done
