### ISSUE TITLE
Tests for casts in JS fail due to differing JS/JVM semantics

### ISSUE THREAD

**Issue by InTheNow** [milessabin/shapeless#355]
Tests [such as TypeableTests.testTuples](https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/typeable.scala#L326) fail on JS as it is a dynamic language and tries to cast anything it can. These types of tests need to be changed on JS only to return false (i.e. they are not empty).

See [Semantics of Scala.js](http://www.scala-js.org/doc/semantics.html)

**Comment by milessabin** [comment]
I guess I'm not surprised that there are issues with `Typeable` given that it uses reflection.

But surely there's an alternative runtime typing mechanism which could be used here instead? I would be happy for the Scala/JS branch to use that as an alternative to JVM reflection in the implementation of `Typeable`.

**Comment by InTheNow** [comment]
Makes sense, and I shall investigate accordingly.

**Comment by milessabin** [comment]
Interestingly, this might make `Typeable` into a portable reflection-replacement.

**Comment by milessabin** [comment]
Wasn't this one fixed a while back?

**Comment by milessabin** [comment]
I'm not clear what happened here ... was Scala.js friendly implementation of `Typeable` added to the Scala.js branches in the end?

**Comment by milessabin** [comment]
Fixed in 2e1a48ef5826e9df3b0aff66ea0d84341450a4a0.
