### ISSUE TITLE
Replace JUnit with integral test framework 

### ISSUE THREAD

**Issue by InTheNow** [milessabin/shapeless#359]
See  https://github.com/milessabin/shapeless/issues/347 for rational/discusssion.

**Comment by InTheNow** [comment]
I've pushed the impl of this to https://github.com/InTheNow/shapeless/tree/fix/359 but there are two issues that I cannot (quickly) fix, both in `typeable testToString` 

- one is a commented out `Todo` that will not compile https://github.com/InTheNow/shapeless/commit/8b1437040fcff6618da34b76feec3c6557e3b159#diff-09386dc83c17179e88988cbaeb0d960eR541
- the other is failed test:

```
[info] ! TypeableTests:testToString failed: Expected (Typeable[Foo]) to equal (Typeable[Foo$3])                                                                                       
[info] Failed: Total 409, Failed 0, Errors 1, Passed 408
```

@milessabin Any chance that you can have a quick look, please?

**Comment by InTheNow** [comment]
btw, you may notice that all the indentation in the test  is "wrong", as the `should {` clause adds an extra level of intention. I've _deliberately_ removed the indentation so as to make it clear what the actual changes are; otherwise, it's impossible as all lines are changed => 14,000 LOC changes

@japgolly @benhutchison Sorry I missed you out on previous comment, my apologies :)

**Comment by InTheNow** [comment]
I've just pushed https://github.com/InTheNow/shapeless/commit/2942e7c8ce27f2f25441f29a3519b2dd59db52eb that "fixes" the two issues mentioned above, but I'm not overly confident with the result.

fyi, the non-compile error message was:

```
[error] (core/test:compile) scala.reflect.internal.Types$TypeError: assignment to non variable
``` 

hence the obvious workaround  with an explicit assignment before the tests assertion.

**Comment by milessabin** [comment]
+1 on preserving the whitespace. We can fix that once we're happy.

**Comment by milessabin** [comment]
Yup, that problem with the `Typeable` test is odd. Another one for @sjrd?

**Comment by sjrd** [comment]
This looks pretty normal to me. Scala would tell you the same thing. Since you enclosed everything in a `should {}` closure, classes, traits, and objects need to have mangled fully-qualified names, and scalac takes care of that. So it is also normal that moving the definitions outside of the `should {}` closure fixes the issue. The change is not dubious, IMO: it is the right way to go about it.

**Comment by sjrd** [comment]
Regarding the `val result =` workaround, I have no idea. It would probably be useful to see the stack trace, at least, to discover which compiler phase is responsible.

**Comment by milessabin** [comment]
Ahh ... yes, that does make sense.

One issue this raises is that there are a number of tests which specifically relate to things (esp. case classes) being defined at the top level vs. locally. These are mostly defined in blocks of code which are simply expected to compile or not rather than being tests per-se, so I think they're probably unaffected, but I'd like to be sure that in changing the test framework we haven't inadvertently changed the semantics of the tests.

**Comment by InTheNow** [comment]
quick point here... this is at the moment pure scala JVM only. So @sjrd is quite right in asserting  that scala would complain ;)

@milessabin Yes, it's quite easy to see what has changed and for sure the small changes need analysis to ensure the semantics are the same and also that new issues have been discovered.

And whilst @sjrd is in the loop: 

- There are two added files [here](https://github.com/InTheNow/shapeless/tree/fix/359/core/src/main/scala/shapeless/test/testinterface), lifted from scalajs. These can also be included via a library, but would be an additional scala dep. The norm would be to just use the library version - @milessabin your call, assuming @sjrd is OK with licence, etc
- the other two issues I have PR'd automatically link up with their respective issuea on [waffle](https://waffle.io/milessabin/shapeless) - see 356/354. This happens if you use the same naming conventions in commits as introduced to my by @sjrd (note 364 does not link as the the most recent commit does not have correct name)

**Comment by sjrd** [comment]
I don't care about the license for these two files, no.

**Comment by milessabin** [comment]
I'm fine for them to be included with the proviso that it doesn't complicate the licensing situation.

There's some scala 2.10 vs. 2.11 macro compat stuff and use of `reify`/`splice` in `TestUtils` ... I have a **strong** preference for taking 2.11 and quasiquotes as canonical, then merging to a 2.10 branch (with macro paradise, so quasiquotes are available) and backporting. That's the way it's done throughout shapeless and I don't want to have different styles of handling 2.10 vs. 2.11 in the codebase.

**Comment by InTheNow** [comment]
re the macro compat: really is no np, was going to do it anyway, just wanted to know your general position before spending too much time on it. Once you are happy with the test migration semantics, etc above, I'll make the changes, squash and push.

**Comment by milessabin** [comment]
Is this finished with now? What's the current status of JUnit for Scala.js?

**Comment by dwijnand** [comment]
It's supported as of Scala.js 0.6.6: http://www.scala-js.org/news/2016/01/25/announcing-scalajs-0.6.6/#support-for-junit

**Comment by milessabin** [comment]
Thanks! I'll bump the Scala.js version to 0.6.6.
