### ISSUE TITLE
2.10 REPL woes - shapeless 2.2.0-RC4

### ISSUE THREAD

**Issue by tpolecat** [milessabin/shapeless#367]
Here is a self-contained example of the REPL failure I'm seeing in **doobie** ... the following works just fine as normal source in 2.10, but the derivation does not work in the REPL. It works fine with 2.11.

```scala
> console
[info] Starting scala interpreter...
[info] 
Welcome to Scala version 2.10.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.7.0_67).
Type in expressions to have them evaluated.
Type :help for more information.
 
scala> :pa
// Entering paste mode (ctrl-D to finish)
 
import shapeless._
 
class Foo[A]
 
object Foo extends ProductTypeClassCompanion[Foo] {
 
  implicit val intFoo = new Foo[Int]
  implicit val stringFoo = new Foo[String]
 
  object typeClass extends ProductTypeClass[Foo] {
    def product[H, T <: HList](H: Foo[H], T: Foo[T]): Foo[H :: T] = new Foo[H :: T]
    def emptyProduct: Foo[HNil] = new Foo[HNil]
    def project[F, G](instance: => Foo[G], to: F => G, from: G => F): Foo[F] = new Foo[F]
  }
 
}
 
implicitly[Foo[(Int,String)]] 
 
 
// Exiting paste mode, now interpreting.
 
<console>:27: error: could not find implicit value for parameter e: Foo[(Int, String)]
              implicitly[Foo[(Int,String)]] 
                        ^
```

**Comment by milessabin** [comment]
Is this a regression relative to 2.1.0 or something you've noticed just now?

**Comment by tpolecat** [comment]
Ah, very good question. This actually doesn't work in 2.0.0 either. The following encoding (which is what's in doobie master at the moment) *does* work, so I can just change your PR back to the way it works now and I think we'll be ok. It looks like there's something in the way `ProductTypeClassCompanion` arranges the machinery that doesn't quite work in 2.10.

```scala
import shapeless._

class Foo[A]

object Foo {

  implicit val intFoo = new Foo[Int]
  implicit val stringFoo = new Foo[String]

  implicit object typeClass extends ProductTypeClass[Foo] {
    def product[H, T <: HList](H: Foo[H], T: Foo[T]): Foo[H :: T] = new Foo[H :: T]
    def emptyProduct: Foo[HNil] = new Foo[HNil]
    def project[F, G](instance: => Foo[G], to: F => G, from: G => F): Foo[F] = new Foo[F]
  }

  implicit def deriveFoo[T](implicit ev: ProductTypeClass[Foo]): Foo[T] =
    macro GenericMacros.deriveProductInstance[Foo, T]

}
```

**Comment by milessabin** [comment]
Err ... `deriveProductInstance` is long gone.

**Comment by milessabin** [comment]
What happens if the definition of object/class `Foo` is compiled and only `implicitly[Foo[(Int,String)]]` is executed from the REPL?

**Comment by milessabin** [comment]
I've tracked this down to a macro implementation class loading issue which affects the Scala 2.10.x REPL and was fixed in 2.11.x here: https://github.com/scala/scala/commit/48cc8b47fcadaa187026ca0422178c9094e4b412.

I might be able to come up with a workaround, but it'll be extremely grubby and I only want to go down that route if this is actually a showstopper for you.

Parking until I get your input on this ...

**Comment by tpolecat** [comment]
My thinking is that I could easily tweak my build to have distinct `Composite`, sql interpolator, and shapeless versions for 2.10 and 2.11. So I think we can push this problem off for now.

**Thank you** for looking into this.

**Comment by milessabin** [comment]
Fixed in https://github.com/milessabin/shapeless/commit/7ce16d7b4b852b2c7f065ec1accf66fb5a140d75.
