### ISSUE TITLE
non-trivial AST breaks the coproduct derivations

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#368]
I extended the `sexp.scala` with a non-trivial AST https://github.com/fommil/shapeless/blob/sexp_ast/examples/src/main/scala/shapeless/examples/sexp.scala

(copied to https://gist.github.com/fommil/1552641fad3daf36b8af for posterity)

but I see this compilation error

```
[error] examples/src/main/scala/shapeless/examples/sexp.scala:171: unreachable code
[error]   val complex = SexpConvert[TokenTree]
[error]                            ^
```

The AST is a little simpler than the one I actually wanted to test, but I don't expect the simplifications to be relevant to shapeless.

**UPDATE**: the break seems to be on the final item, remove `with Term` from the definition of `QualifierToken` and it seems to compile. So it looks like multiple inheritance is flagging up a bug.

**Comment by fommil** [comment]
@milessabin FYI, initial performance tests on JSON data at my work (100GB of data from 7m documents, **not** the AST in this report) suggest that this approach is on-par with super-optimised-to-hell-and-back hand-crafted spray-json marshalling.

**w00t**! :grinning:

(i.e. about 20,000 deserialisations / second). The hand-crafted spray-json finished in 256s and the Spray JSON based on `sexp.scala` took 271s (so a computer scientist's same order of magnitude, but basically the same number to an astrophysicist like me)

I did this in three forms:

1. assigning all marshallers to `implicit vals` so everything is precomputed (340s) (no idea why this is slower)
2. assign just the top level sealed trait to an `implicit val` (271s)
3. no assignation to `implicit val`... everything is calculated when needed for every document (???s)

I'll do a YourKit profile sometime soon, and look at serialisation as well. (BTW, we got gratis YourKit licenses for use in ENSIME, you could easily get the same.)

When I release the Spray JSON code, I'll cook up some scalacheck powered performance tests so that you can grin all the way to the cheese shop (or that nice icecream shop by the pier, since it's nearly summer).

**Comment by milessabin** [comment]
I've just tested the gist you posted and this now appears to compile and run, most likely as a result of the fix for #370, given your comment in the update above.

Could you give this a try once build [#822](https://travis-ci.org/milessabin/shapeless/builds/60454910) has sorted itself out and let me know how you get on.

**Comment by fommil** [comment]
you told me told to send a PR :-P

(luckily I created a branch just incase you changed your mind ;-))

**Comment by fommil** [comment]
actually, I'll add some assertions before sending this as a PR.

**Comment by milessabin** [comment]
Well, I meant that a PR wasn't the right way to report a bug, but now it's not a bug a PR is just fine :-D

So, can I infer from that that you're happy that this issue can be closed as fixed?

**Comment by fommil** [comment]
I've not had a chance to run it yet, but fit works for you then sure close :-)
