### ISSUE TITLE
Unable to derive type class for Scrooge generated product class

### ISSUE THREAD

**Issue by philwills** [milessabin/shapeless#371]
[Scrooge](https://github.com/twitter/scrooge) generates classes representing thrift structs which if you squint hard look a bit like case classes, but are different enough that Shapeless doesn't recognise them as such, so is unable to derive type classes.

I created an example repo (https://github.com/philwills/scrooge-shapeless-example) which if you fire up the console and run the following shows the issue:

```scala
scala> import scrooge.shapeless.example._
scala> import scrooge.shapeless.example.Show._
scala> def s[T](t: T)(implicit s: Show[T]) = s.show(t)
scala> s(Prod(1, "f"))
res0: String = a = 1.0, b = f
scala> s(thrift.Product(1, "f"))
<console>:15: error: could not find implicit value for parameter s: scrooge.shapeless.example.Show[thrift.Product]

```

The generated thrift if we cut out a lot of guff looks like
```scala
object Product extends ThriftStructCodec3[Product] {
   def apply(a: Double, b: String): Product =
    new Immutable(a, b)

  class Immutable(val a: Double, val b: String,override val _passthroughFields: immutable$Map[Short, TFieldBlob]) extends Product {
    def this(a: Double, b: String) = this(a, b, Map.empty)
  }
  
  def unapply(_item: Product): Option[scala.Product2[Double, String]] = Some(_item)
}

trait Product
  extends ThriftStruct
  with scala.Product2[Double, String]
  with java.io.Serializable
{
  import Product._

  def a: Double
  def b: String

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = a
  def _2 = b

  override def productArity: Int = 2

  override def productElement(n: Int): Any = n match {
    case 0 => this.a
    case 1 => this.b
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "Product"
}
```

i.e. it is a non-sealed trait, rather than a class which puts shapeless off the scent.

**Comment by milessabin** [comment]
Just looking at this again ... are you able to summon a `Generic` instance for `Product.Immutable`?

**Comment by philwills** [comment]
```scala
 implicitly[shapeless.Generic[thrift.Product.Immutable]]
```
fails to summon anything.

Incidentally, I did have a stab at trying to address this by broadening the `isCaseClassLike` check, but then ran into issues in `mkProductCases` that were sufficiently deep in the AST that I decided to retreat.

**Comment by milessabin** [comment]
I'm poking around in that area at the moment ... I'll see what I can come up with.

**Comment by milessabin** [comment]
OK, I think this can be done.

It really requires a thorough reworking of the criteria that are used for determining that a type is case class like and its alignment with the mechanism for introducing and eliminating values of that type though, and I don't want to do that in a point release.

I'll revisit for 2.3.0.

**Comment by milessabin** [comment]
Reduced test case,

```scala
import shapeless._

object TProduct {
  def apply(a: Double, b: String): TProduct = new Immutable(a, b)

  def unapply(tp: TProduct): Option[Product2[Double, String]] = Some(tp)

  class Immutable(val a: Double, val b: String) extends TProduct
}

trait TProduct extends Product2[Double, String] {
  def a: Double
  def b: String

  def _1 = a
  def _2 = b

  override def productPrefix: String = "TProduct"

  def canEqual(t: Any): Boolean = true
}

object GenDemo {
  Generic[TProduct]
}
```

Let me know if you think this is missing anything essential from your original ...

**Comment by philwills** [comment]
Sorry, I missed this. I think that reduced test case covers everything important.

**Comment by milessabin** [comment]
See also [this scalac issue](https://issues.scala-lang.org/browse/SI-9029).

**Comment by milessabin** [comment]
OK, the current state of play is that `Generic[TProduct.Immutable]` is fine as is, and `Generic[TProduct]` is fine if `trait TProduct` is marked as sealed.

Would this get you any further with Thrift, or is the sealed issue still a showstopper?

**Comment by philwills** [comment]
I just tried this against a 2.3.0-SNAPSHOT using https://github.com/philwills/scrooge-shapeless-example and am still not able to summon a `Generic[Product.Immutable]` or `Generic[Product]`. As a consumer, rather than author of Scrooge, I'm not sure of the reasoning behind the trait's it produces not being sealed and whether there would be an issue with changing that.

**Comment by milessabin** [comment]
It was the secondary constructor in `Product.Immutable` which was causing the problem there, and I now have this working for that case (not pushed yet, needs some cleanup).

Is this likely to be sufficient for your scenario? Bear in mind that due to the lack of sealing on the `Product` trait you will only get an automatic `Generic` instance if you explicitly refer to the concrete type `Product.Immutable`.

**Comment by milessabin** [comment]
@philwills I've added [this](https://github.com/milessabin/shapeless/blob/287707228b24bcbde30e43b7b5a9d20c18fb0333/core/src/test/scala/shapeless/generic.scala#L1088-L1125) compilation test, which corresponds directly to the generated Thrift output.

Note that because the trait is unsealed we won't be able to summon a `Generic` instance for it. Instead we have to summon a `Generic` instance for the concrete class `TProduct.Immutable`.

Is this good enough for your scenario?
