### ISSUE TITLE
Singleton Types for Value Classes

### ISSUE THREAD

**Issue by Tzbob** [milessabin/shapeless#379]
```scala
  class ValueTest(val x: Int) extends AnyVal

  object PathDependentSingleton2 {
    val x = new ValueTest(5)
    val wX = Witness(x)
    type XT = wX.T
  }
```

This compiles just fine but I have no idea what ```XT``` is supposed to be here. ```x.type``` is an invalid expression since ```x``` is not subclassing ```AnyRef``` so I'm not sure if this behavior is intended? 

If it is then Shapeless Witness macros add support for singleton types on value classes by treating them as reference types which may lead to un{expected, documented} behavior? An example that could possibly confuse people:

```scala
    val x = new ValueTest(5)
    val y = new ValueTest(5)
    val wX = Witness(x)
    val wY = Witness(y)
    implicitly[wX.T =:= wY.T]
```

**Comment by milessabin** [comment]
Would you mind taking a look to see if this is still an issue for shapeless-2.2.2?

**Comment by Tzbob** [comment]
On master (2.2.3) it's still odd that the following compiles:

```scala
  object PathDependentSingleton3 {
    val x = new ValueTest(5)
    val wX = Witness(x)
  }
```
Since it's invalid Scala to reference the singleton type of a Value class:

```scala
  object PathDependentSingleton3 {
    val x = new ValueTest(5)
    val wX = Witness(x)
    implicitly[wX.T =:= x.type] 
  }

[error]  found   : shapeless.SingletonTypesTests.PathDependentSingleton3.x.type (with underlying type shapeless.ValueTest)
[error]  required: AnyRef
[error] Note that ValueTest extends Any, not AnyRef.
[error] Such types can participate in value classes, but instances
[error] cannot appear in singleton types or in reference comparisons.
[error]     implicitly[wX.T =:= x.type]
```

I think it's best not to allow Value classes in Witness at all, right? That's what I meant in the original post, this behavior might confuse people unless it's explicitly stated somewhere.

**Comment by milessabin** [comment]
Agreed. It's just that there were some changes in the `Witness` materializer and it was at least conceivable that this might have come out in the wash.

Thanks for the update :-)

**Comment by milessabin** [comment]
This decision has been reversed in https://github.com/milessabin/shapeless/commit/e70f01ecdcca9c2a991fb045b002dc32e9d88388. As of SIP-23 value types do admit singleton types of this form, and the exclusion no longer seems well motivated.
