### ISSUE TITLE
performance problems in coproduct derivations

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#381]
as demonstrated in
https://github.com/fommil/shapeless/commit/2ea5adfbe315b79fa082019013935faff7fb035a

i.e. adding
```scala
/** Example AST with performance problems */
package sexp.big {
  sealed trait Base
  case object Foo01 extends Base
  case object Foo02 extends Base
  case object Foo03 extends Base
  ....
}
...
  // a performance bottleneck example
  import sexp.big._
  val slow = SexpConvert[Base]
```

to `sexp.scala` we are getting **very** slow compilation times. Looks quadratic with a big constant factor.

@rorygraves you would be interested in the compiler CPU profile. It seems to be spending all its time recalculating hashcodes. Grab my branch of shapeless and type `examples/runMain shapeless.examples.SexpExamples` to kick off the compiler. You'll have **plenty** of time to attach visualvm. Add yourkit to `.jvmopts`.

**Comment by fommil** [comment]
FYI, I've been unable to come up with a satisfactory workaround for this. If the compile time gets too high, the only thing that can be done is to fall back to manually written marshallers :sob:

**Comment by milessabin** [comment]
I don't have time to look into it today, but one option it might be worth investigating is getting rid of the string singleton types as early as possible. In `deriveInstance` you could try mapping the representation type (`G`) from the form,

```scala
FieldType[K1, V1] :: FieldType{K1, V2] ... :: HNil
```
to,
```scala
(String, V1) :: (String, V2) ... :: HNil
```
and similarly for coproducts. That will eliminate all the singleton typed strings previously embedded in `FieldType` and I think is probably safe here: you're only relying on the labels as simple values in the rest of the derivation and not things which might be used to index a type.

**Comment by fommil** [comment]
I'm tracking this to https://github.com/typelevel/scala/blob/2.11.x/src/reflect/scala/reflect/internal/Types.scala#L1058

which means that the compiler must be creating an excessive number of `UniqueType` instances.

**Comment by fommil** [comment]
also MethodInvoke on SingletonTypeMacros is extremely slow

**Comment by fommil** [comment]
this is crazy, it looks like `Object.hashCode` is really slow. I wonder why that would be. I thought it was basically free.

**Comment by rorygraves** [comment]
Nothing is free if you call it enough times.

**Comment by fommil** [comment]
could be a ghost, some people report seeing similar high CPU on `Object.hashCode` in java land saying that it seems false http://stackoverflow.com/questions/3124676

**Comment by fommil** [comment]
@milessabin (this isn't exactly 100% typesafe, I need a few more restrictions) but I've pushed a change that uses `String` instead of `FieldType`. But I have no idea how to turn the `LabelledGeneric` into this representation, i.e. change `deriveInstance`. Any ideas? https://github.com/fommil/shapeless/commit/a848f7a13d8d9d1b0f8b57a913561cd3f16e95ca

**Comment by fommil** [comment]
@milessabin I managed to catch @alexarchambault on gitter and he helpfully recommended using `ops.record.Fields` and `ops.union.Fields` to get the `(String, V) ::/:+: Rest` representations. The only problem is that we can't work out how to pass the actual value of the `String` down the chain... we can't use the `Witness` for the `K` anymore. Any further ideas?

**Comment by retronym** [comment]
I inspected the macro expansion for quadratic patterns in generated code and found a few.

Based on that, here's an improvement to the performance:

https://github.com/milessabin/shapeless/compare/master...retronym:topic/coproduct-speed

Please feel free to adapt that into a fix. I haven't submitted it as a PR because I'm not sure how you'd like things arranged.

I think there is still a problem with the implicit expansion that invokes `cpZipWithKeys`, but I haven't attempted to solve that.

**Comment by fommil** [comment]
awesome! It is indeed faster, but I'm getting a runtime error in the `sexp.scala` for the simpler examples, so this changes the functional behaviour somehow.

**Comment by fommil** [comment]
both the "wibble" example and the "less trivial example" are failing with classcast exceptions.

**Comment by retronym** [comment]
Yep, I just noticed it doesn't pass tests yet.

**Comment by retronym** [comment]
Okay, I had an off-by-one error in `unsafeMakeCoproduct`. Just pushed a fix.

**Comment by rorygraves** [comment]
cool stuff!

**Comment by fommil** [comment]
wow! thank you thank you thank you!

Please cherry pick my commit #2ea5adf so that we have a permanent test for this regression and then lets gang up on @milessabin to release this

**Comment by fommil** [comment]
btw, takes 10 seconds now on my machine... down from killing the compiler process after 20 minutes of eating all my CPU cycles and getting nowhere.

**Comment by milessabin** [comment]
What! Seriously! Awesome! Thanks @retronym!

**Comment by milessabin** [comment]
@fommil can you turn this and your test into a PR that I can merge?

**Comment by rorygraves** [comment]
The trick is apparently to accuse the scala compiler of being slow in your talk then @retronym fixes it.
Got to remember that trick ;)

**Comment by milessabin** [comment]
:-D

**Comment by rorygraves** [comment]
now I just need to wrap up the String one I mentioned into a script that I can blame on the compiler so @retronym  can fix it and I can take the rest of the year off :wink:

**Comment by fommil** [comment]
I can do that, unless @retronym does it first
