### ISSUE TITLE
Implicit derivation failing when using cached implicits + orphan derivation at the same time

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#391]
See the last two commits here: https://github.com/alexarchambault/argonaut-shapeless/commits/test/orphans and here: https://github.com/alexarchambault/scalacheck-shapeless/commits/test/orphans.

Cached implicits were enabled. The first of the two commits enables orphan derivation by default, which breaks implicit derivation. The last of the two commits disables cached implicits, which makes things work again.

I'm afraid I can't derive a minimalist example right now... The code bases of argonaut-shapeless and scalacheck-shapeless aren't that large though.

**Comment by milessabin** [comment]
It'd be really helpful if you could find some time to post a minimization. I'll punt this until the next release for now.

**Comment by alexarchambault** [comment]
I finally set up a minimal example here: https://github.com/alexarchambault/shapeless-cached-implicits-vs-orphan-derivation

It seems that implicit derivation through `the` fails with orphan derivers. (And `cachedImplicit` is using `the` internally)

**Comment by milessabin** [comment]
Thanks for that ...

**Comment by milessabin** [comment]
This doesn't solve the problem for `the` in general, but it does solve the problem for `cachedImplicit` by replacing `the` with `implicitly` in its expansion.
