### ISSUE TITLE
HList#updateWith is leaking

### ISSUE THREAD

**Issue by l15k4** [milessabin/shapeless#408]
Hey,

in `shapeless 2.1.0`, `scala 2.11.6`, `OpenJDK 1.7` if I use :
```
hlist.updateWith[Map[String,Any], Map[String,Any], ReqCtx](rec => rec ++ (extSource - extMergeKey))
```
in my application, it dies on `OutOfMemoryError: GC overhead limit exceeded` no matter how much `-Xmx` I set... I'm updating HLists very frequently

However if I change it to :
```
hlist.replace[Map[String,Any]](hlist.select[Map[String,Any]] ++ (extSource - extMergeKey))
```

It is alright and it needs just -Xmx128m... There must be some sort of hidden reference from the new HList to the old one so that the old one is never GCed ... if you use `updateWith` method....  

I think it might be easily reproduced by just doing `updateWith` like 1 000 000 times and it will crash on `OutOfMemoryError: GC overhead limit exceeded` or OutOfMemory error, depending on which GarbageCollector you are using ... I'm using `-XX:-UseConcMarkSweepGC`

**Comment by milessabin** [comment]
It looks like you must be closing over something large which is getting captured in the resulting `HList` somehow. That's very dependent on the surrounding context though ... are you able to reproduce this with a small standalone example that I could look at locally?

**Comment by l15k4** [comment]
I'll try to reproduce it in the evening... so far it seems that it happens only with big immutable hash maps with a few thousands of entries, although the values are just Strings mostly and other primitives. Seems like the problem is conditioned by presence of `rec ++ (extSource - extMergeKey)` which is really just `immutable.Map ++ (immutable.Map - entry)`  but the amount of data flowing is max 50MB at the peak and `OutOfMemoryError: GC overhead limit exceeded` happens even if I feed it with way too much heap memory...

**Comment by milessabin** [comment]
My gut feeling is that this isn't specifically an issue with shapeless ... I think you would probably see a similar leak doing the equivalent with a vanilla list. If that's not the case then I definitely want to know about it. Thanks for investigating :-)

**Comment by l15k4** [comment]
Your gut feeling was right :-) I was getting a little paranoid because it was really tough to find this one. Thanks !

**Comment by milessabin** [comment]
Thanks for the update.
