### ISSUE TITLE
OSGI settings place publish-local jar in .ivy2/.../bundles/ 

### ISSUE THREAD

**Issue by rrmckinley** [milessabin/shapeless#42]
The OSGI settings in Build.scala cause a SNAPSHOT build from publish-local to place jar files in .ivy2/.../bundles/. The expectation is .ivy2/.../jars/. I did not easily find a way to depend on the OSGI bundle with sbt. My workaround is to comment out osgiSettings and lines beginning with OsgiKeys.

Could OSGI publishing be moved to a different target? Wanting to try the SNAPSHOT should be easier from publish-local. Thanks.

**Comment by fommil** [comment]
I'm seeing this with `publishLocal` --- the jar goes to `bundles` instead of `jars`. And it's not transparent to me when I attempt to depend on the SNAPSHOT I just published from another project.

Workaround is to remove the OSGI plugin and its settings when doing a `publishLocal`.

Seems like an upstream bug to me.

**Comment by mpilquist** [comment]
I'm fairly sure this behavior is intentional. The JAR location in a local ivy repository is transparent if you are using Ivy to do the resolution.

**Comment by fommil** [comment]
it's looking at a specific location in the `jars` directory and not seeing it. Try it yourself with the `ensime-server` project... bump shapeless to 2.2.2-SNAPSHOT.

**Comment by mpilquist** [comment]
Just tried in a standalone project and it appears to work fine:

```
› cat build.sbt
libraryDependencies += "com.chuusai" %% "shapeless" % "2.2.2-SNAPSHOT"
resolvers ++= Seq(
  Resolver.sonatypeRepo("releases"),
  Resolver.sonatypeRepo("snapshots")
)

› cat project/build.properties
sbt.version=0.13.8
```
Here's the output
```
[info] Loading project definition from /Users/mpilquist/Development/scratch/sam/project
[info] Updating {file:/Users/mpilquist/Development/scratch/sam/project/}sam-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to sam (in build file:/Users/mpilquist/Development/scratch/sam/)
> console
[info] Updating {file:/Users/mpilquist/Development/scratch/sam/}sam...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://oss.sonatype.org/content/repositories/snapshots/com/chuusai/shapeless_2.10/2.2.2-SNAPSHOT/shapeless_2.10-2.2.2-SNAPSHOT.jar ...
[info]  [SUCCESSFUL ] com.chuusai#shapeless_2.10;2.2.2-SNAPSHOT!shapeless_2.10.jar(bundle) (1201ms)
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.10.4, 2.10.3) -> 2.10.5
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Starting scala interpreter...
[info]
Welcome to Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_25).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import shapeless._
import shapeless._

scala> val xs = 1 :: 2 :: "hi" :: HNil
xs: shapeless.::[Int,shapeless.::[Int,shapeless.::[String,shapeless.HNil]]] = 1 :: 2 :: hi :: HNil
```

**Comment by fommil** [comment]
try it with `ensime-server`
