### ISSUE TITLE
everywhere does not work on sealed families that have a `Symbol` field anywhere

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#422]
Reproduction:

Add this line to `sybclass.scala`

```scala
  case class Magician(trick: Symbol) extends Subunit
```

see this failure

```
[error] (examples/compile:compileIncremental) scala.reflect.internal.FatalError: unexpected UnApply scala.this.Symbol.unapply(<unapply-selector>) <unapply> ((pat$macro$74 @ _))
```

This is blocking https://github.com/ensime/ensime-server/issues/1006 :cry:

**Comment by milessabin** [comment]
No time to look at this properly right now, but I think a quick workaround would be to define a `Data` or `DataT` instance for `Symbol`.

**Comment by fommil** [comment]
One of these? I have no idea how to begin.

```
trait Data[F, T, R] extends Serializable {
  def gmapQ(t: T): List[R]
}
```

**Comment by milessabin** [comment]
If I had this (in the same scope as `case class Magician`) it compiles,

```scala
implicit def symbolDataT[F <: Poly]: DataT.Aux[F, Symbol, Symbol] =                                                             
  new DataT[F, Symbol] {
  type Out = Symbol
  def gmapT(t: Symbol) = t
}
```

**Comment by fommil** [comment]
excellent, that seems to fix it for my actual use case as well.

**Comment by milessabin** [comment]
Cool ... this is a bug though, and that instance is just a workaround for it, so watch this space.

**Comment by milessabin** [comment]
Minimized to,

```scala
implicitly[Lazy[Generic[Symbol]]]
```

**Comment by fommil** [comment]
interesting, this might be related to my spray-json-shapeless problems. There it seemed that shapeless was too eager to generate `LabelledGeneric`s for `Symbol` and I had to override with the built-in spray-json `JsonFormat[Symbol]`.

**Comment by milessabin** [comment]
I think that's most likely the "derived orphans trump explicit instances" problem that I've promised to fix for you. So probably not related.

**Comment by milessabin** [comment]
It turns out this isn't `Symbol` specific ... it's reproducible with any case class like type with an `unapply`, eg.,

```scala
class Foo(val s: String)
object Foo {
  def unapply(f: Foo): Option[String] = Option(f.s)
}

object GenericSym {
  implicitly[Lazy[Generic[Foo]]]
}
```
The bug is due to the `Generic` for the type, which generates a pattern match using the extractor, being passed though `Lazy` which internally results in the `Generic` instance being untypechecked and retypechecked and then falling foul of [SI-5465](https://issues.scala-lang.org/browse/SI-5465).
