### ISSUE TITLE
Add variants of Fn{To,From}Product which are parametric in the result type

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#438]
See [this gist](https://gist.github.com/milessabin/cab5661217ec47bbddad) for a motivating example.

A result type parametric `Fn{To,From}Product` would allow us to constrain the shape of the arguments to an arbitrary arity function type without having to commit a particular result type. In the example shown we've worked around this by constraining an `HList` argument `L` to a `Function1` and then have an implicit conversion from an arbitrary arity function to that `L => R`. This only works if the type of the function is fully known, hence the type annotations on the function's arguments.

**Comment by joroKr21** [comment]
@milessabin do you mean something like `FnGeneric` in this PR: typelevel/kittens#223
Do you think it makes sense to contribute it to shapeless instead?

**Comment by milessabin** [comment]
Honestly I have no recollection of what this issue is about and the description and the gist are leaving me none the wiser.

I don't have any strong feelings about whether that PR belongs in kittens or here.

**Comment by joroKr21** [comment]
> I don't have any strong feelings about whether that PR belongs in kittens or here.

Me neither. Then I would keep it in kittens.

**Comment by joroKr21** [comment]
If anyone needs this they can use the version from Kittens: https://github.com/typelevel/kittens/pull/223
