### ISSUE TITLE
Using `the` still outputs a non-refined type

### ISSUE THREAD

**Issue by gabro** [milessabin/shapeless#439]
With reference to [this SO question](http://stackoverflow.com/questions/31747143/how-to-create-typeclass-with-hlist-existential-member/31748667#31748667), I expected using `the` in place of `implicitly` would solve the issue, but it doesn't.

The type member of the type inferred by `the` is `View#Result`, whereas it should be `Int :: Int :: Int :: HNil`.

As shown in the answer, using an implicit parameter list instead of a context bound + `the`/`implicitly` solves the issue and propagates the fully refined type.

Could this be a bug of `the` or is this intended behavior?

Here's a reproductible MWE

```scala
import shapeless._, poly._

trait View[R] {
  type Result <: HList
  def apply(r: R): Result
}

case class Viewable(x: Int, y: Int, z: Int)

implicit def provideView[R, L <: HList](implicit gen: Generic.Aux[R, L]) =
  new View[R] {
    type Result = L
    def apply(r: R): Result = gen.to(r)
  }

/*
// This works
object View extends LowPriorityLiftFunction1 {
  implicit def atView[R](implicit v: View[R]) = at[R](v.apply(_))
}

// This doesn't work, as expected: implicitly loses refinement
object View extends LowPriorityLiftFunction1 {
  implicit def atView[R: View] = at[R](implicitly[View[R]].apply(_))
}
*/

// This should work, but it doesn't
object View extends LowPriorityLiftFunction1 {
  implicit def atView[R: View] = at[R](the[View[R]].apply(_))
}

val h = View(Viewable(1, 2, 3)).head
```

**Comment by travisbrown** [comment]
The `the` macro won't be able to capture a refinement in a generic context where the refinement isn't statically known, so I think this is the "intended" behavior, in the sense that you can't really expect better.

If you expect a method's return type to include type members from a parameter, I'd suggest always making that explicit (especially if the method itself is implicit):

```scala
object View extends LowPriorityLiftFunction1 {
  implicit def atView[R](implicit v: View[R]): Case.Aux[R, v.Result] = at[R](v(_))
}
```

I know I have a bad habit myself of leaving type annotations off of `poly` cases in SO answers—I'm working on it. :smile:

**Comment by milessabin** [comment]
Sorry I didn't respond to this earlier. I agree with Travis's analysis here: the refinement isn't propagated from the implicit argument/context bound into the body of the method, hence `the` is only seeing the unrefined type, namely `View[R]`.

As a general rule I would say that the use of an implicit parameter block is idiomatic here. Even though `the` is somewhat better behaved than `implicitly` I would mainly expect to use it either interactively on the REPL or in test code rather than as a mechanism for referring to an implicit argument in mainline code.

**Comment by gabro** [comment]
It makes sense, thank you both for the answers.

**Comment by travisbrown** [comment]
Actually the `the` macro _could_ inspect the type for type members and make sure they were included on the static type of the instance it returns, right? It'd be kind of messy, and I still think the type-annotation solution is more appropriate here, but I think it would be possible to write a `the` that would do what you're asking, @gabro.

**Comment by milessabin** [comment]
Yes, I guess it could.

It's isn't actually the result type annotation which is doing the work here tho' ... the following definition of `View` also works fine,

```scala
object View extends LowPriorityLiftFunction1 {                                                                                       
  implicit def atView[R](implicit v: View[R]) = at[R](v(_))
}

scala> val h = View(Viewable(1, 2, 3)).head
h: Int = 1
```
It's the direct use of the implicit argument rather than the result type which is doing the work here.
