### ISSUE TITLE
Support for lifting an argument list of Int literals to an HList of Nat

### ISSUE THREAD

**Issue by AndreasKostler** [milessabin/shapeless#445]

**Comment by triggerNZ** [comment]
@AndreasKostler do you mean something like:

```natList(1,2,3)``` returning ```1::2::3::HNil``` but ```natList(-2)``` not compiling?

**Comment by milessabin** [comment]
I think @AndreasKostler meant 581e01f2 ... should this be closed now?

**Comment by AndreasKostler** [comment]
I think @milessabin is correct - in both regards.

**Comment by milessabin** [comment]
Awesome ... closing as fixed :-)
