### ISSUE TITLE
Strange(?) behaviour of `Tupler` on `HList` of `HList`

### ISSUE THREAD

**Issue by AndreasKostler** [milessabin/shapeless#454]
I am kind of confused about the behaviour of `Tupler` on nested `HList`:
```scala
val l = 1::2::HNil ::3::4::HNil
l: shapeless.::[Int,shapeless.::[Int,shapeless.::[shapeless.HNil.type,shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]]]] = 1 :: 2 :: HNil :: 3 :: 4 :: HNil
l.tupled
(1,2,HNil,3,4)
```
Whereas I'd expect something like
```scala
l.tupled
((1,2),(3,4))
```
Is this the intended behaviour?

**Comment by ceedubs** [comment]
I don't think your `l` is what you think it is. You are actually putting the `HNil` object into the middle of an `HList`.

I think what you meant to do was something like this:

```scalascala> val l = (1 :: 2 :: HNil) :: (3 :: 4 :: HNil) :: HNil
l: shapeless.::[shapeless.::[Int,shapeless.::[Int,shapeless.HNil]],shapeless.::[shapeless.::[Int,shapeless.::[Int,shapeless.HNil]],shapeless.HNil]] = 1 :: 2 :: HNil :: 3 :: 4 :: HNil :: HNil

scala> l.tupled
res6: (shapeless.::[Int,shapeless.::[Int,shapeless.HNil]], shapeless.::[Int,shapeless.::[Int,shapeless.HNil]]) = (1 :: 2 :: HNil,3 :: 4 :: HNil)
```

The `.tuple` command only goes one layer deep. So if you wanted to also turn each of the two `HList`s into a tuple, you would have to call `.tupled` on them.

**Comment by milessabin** [comment]
@ceedubs is spot on.

**Comment by AndreasKostler** [comment]
Right, my oversight. However, is there a reason why `.tupled` only does go one layer deep? Disclaimer - I haven't looked at the implementation, just wondering.

**Comment by milessabin** [comment]
I think a one layer operation makes sense as a primitive. Would you expect `size` on a `List[List[Int]]` to give you the number of `List[Int]` in the outer list or the total number of `Int`s in the structure?

**Comment by AndreasKostler** [comment]
No, but on the same token, would you expect `flatten` on nested Lists to
only flatten one level? Incidentally, this is what `List.flatten`
does...Which in my opinion doesn't make sense. This came up during the
implementation of `flatten` for `HList` - hence the opinionated view I
guess.
I am happy for this to be closed - it was just for clarification.

**Comment by fthomas** [comment]
@AndreasKostler I wonder how the signature of `List.flatten` would look like if it could flatten nested lists?

**Comment by AndreasKostler** [comment]
This is modelled after Miles' nice example for Tuples...

```scala
trait LowPriorityFlatten extends Poly1 {
    implicit def default[T] = at[T](_::HNil)
}
object flatten extends LowPriorityFlatten {
    implicit def caseTuple[L <: HList](implicit fm: FlatMapper[flatten.type, L]) = at[L](_.flatMap(flatten))
}
```

**Comment by milessabin** [comment]
The current `Tupler`/`.tupled` are behaving as designed, and I think they should stay that way, so I'm going to close this issue for now.

But a recursive operation would also be useful, and I'd be happy to be on the receiving end of a PR that added one :-)

**Comment by AndreasKostler** [comment]
;) I'll see what I can do
