### ISSUE TITLE
Add a way to transform any HList into a Monoid of some Coproduct

### ISSUE THREAD

**Issue by vil1** [milessabin/shapeless#457]
Given a `Monoid` instance `F`, it is possible to convert any `HList` into a `F[C]` where `C` would be the smallest coproduct that encompasses all the input `HList` elements' types.

For example the desired function would transform 
`1 :: "Foo" :: true :: 42 :: HNil` 
into a 
`F[Int :+: String :+: Boolean :+: CNil]` 
for any given `F`.

See [this gist](https://gist.github.com/vil1/2c45599bc01c05353476) for a stub implementation (specialized for the `List` monoid)

**Comment by milessabin** [comment]
I'd be happy to have a PR for this for 2.3.1 and I also think that something along these lines will most likely drop out of the SMC redesign in shapeless 3.0.0.

**Comment by vil1** [comment]
@milessabin I fail to find a `Monoid` definition in `master` (except the one defined for tests). Is that something that is planned for addition in 2.3.0, in which case I would patiently wait for it, or would a specialized version (like in the gist proposed in the description above) be enough for now ?

**Comment by milessabin** [comment]
Good point. Maybe it belongs in [Kittens](https://github.com/milessabin/kittens) instead?

**Comment by vil1** [comment]
I'm not very familiar with Kittens (yet). Is transforming a `HList` to a `F[C]` (with `F:Monoid` & `C <: Coproduct`) something valuable for Kittens users ?

**Comment by alexarchambault** [comment]
@vil1 You should use `CanBuildFrom` for this, like `ToTraversable` does for example. It's (very) vaguely like having a monoid - you create a builder and add elements to it.

**Comment by vil1** [comment]
@alexarchambault that's a pretty trick I would've probably never think of ! I'll give it a try tonight.
