### ISSUE TITLE
cachedImplicit presentation compiler hack

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#458]
in ENSIME we have a file that takes 2 minutes to compile, and it (paraphrasing) looks like this :

``` scala
object Formats extends FamilyFormats {
  implicit val foo: JsonFormat[EnsimeIn] = cachedImplicit
  implicit val bar: JsonFormat[EnsimeOut] = cachedImplicit
}
```

c.f. https://github.com/ensime/ensime-server/blob/master/jerk/src/main/scala/org/ensime/jerk/JerkFormats.scala#L39

it is the kind of pattern that I'm encouraging people to use with spray-json-shapeless (and sexpress when I get round to writing it properly).

the thing is, when anyone opens this file in ENSIME, the presentation compiler also takes about 2 minutes to infer the types.

As you know, there is no way to interrupt the presentation compiler when it really gets going, so basically this knocks out the presentation compiler for all tasks until it finishes. And it'll happily do the whole thing again if the file is trivially modified or the file is closed and opened again.

This is a problem with all complex implicits when using shapeless.

From an ENSIME user perspective, giving back control of the presentation compiler is far far far more important than getting it right. I believe that the vast majority of ENSIME (and scala-ide) users would be happy with the presentation compiler effectively ignoring this code.

Until the presentation compiler allows such interruptions, I propose a hack. `cachedImplicit` expands something like this

``` scala
  implicit val foo: JsonFormat[EnsimeIn] = {
    def foo: JsonFormat[EnsimeIn] = ???
    implicitly[JsonFormat[EnsimeIn]]
  }
```

but if it expanded like so when run **only as the presentation compiler** (or perhaps only in presentation compiler and some setting is activated):

``` scala
  implicit val foo: JsonFormat[EnsimeIn] = null // or throw a GuruMeditationFailure
```

then that would be pretty fantastic because the code would typecheck immediately.

I'm aware that this won't fix all the presentation compiler performance problems with shapeless (there are also a few non-performance related ones) but I believe this works around the biggest problem that I've seen. It'll mean that the presentation compiler cannot be trusted to catch missing `cachedImplicits`, but could it ever be trusted to do this anyway?

**Comment by fommil** [comment]
note to self, start here https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/package.scala#L110

**Comment by milessabin** [comment]
I think I might be able to do something here.

I could arrange for `cachedImplicit[T]` to not perform the resolution on the RHS iff the following two conditions are met,

1. We're running in the context of the presentation compiler.
2. An implicit of type `TrustMe[T]` is in scope.

Would that work for you?

**Comment by fommil** [comment]
It seems a bit nasty that an implicit makes it to runtime for this and that code changes are needed by the user. Why not just use an annotation in that case?

**Comment by fommil** [comment]
Also, bare in mind that cachedImplicit doesn't work at all in the PC, even for simple things. I'm also not sure if this will work as a macro, but it's worth investigating.

**Comment by milessabin** [comment]
An annotation would work too.

The effect of this is that,

```scala
@trustMe val foo: T = cachedImplicit
```

would be rewritten as,

```scala
val foo: T = null
```

If that doesn't get along well with the PC then I'm afraid you're doomed.

**Comment by fommil** [comment]
well not entirely doomed. If that doesn't work it probably means that a presentation compiler plugin is the answer. I was going to try coding up this exact feature last night when you threw me the curveball with the typed class example, which appears to completely confuse the compiler :smile:

**Comment by milessabin** [comment]
Do you want this or not?

**Comment by fommil** [comment]
Definitely want! I'm incredibly interested to see if this can be implemented as a macro vs compiler plugin.

**Comment by milessabin** [comment]
Okey doke ... I'll see what I can do ...

**Comment by fommil** [comment]
alternative behaviour under the presentation compiler can now be asserted using http://github.com/ensime/pcplod

**Comment by fommil** [comment]
we created a project to do this, nothing needed from shapeless https://github.com/ensime/ensime-plugin-implicits
