### ISSUE TITLE
Add typeclass giving access to constructor default arguments

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#461]
/cc @travisbrown

**Comment by alexarchambault** [comment]
I did something similar while benchmarking type class derivation some time ago: https://github.com/alexarchambault/upickle-pprint/blob/topic/shapeless/upickle/shared/src/main/scala/upickle/experimental/Default.scala

Could be backported here.

**Comment by milessabin** [comment]
Go for it! :-)
