### ISSUE TITLE
Default type class broken for top-level classes

### ISSUE THREAD

**Issue by cvogt** [milessabin/shapeless#474]
@alexarchambault playing around with the Default type class. Great job. Only it doesn't work for top-level classes for me :). If you move `CC` in the test out of DefaultTestDefinitions into the top-level it produces HNil instead of the record.

**Comment by alexarchambault** [comment]
I used this type class quite a bit, and somehow managed not stumble upon this! Good catch :-)

https://github.com/milessabin/shapeless/pull/475 should fix it.

**Comment by cvogt** [comment]
Sweet, thx :)!
