### ISSUE TITLE
No implicit Generic[A] available if A is defined in an expression

### ISSUE THREAD

**Issue by mpilquist** [milessabin/shapeless#48]
Welcome to Scala version 2.10.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_51).
    Type in expressions to have them evaluated.
    Type :help for more information.

    scala> import shapeless._
    import shapeless._

    scala> { case class Foo(x: Int, y: String); implicitly[Generic[Foo]] }
    <console>:11: error: could not find implicit value for parameter e: shapeless.Generic[Foo]
                  { case class Foo(x: Int, y: String); implicitly[Generic[Foo]] }
                                                                 ^

    scala> def foo = { case class Foo(x: Int, y: String); implicitly[Generic[Foo]] }
    <console>:10: error: could not find implicit value for parameter e: shapeless.Generic[Foo]
           def foo = { case class Foo(x: Int, y: String); implicitly[Generic[Foo]] }
                                                                    ^

    scala> case class Foo(x: Int, y: String); implicitly[Generic[Foo]]
    defined class Foo
    res1: shapeless.Generic[Foo] = $1$$1@7b63a14

One common use case for this is writing tests with ScalaTest or Spec2. Something like:

    class MyTest extends WordSpec {
      "my code" should {
        case class Foo(x: Int, y: String)
        "do something interesting" in {
          ...
        }
      }
    }

**Comment by milessabin** [comment]
I can't reproduce this any longer. I expect that it was fixed as a result of one of the many prefix related fixes in the last few releases :-)
