### ISSUE TITLE
License file issues

### ISSUE THREAD

**Issue by JanBessai** [milessabin/shapeless#482]
The license file is a vanilla copy of the Apache License. Its text says that the file needs to be modified, including mentioning of a copyright owner [here](https://github.com/milessabin/shapeless/blob/master/LICENSE#L190).

**Comment by milessabin** [comment]
Looking again, I think this is just fine. The LICENSE file is a pristine copy of the license document and appears in exactly the same unmodified form in all the canonical Apache projects I've just checked against. The key thing is that the boilerplate text in the appendix be filled out and added to all the relevant source files, and that's always been the case.

Thanks for taking the time to check up on this ... it's good to periodically check that licensing issues are straight.
