### ISSUE TITLE
Release for 2.12.0-M3?

### ISSUE THREAD

**Issue by SethTisue** [milessabin/shapeless#484]
The Scala team would be interested in hearing whether you run into any trouble.

**Comment by milessabin** [comment]
I bumped the cross build and travis snapshot build matrix to 2.12.0-M3 in b8f7f35fc43b6c8fdb28c0bdcff2ed5ea7379fa9 and I've just published 2.2.5 for 2.12.0-M3.

For JVM only though, there doesn't seem to be a Scala.js build for 2.12.0-M3 yet.

**Comment by milessabin** [comment]
We now have parity for Scala.js ... the Travis cross builds are good and I've published 2.2.5 for 2.12.0-M3 and Scala.js as well.

**Comment by SethTisue** [comment]
awesome, thanks Miles!
