### ISSUE TITLE
`everywhere' and the presentation compiler

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#487]
I can easily put together a small testcase for this: basically the presentation compiler doesn't like the `everywhere` feature. I quite like `everywhere` and I'd like it to work in the presentation compiler. Or, I should say, I'd like it not to break the presentation compiler.
1. is it even worth filing a report with upstream?
2. any ideas for a hack? I'd rather get a false negative than a false positive

**Comment by milessabin** [comment]
Are you able to put together a headless presentation compiler test that could live alongside the other shapeless tests?

**Comment by fommil** [comment]
That could be tricky. Possibly. Its a lot easier in the ENSIME codebase but the relevant parts could be ported.

**Comment by milessabin** [comment]
I think that if this only manifest itself in the presentation compiler and that the only straightforward way to reproduce it is in ENSIME then we're more likely to make progress on it if it's an issue there.

We do have one workaround for the PC [here](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/lazy.scala#L186) contributed by @dragos ... it might be an idea to ping him to see how he tracked that down as the point the issue manifested itself.

**Comment by JanBessai** [comment]
Is [runtime compilation](http://www.scala-lang.org/api/2.11.8/scala-compiler/index.html#scala.tools.reflect.ToolBox) also affected? If so, it might help with writing down a good test case.
