### ISSUE TITLE
LabelledTypeClassCompanion-based serializer fails to compile due to file naming

### ISSUE THREAD

**Issue by divijan** [milessabin/shapeless#495]
I'm using LabelledTypeClassCompanion for serialization, project is built with SBT 0.13.9. 
The sealed trait that is being serialized resides in one file and actual JsonWriters are constructed in another one. If a name of the writer file lexicographically precedes the name of the file where the trait is defined, I get a compilation error. The project to illustrate this issue can be found [here](https://github.com/Optrak/shapeless22-codec-bug).

**Comment by milessabin** [comment]
Yes, I'm afraid this is another symptom of [SI-7755](https://issues.scala-lang.org/browse/SI-7755): it's a compiler bug ... please help to lobby for it being fixed, but I'm afraid there's nothing that I can do about it here.

Nb. this affects _all_ attempts to use macros, directly or indirectly, to automate serialization of sealed families, not just shapeless based ones.
