### ISSUE TITLE
Explicit type for a record loses Witness.Aux

### ISSUE THREAD

**Issue by jonifreeman** [milessabin/shapeless#51]
See: https://gist.github.com/jonifreeman/6533463

Switching to   

```
type FieldType[K, V] = (K, V)
```

fixes the problem since Witness.Aux is no longer needed.

See: https://gist.github.com/jonifreeman/6570276

**Comment by eugengarkusha** [comment]
it would be great  if record type literals could be written in multiple lines :
```
 type Error = Record.`
                       "k1" -> String,
                       "k2" -> Long
                    `.T
```
Is it generally possible?
