### ISSUE TITLE
The doc on Coproduct Unifier is wrong

### ISSUE THREAD

**Issue by notxcain** [milessabin/shapeless#519]
[Here](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/syntax/coproduct.scala#L182) the doc says that `Unifier` returns `Coproduct` made of `LUB`. In fact it returns the `LUB` itself.

**Comment by milessabin** [comment]
Good catch ... a PR with corrected documentation would be great :-)

**Comment by notxcain** [comment]
Thanks @vpavkin. I forgot about this one :(
