### ISSUE TITLE
Review use of Symbol#companionXxx

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#526]
See https://github.com/scala/scala/pull/4861.

**Comment by milessabin** [comment]
@retronym your advice would be very much appreciated here ...

shapeless includes uses of `Symbol#companion` and `Type#companion` where the `.info` of the result is typically what's wanted ... are these problematic?

shapeless also uses [this](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/generic.scala#L673) version of `companionSymbolOf` cargo culted from macro paradise when constructing trees referring to companions ... is this still valid and does it address the issues you fixed in https://github.com/scala/scala/pull/4861?

**Comment by retronym** [comment]
The naive way to lookup companion's is `someClassSymbol.owner.info.decl(someSymbol.name.toTermName)`. That's what `Symbol#companionXxx` does.

However, this only works for classes enclosed in classes (including the "package class" or a package or the "module class" of an object. For classes enclosed in a method (aka a "local symbol"), the owner will be the method, but `someMethod.info` gives you the signature of the method which clearly doesn't expose anything from within the method body.

During typechecking, however, we can use `Namers.companionSymbolOf(someClass)` to to the right thing. It will walk out the chain of enclosing typer `Context`s, and get to the one representing typechecking the body of the method. That context contains the scope for the method body.

This will only work if you are looking up the companionship during typechecking of that method. That's the only spot that local symbols can be referred to anyway.

**Comment by milessabin** [comment]
Thanks. Do the same considerations apply to `Symbol#companion` and `Type#companion` and to [`patchedCompanionSymbolOf`](https://github.com/scalamacros/paradise/blob/03f96e1b7b02cfeabc2e607f7db4a9fa0895cc20/plugin/src/main/scala/org/scalamacros/paradise/typechecker/Namers.scala#L576) in macro paradise?

**Comment by retronym** [comment]
Looks like they try to look up the companion in the scopes of enclosing typer contexts, as is done by `Namers#companionSymbolOf`.

I'd suggest writing some tests to convince yourself its working, though.

**Comment by milessabin** [comment]
We have a ton of tests of various forms of nesting because bugs there were seen in the wild quite regularly. The `patchedCompanionSymbolOf` implementation was borrowed from macro paradise to deal with them, I think at your suggestion?

**Comment by retronym** [comment]
![image](https://cloud.githubusercontent.com/assets/65551/12613855/1655be36-c548-11e5-88b7-749b9bad2623.png)

:smile:

**Comment by alexarchambault** [comment]
@milessabin I added `patchedCompanionSymbolOf`, for `Default` to work for classes enclosed in a method. It's tested [here](https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/default.scala#L142). If @retronym suggests a better way to do that, he's highly probably right :-)

**Comment by retronym** [comment]
Sounds like you've got it covered. You'd need to downcast to call the version in `Namers`, but maybe that's better than copy/paste.

**Comment by milessabin** [comment]
@alexarchambault ahh ... my mistake :-)

I did try that using `companionSymbolOf` from `Namers` as a substitute for `patchedCompanionSymbolOf` but that resulted in a lot of failing tests ... clearly the two aren't completely equivalent, at least not in this context.

**Comment by milessabin** [comment]
I think I'm going to declare victory on this one ... if anyone thinks differently, please reopen :-)
