### ISSUE TITLE
Review remaining 2.10.x vs. 2.11.x differences

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#529]
See

+ https://github.com/milessabin/shapeless/pull/515/files#diff-c8d2b03958e8b575ca9bdc3b92988078
+ https://github.com/milessabin/shapeless/pull/515/files#diff-21cd9467b2b35a579fc7910defb1d163
+ https://github.com/milessabin/shapeless/pull/515/files#diff-0b820408389801540a65e3cebeee6132
+ https://github.com/milessabin/shapeless/pull/515/files#diff-9ce08e6a1028cc0e45f4236f22695e8e
+ https://github.com/milessabin/shapeless/pull/515/files#diff-1f8360485a9b0a64e05357b16e34ba99

And everything found via https://github.com/milessabin/shapeless/search?l=scala&q=BACKPORT&utf8=%E2%9C%93

**Comment by dwijnand** [comment]
:+1:

and https://github.com/milessabin/shapeless/pull/515/files#diff-dcbf094c9fae87bd50d7a16e2b088beb

**Comment by milessabin** [comment]
Fixed via b75e1a3576fe34b264839750efc477af58f7ea22, 277b79441335f7a8486056680d9abdeb2c2ae938, f78cf4601e7bcdfc5dbecf900fa05a8ae3990294, 9d59210cc1fb9ce2ebb78dcc026a44d9b11dd6c4, 402f3f9ac85140f78c282f89cb670e5a54f6e7dd and 0021e6067301eb6ad1714122dddc7c666fbef26d.

**Comment by dwijnand** [comment]
Excellent!
