### ISSUE TITLE
Cleanup references to dead branches in .travis.yml

### ISSUE THREAD

**Issue by dwijnand** [milessabin/shapeless#530]
Once dead, cleanup references to dead branches in .travis.yml, such as "scala-2.10.x"

https://github.com/milessabin/shapeless/blob/23ace5c1d99a3fda0102755f2c4487976f5473f1/.travis.yml#L18

**Comment by milessabin** [comment]
Fixed in 2e1a48ef5826e9df3b0aff66ea0d84341450a4a0.
