### ISSUE TITLE
flatten.scala behaves unexpectedly on certain arities of nested tuples

### ISSUE THREAD

**Issue by jrwiebe** [milessabin/shapeless#545]
I noticed while doing some testing that the flatten example sometimes fails, depending on the size of the nested tuples it is passed. This is easier to explain with a few examples:

```
scala> :paste
// Entering paste mode (ctrl-D to finish)

object FlattenExample {
  import shapeless._
  import ops.tuple.FlatMapper
  import syntax.std.tuple._
  import test._
  
  trait LowPriorityFlatten extends Poly1 {
    implicit def default[T] = at[T](Tuple1(_))
  }
  object flatten extends LowPriorityFlatten {
    implicit def caseTuple[P <: Product](implicit fm: FlatMapper[P, flatten.type]) =
      at[P](_.flatMap(flatten))
  }
}

// Exiting paste mode, now interpreting.

defined object FlattenExample

scala> FlattenExample.flatten((1,2,(3,4,5,(6,7),8)))
res0: (Int, Int, (Int, Int, Int, (Int, Int), Int)) = (1,2,(3,4,5,(6,7),8))
```
As you can see, the tuple wasn't flattened. However, if I remove the 5:
```
scala> FlattenExample.flatten((1,2,(3,4,(6,7),8)))
res1: (Int, Int, Int, Int, Int, Int, Int) = (1,2,3,4,6,7,8)
```
I can't figure out why some tuples aren't being matched while (most) others are.

This was tested with the latest shapeless (2.3.0-SNAPSHOT) and Scala 2.11.7, but it holds for older releases too.

**Comment by milessabin** [comment]
Good catch, thanks :-)

The problem you're seeing is that resolving the `FlatMapper` instance for the first of the two tuple types involves a recursion which revisits the same tuple type during the implicit resolution process which trips Scala's divergence checker. This is masked by the fact that there is a fallback default case available which just applies the identity. The second of the two tuple types has a slightly different structure which means that the divergence checker isn't similarly tripped.

This example was written before I fully understood the subtleties here. The change I've just made which fixes it by wrapping the `FlatMapper` instance in `Lazy` is the way it would have been written if I'd known then what I know now. The rule of thumb is that if you are resolving recursive implicits which are indexed by types which aren't guaranteed to shrink on each step (but which are guaranteed to shrink eventually) then you should wrap the topmost or recursive occurrences with `Lazy`. You can see this pattern in the `DeepHLister` example and all of the type class derivation examples.
