### ISSUE TITLE
Lazy / Strict sometimes not working in 2.10

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#547]
Reproduce with
```bash
$ git clone https://github.com/alexarchambault/case-app.git -b topic/shapeless-2.3.0 # commit 4ba9d063
$ cd case-app
$ sbt ++2.10.6 coreJVM/console
```

Then
```scala
> import caseapp._
> case class Options(foo: Boolean)
> Parser[Options]
res0: caseapp.core.Parser[Options]{type D = shapeless.::[Option[Boolean],shapeless.HNil]} = caseapp.core.Parser$$anon$2@2d258973
> CaseApp.parse[Options](Seq("--foo"))
<console>:13: error: could not find implicit value for parameter parser: shapeless.Strict[caseapp.Parser[Options]]
              CaseApp.parse[Options](Seq("--foo"))
                                    ^
```
The problem is that looking for a `Strict[Parser[Options]]` in the last line fails, whereas looking for a `Parser[Options]` directly succeeds (line just before the last).

Things were fine (both look ups succeeding) with shapeless 2.2, both in 2.10 and 2.11, and are still fine with shapeless 2.3.0-RC1 in 2.11.

A bit of debug showed that the first Strict derivation was indeed considered a root one (that is, it was setting the `dcRef` field in `LazyMacros`), but the one it itself immediately triggers, which should not be a root one, actually is too (and sets a `dcRef` field too). What happens here is that two `LazyMacros` singletons are loaded by two different class loaders (both of type `scala.tools.nsc.util.ScalaClassLoader$URLClassLoader`).

Now, I have not the slightest idea what compels scalac into loading shapeless with two distinct class loaders during the compilation, nor why both are used at the same time like here.

**Comment by milessabin** [comment]
See #367.
