### ISSUE TITLE
tag[Tag](value) doesnt work with explicitly declared target type

### ISSUE THREAD

**Issue by benhutchison** [milessabin/shapeless#557]
```
@ import shapeless.tag._
import shapeless.tag._
@ trait NameTag; type Name = String @@ NameTag
defined trait NameTag
defined type Name
@ val name1 = tag[NameTag]("ben")
name1: String @@ NameTag = "ben"
@ val name2: Name = tag[NameTag]("ben")
Compilation Failed
Main.scala:321: type mismatch;
 found   : String("ben")
 required: shapeless.tag.Tagged[cmd4.NameTag] with String
val name2: Name = tag[NameTag]("ben")
                               ^
```

It seems to be a side-effect of type inference from the target (ie the `val`) flowing back to the expression assigned to it. Scalac is simplistically setting the type T in Tagger#apply to be the "target" type of the val, eg Name. gitter [context](https://gitter.im/milessabin/shapeless?at=56d82cbd048f9e65291bb89d).

Reordering the tag operation, to collect the value first and the tag type second, seems a nice solution:

```
import shapeless.tag
import shapeless.tag.@@
object tag2 {
    def apply[T](t: T) = new TaggedValue[T](t)
    class TaggedValue[T](t: T) {
      def @@[U]: T @@ U = tag[U].apply[T](t)
    }
  }

def name: Name = tag2("ben").@@[NameTag]
```

I like the symmetry of using `@@` here myself. 

Ive trialed this pattern in my own codebase with success, and wonder if it would be welcomed pushed up to shapeless proper? I'd propose offering the new form, retaining but deprecating the existing `tag` operation.

**Comment by fthomas** [comment]
JFYI this is also known as https://issues.scala-lang.org/browse/SI-8740

**Comment by milessabin** [comment]
Thanks @fthomas ... looks like there's nothing we can do about it here. I've pinged Jason to see if there's any chance of his fix going in for 2.12.0-M4. I'll leave this open to track the status of the upstream ticket.

**Comment by kwark** [comment]
FYI: [SI-8740](https://issues.scala-lang.org/browse/SI-8740) is now https://github.com/scala/bug/issues/8740

**Comment by joroKr21** [comment]
That's an issue with type inference in the compiler and at this point we can't change the encoding of `@@` because it would change erasure and cause binary incompatibility.
