### ISSUE TITLE
Idea: Forall type-level predicate for product/coproduct

### ISSUE THREAD

**Issue by djspiewak** [milessabin/shapeless#558]
Here's the thought:

```scala
// a proof of some property about type A
trait Predicate[A]

object Predicate {
  // ...
}

def foo[L <: HList](implicit proof: Forall[L, Predicate]) = ???
```

Pick your favorite property instead of `Predicate`.  The idea is simply that the `Forall` evidence would require that an instance of `Predicate` is available for every type in the list.  One would imagine that the implementation would be something like this:

```scala
trait Forall[L <: HList, Prop[_]] {
  type Out <: HList
  def evidence: Out
}

object Forall {
  type Aux[L <: HList, Prop[_], Out0 <: HList] = Forall[L, Prop] { type Out = Out0 }

  implicit def base[Prop[_]]: Forall.Aux[HNil, Prop, HNil] = new Forall[HNil, Prop] {
    type Out = HNil
    def evidence = HNil
  }

  implicit def corecurse[H, T <: HList, Prop[_]](implicit ev: Prop[H], ind: Forall[T, Prop]): Forall.Aux[H :: T, Prop, Prop[H] :: ind.Out] = new Forall[H :: T, Prop] {
    type Out = Prop[H] :: ind.Out
    def evidence = ev :: ind.evidence
  }
}
```

Aside from the obvious issues related to SI-2712, this seems like it might be a useful tool to have (if it doesn't already exist somewhere that I couldn't find).  I guess you *could* do something like this with `Mapper`, but that's specific to `Poly` rather than an "arbitrary implicit in scope".

The motivation here is to be able to more easily "lift" userspace proofs on single types to operate over product/coproduct.

**Comment by alexarchambault** [comment]
@djspiewak https://github.com/milessabin/shapeless/pull/503 added something similar (if not exactly that, under another name).

**Comment by djspiewak** [comment]
@alexarchambault Nice!  It is indeed exactly this.
