### ISSUE TITLE
Typeable instance derived for generic case classes can be unsafe

### ISSUE THREAD

**Issue by durban** [milessabin/shapeless#574]
The automatically derived/generated `shapeless.Typeable` instance for generic case classes can be unsafe in some cases. For example:
```
final case class C[A](s: String)(x: A) {
  val y: A = x
}
```
The `Typeable[C[Int]]` instance can cast a `C[Double]` to a `C[Int]`, which then blows up with a `ClassCastException`, due to a `Double` not being an `Int` (full code: https://github.com/durban/akka-typed-examples/blob/7f7378979cbdb70615690a25207c70cf57f332fb/src/main/scala/com/example/shless/TypeableExample.scala). More variations: https://github.com/durban/akka-typed-examples/blob/7f7378979cbdb70615690a25207c70cf57f332fb/src/main/scala/com/example/shless/TypeableExample2.scala and https://github.com/durban/akka-typed-examples/blob/7f7378979cbdb70615690a25207c70cf57f332fb/src/main/scala/com/example/shless/TypeableExample3.scala.

I guess the reason could be that the macro generating the instance misses some definitions involving `A` (it only seems to take into account the case class accessors).

**Comment by milessabin** [comment]
Ouch! Nice catch ... thanks. Would you like to take a swing at fixing it?

**Comment by durban** [comment]
Ok, I'll try to take a look during the weekend (although I can't promise anything).

**Comment by milessabin** [comment]
Awesome! Thank you :-)
