### ISSUE TITLE
Typeable instance derived for nested classes can be unsafe

### ISSUE THREAD

**Issue by durban** [milessabin/shapeless#579]
The automatically generated `Typeable` instance for nested classes can be unsafe, if they refer to a type member of the enclosing class. The macro generating the instance correctly rejects uncheckable generic classes, but allows these; unfortunately these classes are in effect also "generic". The problem affects both regular classes and case classes (examples which cause a `ClassCastException`: https://github.com/durban/akka-typed-examples/blob/ca73c1dc1e1ca729ddc355a175ca95ca4d448b75/src/main/scala/com/example/shless/TypeableExample4.scala and https://github.com/durban/akka-typed-examples/blob/ca73c1dc1e1ca729ddc355a175ca95ca4d448b75/src/main/scala/com/example/shless/TypeableExample5.scala).

I discovered this when I worked on #574. I tried to fix this too, but haven't been able to find a way to distinguish cases when the nested class refers to the type member from the ones when is doesn't. (If it doesn't refer to the type member, I _think_ its not unsafe.)

**Comment by milessabin** [comment]
Good spot, and thanks for the analysis.
