### ISSUE TITLE
Issues with sized

### ISSUE THREAD

**Issue by JohnReedLOL** [milessabin/shapeless#597]
In order to used sized, I need to be able to define a method that will append one Sized[IndexedSeq of length A to another Sized[IndexedSeq of length B and return a Sized[IndexedSeq of length C.

```
    val toAppend: Sized[IndexedSeq[String], shapeless.nat._1] =
      Sized("666")

    def appendT[MyLength, ToAppLength, ToReturnLength](me: Sized[IndexedSeq[String], MyLength])
    (toAppend: Sized[IndexedSeq[String], ToAppLength]):
    Sized[IndexedSeq[String], ToReturnLength]
    = {
      me ++ toAppend
    }

    // Extend the bookRows to match ...
    val extendedRows: List[Sized[IndexedSeq[String], shapeless.nat._3]]
      = bookRows map (appendT(_)(toAppend))

```

**Comment by JohnReedLOL** [comment]
More specifically I need to be able to pass in two sized 2D grids and append them to form a third sized 2D grid.

**Comment by milessabin** [comment]
Thanks for using shapeless. This isn't really the right place to ask questions about usage. I recommend asking on StackOverflow (there's a shapeless tag, and questions are usually answered very quickly) or on the [shapeless gitter channel](https://gitter.im/milessabin/shapeless).
