### ISSUE TITLE
Sized.equals fails in 2.3.1

### ISSUE THREAD

**Issue by mpilquist** [milessabin/shapeless#600]
```
scala> Sized(1, 2, 3) == Sized(1, 2, 3)
res4: Boolean = false
```

This returned true in 2.2.5 but returns false in 2.3.1.

**Comment by milessabin** [comment]
@alissapajer were you looking at this?

**Comment by mpilquist** [comment]
Looks like this was introduced by removing the `extends AnyVal`. We can override equals/hashCode for now since we can't extend `AnyVal` in the 2.10 build.

**Comment by milessabin** [comment]
Yup, that was what we discussed a couple of weeks back.

**Comment by milessabin** [comment]
The fix for this will break binary compatibility so we'll have to punt this to 2.4.0.

**Comment by aborg0** [comment]
Maybe `Ordering` `Eq` typeclass instances can also be added if those are available for the generic `Repr` parameter.

**Comment by milessabin** [comment]
@aborg0 could you explain how your comment relates to this ticket?

**Comment by aborg0** [comment]
Probably it is related only in my head. :)
You are right, it is not closely related. I was also hit by this issue and was thinking about reporting it with also requesting `Ordering` and `Eq` type class instances when found this.
Sorry for not creating a new issue/commenting here. (Adding these implicit methods can be done in user code, so no need for them in shapeless as opposed to the `equals`/`hashCode` implementations/or extending `AnyVal`.)
