### ISSUE TITLE
HList() exposes HNil.type 

### ISSUE THREAD

**Issue by doolse** [milessabin/shapeless#609]
As most HList ops don't currently handle HNil.type properly, it's probably not a good idea to have any shapeless API expose it. In fact if you make HNil private, you can find any instances of this happening in the library.

**Comment by milessabin** [comment]
How would you rewrite,
```
val l = 23 :: "foo" :: true :: HNil
```
If the `HNil` object was private?

**Comment by yilinwei** [comment]
Would a better solution not be to change `::` on the `HNil` from `def ::[H](h : H) = shapeless.::(h, this)` to writing the return type explicitly as the trait rather than the singleton type?

**Comment by milessabin** [comment]
@yilinwei Adding the explicit result type `H :: HNil` to `::` on trait `HNil` is a good idea. I think that's orthogonal to this issue though.

**Comment by doolse** [comment]
@milessabin Yeah before I added the "private" to HNil i suspected that you wouldn't be able to do:

`val l = 23 :: "foo" :: true :: HNil`

But when I tried that in a library i'm writing against shapeless it still worked.. I don't pretend to know why though.. 
I guess it's probably not worth merging the PR anyway if it breaks binary compatibility, it's generally something that can be worked around but it's something that may trip up people new to the library.

Also I believe HNil's `::` already infers HNil instead of HNil.type
