### ISSUE TITLE
slow performance for sealed traits with large number of case objects

### ISSUE THREAD

**Issue by cvogt** [milessabin/shapeless#620]
As discussed here: https://gitter.im/milessabin/shapeless?at=578d59c20720fd587a91e5a4

Example here:
https://github.com/milessabin/shapeless/blob/master/examples/src/main/scala/shapeless/examples/sexp.scala#L121

**Comment by cvogt** [comment]
apparently miles is working on a compiler level fix

**Comment by cvogt** [comment]
seems related to https://github.com/milessabin/shapeless/issues/381

**Comment by milessabin** [comment]
Yup, this is a duplicate of #381.
