### ISSUE TITLE
could not find implicit value for parameter gen: shapeless.Generic[(Int, collection.immutable.Nil.type)]

### ISSUE THREAD

**Issue by Atry** [milessabin/shapeless#626]
``` sbt
scalaVersion := "2.10.6"

libraryDependencies ++= Seq(
  "com.chuusai" %% "shapeless" % "2.3.1",
  compilerPlugin("org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full)
)
```

``` scala
object Niltype {
  import shapeless._

  def g0 = Generic[(Int, Nil.type)] // OK

  def g1 = Generic[(Int, scala.collection.immutable.Nil.type)] // Error
}
```

```
$ sbt compile
[info] Loading global plugins from /Users/twer/.sbt/0.13/plugins
[info] Set current project to niltype (in build file:/private/tmp/Niltype/)
[info] Compiling 1 Scala source to /private/tmp/Niltype/target/scala-2.10/classes...
[error] /private/tmp/Niltype/Niltype.scala:6: could not find implicit value for parameter gen: shapeless.Generic[(Int, collection.immutable.Nil.type)]
[error]   def g1 = Generic[(Int, scala.collection.immutable.Nil.type)] // Error
[error]                   ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed Aug 5, 2016 6:07:42 PM
```

**Comment by everson** [comment]
I confirmed this happens on scala 2.10.6, I also tried on scala 2.12 and 2.11, but on those this issue didn't manifest.

I was giving a shot to see if this was something I could fix. I didn't have much luck. Here are expanded examples:

```scala
package root

object Niltype {
  import shapeless._

  import scala.collection.immutable

  def g0 = Generic[(Int, Nil.type)] // OK
  def g1 = Generic[(Int, immutable.Nil.type)] // Error
  def g2 = Generic[(Int, scala.collection.immutable.Nil.type)] // Error
  
  def lg0 = LabelledGeneric[(Int, Nil.type)] // OK
  def lg1 = LabelledGeneric[(Int, immutable.Nil.type)] // Error

  def t0 = TypeCase[Nil.type] // OK
  def t1 = TypeCase[immutable.Nil.type] // OK

}
```

I created a minimal examples as follow: in either compilation, only one of the `g0` lines where in the file:

```scala
package root

object Niltype {
  import shapeless._

  def g0 = Generic[(Int, Nil.type)] // OK
  def g0 = Generic[(Int, scala.collection.immutable.Nil.type)] // Error
  
}
```

To get an overview of the AST, I have compiled with `-Ymacro-debug-verbose`. The thing that caught my attention was the presence of `SingletonTypeTree` in the output of the file that fails to compile.

For reference, here it is both outputs: https://gist.github.com/everson/096d46ddacd47aca30291a23b2fa40b1

If someone can provide some guidance, I can try to look further. I hope at least what I provided is useful as a start point.

**Comment by milessabin** [comment]
@everson many thanks for the analysis. Are you able to construct a tree similar to the 2.11/12 one by hand in 2.10.6 and see if that compiles?

**Comment by alexflav23** [comment]
Hi @milessabin,

I can confirm this fails in 2.10.6 in other cases as well, using `@macrocompat.bundle` and auto-tupling, where the auto-tupled type is passed as source argument to `Generic`.

I expect the below to provide an `HList` of auto-tupled arguments.

```scala
case class Opera(value: String)

def test[V1, HL <: HList](v1: V1)(implicit ev: Generic.Aux[V1, HL])

// could not find implicit value for parameter gen: shapeless.Generic.Aux[Opera,HL]

```

This works in Scala 2.11 and 2.12 as expected, but it's not working in 2.10.6.

Regards.

**Comment by alexflav23** [comment]
Hi,

In my case this was an oversight on my part. The `macro-paradise` plugin was missing from the submodules where the implicit macro was being summoned from, which was causing trouble in Scala 2.10. In the module where the macro was defined, `Generic` was being successfully generated for all callsites under `test`, but the other modules depending on this one didn't have `macro-paradise`, hence the failure.

Unfortunately unlike other users in the eco-system, we do still get thousands of monthly downloads for 2.10 artefacts which makes it impossible to drop support right now.

Apologies for the false alarm.

Regards.

**Comment by joroKr21** [comment]
2.10 is no longer supported: #967
