### ISSUE TITLE
possible bug in implicit `Witness.apply[T]` ?

### ISSUE THREAD

**Issue by shengc** [milessabin/shapeless#643]
So the compiler complained an implicit I wrote cannot be inferred in the scope. I turned on the implicit logging option of scalac, and the log showed a `Witness` implicit for a symbol tag was missing. But the symbol tag directly comes from a record `HList`, how is it possible ? 

I cloned the `shapeless` project, and tried to find out why. Turns out in `singletons.scala`, the pattern match in the body of `extractSingletonValue` for the `Witness` type failed, and specifically it failed at `SingletonSymbolType(c)`. I got into the body of the `unapply` method of that object, and did something like this,

```scala
    def unapply(t: Type): Option[String] = {
      t match {
        case RefinedType(List(SymTpe, TypeRef(_, TaggedSym, List(ConstantType(Constant(s: String))))), _) =>
          Some(s)
        case RefinedType(mystery, _) =>
           Console.println(s"this is a mystery: $mystery")
           None
        case _ => None
      }
```

Recompiling the `shapeless` core, and including it into the classpath of my project, and after that  I saw such message printed on screen during compile,

```
    this is a mystery: List(Symbol with shapeless.tag.Tagged[String("x")])
```

So the type actually did not get expanded at all! I figured I need to recurse one more time to extract the properly value, and this is what I did:

```scala
    def unapply(t: Type): Option[String] = {
      t match {
        case RefinedType(List(SymTpe, TypeRef(_, TaggedSym, List(ConstantType(Constant(s: String))))), _) =>
          Some(s)
        case RefinedType(List(candidate), _) =>
          candidate.dealias match {
            case RefinedType(List(SymTpe, TypeRef(_, TaggedSym, List(ConstantType(Constant(s: String))))), _) =>
              Some(s)
            case _ =>
              None
          }
        case _ => None
      }
```

Do you think this is an actual bug, or something else is wrong ?

**Comment by milessabin** [comment]
Could you post a minimal, standalone, reproduction of the code you were trying to compile which caused the error?

**Comment by shengc** [comment]
@milessabin I roughly put something together to show the issue. Note that for the last three LOC, the first two compiles, the last one does not. The implicit logging suggested this message,

    hasMatchingSymbol reported error: could not find implicit value for parameter wk: shapeless.Witness.Aux[Symbol with shapeless.tag.Tagged[String("y")]]

```scala
  import shapeless._
  import shapeless.ops.record._

  trait Foo[A] {
    type Out

    def to(a: A): Out
  }

  object Foo {
    type Aux[A, Out0] = Foo[A] { type Out = Out0 }
    def apply[A, Out](implicit foo: Aux[A, Out]) = foo

    implicit def from[A, Out0](implicit gen: LabelledGeneric.Aux[A, Out0]) =
      new Foo[A] {
        type Out = Out0
        def to(a: A) = gen.to(a)
      }
  }

  class Bar[A, HL <: HList](gen: Foo.Aux[A, HL]) {
    def modify[K, V, U, Out0 <: HList](k: K, f: V => U)(implicit modifier: Modifier.Aux[HL, K, V, U, Out0]) = new Bar[A, Out0](new Foo[A] {
      type Out = Out0
      def to(a: A): Out = modifier.apply(gen.to(a), f)
    })

    def keys[Out <: HList](implicit keys: Keys.Aux[HL, Out]): Out = keys.apply()
  }

  final case class FooBar(x: String, y: Int)

  import shapeless.syntax.singleton._
  new Bar(Foo.from( LabelledGeneric[FooBar] )).modify('y.narrow, (_: Int) * 2)  // compiles
  new Bar(Foo.from( LabelledGeneric[FooBar] )).keys // compiles
  new Bar(Foo.from( LabelledGeneric[FooBar] )).modify('y.narrow, (_: Int) * 2).keys // does not compile
```

**Comment by milessabin** [comment]
Thanks for the report and the diagnosis ... spot on :-)
