### ISSUE TITLE
Convenience methods for Either[A, B] <=> A :+: B :+: CNil

### ISSUE THREAD

**Issue by AlecZorab** [milessabin/shapeless#648]
would be nice to have the following:

``` scala
val e: Either[Int, String]  = ???
val c = e.toCoproduct
typed[Int :+: String :+: CNil](c)
val e1 = c.toEither
typed[Either[Int, String]](e1)
```

names obviously subject to debate.

**Comment by AlecZorab** [comment]
If someone wants to assign this to me I'll probably remember to do it

**Comment by milessabin** [comment]
I think I'd like to see this generalized to nested `Eithers`, but yes, this looks useful.
