### ISSUE TITLE
rename CONTRIBUTORS to NOTICE

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#649]
I know contributors may be a better name, but NOTICE brings legal obligations to distributors http://www.apache.org/dev/licensing-howto.html#assembling-license-and-notice

**Comment by fommil** [comment]
(note that these instructions are for an actual Apache Foundation project, soo the ALv2 for what it expects of the NOTICE)

**Comment by milessabin** [comment]
I'm happy to be persuaded, but I'm not convinced yet. In Redistribution, 4.d it says, 

> The contents of the NOTICE file are for informational purposes only and do not modify the License. You
> may add Your own attribution notices within Derivative Works that You distribute, alongside or as an
> addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot 
> be construed as modifying the License

I would say that the CONTRIBUTORS file qualifies as an attribution notice provided alongside or as an addendum. Given that CONTRIBUTORS is so common I'd need to see a pretty strong reason for renaming it.
