### ISSUE TITLE
Release shapeless for 2.12

### ISSUE THREAD

**Issue by etorreborre** [milessabin/shapeless#651]
Hi @milessabin,

Can you please release shapeless for Scala 2.12? Thanks.

**Comment by milessabin** [comment]
I will as soon as macro-paradise is available.

**Comment by etorreborre** [comment]
The cascading effect of a new Scala release... Thanks :-)

**Comment by etorreborre** [comment]
Scalacheck is [out](https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_2.12/) for Scala 2.12!

**Comment by theon** [comment]
Looks like macro-paradise has been pushed for 2.12: https://github.com/scalamacros/paradise/issues/87

**Comment by milessabin** [comment]
shapeless 2.3.2 for Scala 2.12.0 on Central now.
