### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by norcalli** [milessabin/shapeless#653]

**Comment by tkroman** [comment]
This is like stage 2 on a standard "5 Stages of shapeless" scale, right after "Wow it's so cool gonna use it everywhere".

On a serious note: @norcali, there'a a feature overview with a lot of examples: https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0

Also, there's a book: https://github.com/underscoreio/shapeless-guide

Also, you can google some slides. Just try "shapeless tutorial".

Also, you may ask on stackoverflow and Gitter channel, if none of the above works for you.

**Comment by milessabin** [comment]
@norcalli that kind of language isn't acceptable here. Any repetition will get you blocked immediately.

The [shapeless guide](https://github.com/underscoreio/shapeless-guide) pointed to by @tkroman is excellent.

**Comment by LiamGoodacre** [comment]
Would it make sense to link to the book from this project's README.md?  Given that it is recommended by the both of you.

**Comment by milessabin** [comment]
Yes, it would.

**Comment by norcalli** [comment]
Hey thanks guys. Adding a link to the shapeless guide in the README is basically exactly what I wanted. Sorry for the outburst, but I inherited some shapeless stuff, and my work project was being delayed by not having any documentation, so I had to stay late, leading to me being understandably frustrated.

**Comment by milessabin** [comment]
You should address that sort of frustration to employers who give you unreasonable deadlines, not people who give you free software (in both senses of "free").
