### ISSUE TITLE
Drop support for Scala 2.10.x!

### ISSUE THREAD

**Issue by milessabin** [milessabin/shapeless#655]
This issue is to gauge the level of interest in ongoing support for Scala 2.10.x.

As well as adding a :+1: or a :-1: please leave a comment with your reasons for and against.

**Comment by vil1** [comment]
Being a professional user of scala for more than three years, I've not seen any project using scala 2.10.x for quite a long time. So from my (obviously biased) point of view, support of 2.10.x is an unworthy effort.

**Comment by joescii** [comment]
I have not used shapeless in an sbt plugin myself, but I could see where some folks would want 2.10 until sbt 0.13.x dies off.

**Comment by cvogt** [comment]
@joescii that could be achieved with bug-fixes only legacy releases for 2.10, which would allow master to be 2.11 only.

**Comment by joescii** [comment]
@cvogt sounds good to me. Like I mentioned, I don't personally need it. Just want to make sure this consideration is on the radar.

**Comment by fommil** [comment]
We need shapeless in ensime to support 2.10. although as long as there is a cross build available, we're OK not upgrading shapeless to the latest and greatest.

**Comment by Milyardo** [comment]
I'd imagine the only real concern for dropping 2.10.x support would be for sbt plugins as well.

**Comment by tpolecat** [comment]
I would like to support doobie for 2.10 at least through mid-2017 and possibly until the end of the year, so shapeless support at least through that timeframe would be helpful. But in the worst case I can slice off the API that depends on shapeless and offer it only for 2.11+ so it's certainly not a disaster if you decide to end support earlier.

**Comment by gruggiero** [comment]
Our use case is a project with the Cloudera platform for Hadoop and Spark.
Alas Spark with this platform is still with Scala 2.10 only, so we (and anybody else who uses this platform) cannot upgrade to 2.11 until Cloudera does

**Comment by shawjef3** [comment]
@gruggiero Is your team OK using the current shapeless release for 2.10, or do you expect new features that will be in 2.11 and 2.12 releases?

**Comment by gruggiero** [comment]
Actually we use the 2.2.5 as we import it as a transitive dependency of another library, which is an old version for 2.10 compatibility.
This means that even an upgrade to a new Shapeless 2.10 version is not possible in this project.
The choice is between being OK with 2.2.5 or nothing :)

**Comment by fanf** [comment]
We succesfully ended all support of scala 2.10 this spring, so we only have 2.11 now in Rudder. 
(2.12 will be in a far far future, because we have to await that major linux distrib use java 8 by default - and no they don't, I just... Humpf. Yeah. So great to build on-premise oss infra tool).

**Comment by joroKr21** [comment]
What's the plan here? sbt is not stuck on 2.10 anymore and 2.13 will be coming soon.

**Comment by milessabin** [comment]
At this point I'm comfortable to make continued 2.10.x support "best effort" only.

**Comment by joroKr21** [comment]
Dropped Scala 2.10 in #967
