### ISSUE TITLE
Lenses and apparent leaks in JDB (java debugger)

### ISSUE THREAD

**Issue by bbarker** [milessabin/shapeless#656]
I should start by saying I haven't verified a definite leak. What I have done is verified a program that takes ~1GB normally will take over 100GB when running in debug mode, and still generate OOMs (as well as being horrendously slow to debug, even if it weren't impossible due to the OOMs).

This is my first time using Lenses, and I truly apologize for not writing a minimal test case yet using Lenses (I'm not really sure where to start, though I'd probably try something tail recursive to mimic what I've done). That said, my code is not that large, though it is somewhat complex and mid-development (read: probably needs better comments). It is basically trying to parse and XML XSD schema and emit possible XPaths (work-in-progress for complex schemas), and the reason I used Shapeless Lenses was so that I could create Maps that have scope (so named XSD entities within the same schema that have the same identifier don't trample each other). Also I used them a bit to simplify the passing of arguments in a recursive function. Very cool!

I've created two branches. The ["pre-lens" branch](https://github.com/ncrncornell/XPathEnumerator/tree/debugLowMem), which doesn't exhibit high-memory issues when run in JDB, and the [high-memory branch ](https://github.com/ncrncornell/XPathEnumerator/tree/debugBigMem)with lenses.

The test case can be run on each branch as follows:
1. Set a break point at `println("here we are!")` in `XpathXsdEnumerator`, around line 169 in the low memory case, line 230 in the high memory case.
2. Run test case `DdiCodebookSpec`
3. Force step to the line `val last = unapplyMatcher(arg, "")`, around line 112 in the low memory case, 178 in the high memory case.

By the time you run step 3 in the high memory case, you should be noticing quite the difference. For added fun if you've raised the JVM heap memory limit, try to inspect some of the maps embedded in `eArgs` at that point. 

I note the following two caveats to posting the issue here since it may not be an issue directly with shapeless lenses:
1. It could be an issue with JDB, but it might be better to have some more seasoned JDBers to comment.
2. It may be a user-error in how I'm structuring Lenses, but I don't think so, since it runs fine outside of the debugger.

**Comment by rorygraves** [comment]
This is a fun error - I can trigger the same issue in the intellij debugger.
The underlying problem is not the step itself, it is the fact that the debugger tried to do a 'toString of the variables in scope.  If you look at a dump (I used yourkit), you can see it is basically deeply nested in the middile of a ```toString``` chain.  This can be tested by chaning the ```toString``` on NodeWrap to ```override def toString = "NodeWrap()"``` - and now stepping works without issue.

**Comment by bbarker** [comment]
Wow ... interesting. In fact, I was using the IntelliJ debugger, albeit remotely, so I didn't think that it would be related, but of course IntelliJ was probably requesting these toString calls for the remote debugger. 

Moral of the story, be careful when using fancy debuggers on recursive data structures.

I feel like I should have asked this on SO now ... sorry! I'll see if I can get this mentioned more prominently in the IntelliJ docs somewhere.
