### ISSUE TITLE
Malformed literal type on generic types in record type definition

### ISSUE THREAD

**Issue by danslapman** [milessabin/shapeless#660]
How to reproduce:
```scala
type MapRec = Record.`'map -> Map[String, String]`.T
```
emits: `Malformed literal or standard type Map[String`

```scala
type MapRec = Record.`'map -> String Map String`.T
``` 
works well

**Comment by milessabin** [comment]
That's an embarrassing bug in parsing the contents of the backticks. A workaround would be,
```scala
type MapSS = Map[String, String]
type MapRec = Record.`'map -> MapSS`.T
```
Would you like to take a crack at trying to fix it?

**Comment by danslapman** [comment]
Will be glad to try, but I have very limited free time now, maybe at holidays...
