### ISSUE TITLE
Make shapeless modular?

### ISSUE THREAD

**Issue by fomkin** [milessabin/shapeless#662]
I wonder why shapeless is so monolithic? For example, `tag` can be isolated in a separate module, without dependencies.

**Comment by milessabin** [comment]
Yes, this is planned for 3.0.

**Comment by Atry** [comment]
I suggest making every library contain only one Scala source file.
I have tried this style of layout in https://github.com/ThoughtWorksInc/Binding.scala and https://github.com/ThoughtWorksInc/DeepLearning.scala

This restriction does not only minimize dependencies for users, but also leads better design.

**Comment by milessabin** [comment]
That's an interesting idea. Both of those libraries are quite small (I'm not suggesting that that's a bad thing :-) ) and I wonder how it would scale? Do you use a text editor or an IDE?

**Comment by dwijnand** [comment]
Single file libraries also nullify the incremental compiler (i.e. you might as well just call scalac). Bindings.scala for instance is 1388 lines. So I would advise against that suggestion.

**Comment by Atry** [comment]
@milessabin I use IntelliJ IDEA, which has a smooth support for multi-projects build, regardless its vulnerable parser and typer.

**Comment by Atry** [comment]
Since tuple/coproduct/hlist shares a lot of operations, is it possible to share type class definitions and ops among tuple/coproduct/hlist ?

I guess we can remove type constraint on type classes, e.g. using `L` instead of `L <: HList`.

**Comment by milessabin** [comment]
@Atry take a look at the smc branch for an idea of how things might be unified.

**Comment by joroKr21** [comment]
Shapeless 3.0 is out at https://github.com/typelevel/shapeless-3
