### ISSUE TITLE
compilation failure ("could not find implicit value ") in 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [milessabin/shapeless#663]
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1085/consoleFull:

```
[shapeless] Running "compile" in: coreJVM
[shapeless] [info] Compiling 1 Scala source to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/shapeless-8ff3674a7523591eb35fa2955c2bb6c204db66c5/core/jvm/target/scala-2.12.2-a9802c3-nightly/classes...
[shapeless] [info] Compiling 45 Scala sources to /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/shapeless-8ff3674a7523591eb35fa2955c2bb6c204db66c5/core/jvm/target/scala-2.12.2-a9802c3-nightly/test-classes...
[shapeless] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.7-RC1/project-builds/shapeless-8ff3674a7523591eb35fa2955c2bb6c204db66c5/core/src/test/scala/shapeless/coproduct.scala:170: could not find implicit value for parameter flatMap: shapeless.ops.coproduct.FlatMap[shapeless.:+:[I,shapeless.CNil],coIdentity.type]
[shapeless] [error]     val r1 = in1.flatMap(coIdentity)
[shapeless] [error]                         ^
```

I briefly tried was not able to reproduce the problem by using a `scalaVersion` of `2.12.2-a9802c3-nightly` in a local clone of the Shapeless repo. (not entirely sure I didn't mess up the attempt)

my investigations stopped there since it's unfamiliar code to me — @milessabin, any guesses what might be going on here? last green run was https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1083/consoleFull, with the same Shapeless commit (88e8c5687040ef79d669bdb49644d927a0571bbf), Scala `2.12.2-3de1c0c-nightly`

**Comment by milessabin** [comment]
Is it possible that the companion object changes that @retronym made recently have interfered with the implicit scope somehow?

**Comment by SethTisue** [comment]
@milessabin @adriaanm @retronym does anyone have even a guess of why this isn't (so far?) reproducible outside of the community build? I tried again just now with `2.12.2-827d69d-nightly` and I still don't get the failure

perhaps the problem runs through macro-compat and/or macro-paradise somehow. like we'd have to also compile macro-compat and/or macro-paradise with the same Scala version to make the problem show up outside dbuild?

**Comment by retronym** [comment]
Can we bisect to a particular commit in scala/scala that led to the problem?

**Comment by SethTisue** [comment]
I'm already working on bisecting to a particular nightly, at least. Then, if that's not enough, we can get to a particular commit, too, it'll just be a little harder (since the builds aren't already sitting on scala-release-temp)

**Comment by SethTisue** [comment]
* last good nightly: 2.12.2-3de1c0c-nightly (https://github.com/scala/scala/commit/3de1c0c56ee530f4e75533fc9e1909fe0cde31b5)
* first bad nightly: 2.12.2-7ae0aec-nightly (https://github.com/scala/scala/commit/7ae0aec7a202b22ea427d504ad3a79c0998e4b8f)

commits in between:

```
*   7ae0aec7a2 - Merge pull request #5593 from ashawley/spec-jekyll-3 (4 weeks ago) <Adriaan Moors>
|\  
| * 1f4cd50fa4 - Update spec build to Jekyll 3.3 (5 weeks ago) <Aaron S. Hawley>
*   0a3e2b62bd - Merge pull request #5531 from tabdulradi/SI-10060 (4 weeks ago) <Lukas Rytz>
|\  
| * 5370f271df - fixup! SI-10060 Fixes NumericRange.max bug on empty ranges (8 weeks ago) <Tamer Mohammed Abdul-Radi>
| * 99b971e78c - SI-10060 Fixes NumericRange.max bug on empty ranges (8 weeks ago) <Tamer AbdulRadi>
*   8b872daacb - Merge pull request #5543 from retronym/ticket/10069 (4 weeks ago) <Lukas Rytz>
|\  
| * 880aec04e8 - SI-10069 Fix code gen errors with array updates, Nothing (6 weeks ago) <Jason Zaugg>
*   2d90142eca - Merge pull request #5527 from som-snytt/fix/use-modern-replace (5 weeks ago) <Lukas Rytz>
|\  
| * f0d4e1efd9 - String.replaceAllLiterally is String.replace (9 weeks ago) <Som Snytt>
*   d34e44e994 - Merge pull request #5550 from retronym/ticket/3772 (5 weeks ago) <Lukas Rytz>
|\  
| * 9502a061fa - Refactor companion lookup methods after code review (6 weeks ago) <Jason Zaugg>
| * 37037fe706 - SI-3772 Fix detection of term-owned companions (6 weeks ago) <Jason Zaugg>
*   623f0a72ba - Merge pull request #5569 from paplorinc/rotr (5 weeks ago) <Lukas Rytz>
|\  
| * bc91223012 - Changed hashing bit rotation to use Integer.rotateRight (5 weeks ago) <Pap Lőrinc>
* 84484df5b9 - Merge pull request #5594 from retronym/topic/JEP-193 (5 weeks ago) <Lukas Rytz>
* 1ff714b837 - Compiler support for JEP-193 VarHandle polymorphic signatures (5 weeks ago) <Jason Zaugg>
```

PRs merged: scala/scala#5594, scala/scala#5569, scala/scala#5550, scala/scala#5527, scala/scala#5543, scala/scala#5531, scala/scala#5593

**Comment by milessabin** [comment]
Did you investigate my suggestion that @retronym's companion object changes might be relevant?

**Comment by SethTisue** [comment]
not yet, what's above is just where I got before bedtime. as a next step, I will try building the commits just before after 5550 were merged, publishing those versions locally, and asking dbuild what it thinks. there may be a bit of a delay while I figure out how to make dbuild use a locally published Scala; we're pursuing that question over at https://github.com/scala/community-builds/issues/456

**Comment by SethTisue** [comment]
I wanted to learn how to run the community build with locally-published Scala anyway, but it occurred to me later that it would probably be easier to just manually trigger Jenkins runs to build and publish the additional nightlies we want.

**Comment by SethTisue** [comment]
OK, I published the relevant Scala versions locally with:

```
clean
setupPublishCore
set publishArtifact in (Compile, packageDoc) in ThisBuild := false
set baseVersionSuffix in Global := "SHA-NIGHTLY"
set every isSnapshot := true
dist/mkPack
publishM2
```

and did the community build runs (after hand-editing community.dbuild to just contain shapeless and its dependencies, to save time during dependency extraction) and found that the first failing commit is scala/scala@37037fe (the first of the two commits in scala/scala#5550)

**Comment by SethTisue** [comment]
@milessabin we're not especially familiar with the Shapeless codebase. would it be possible for you to attempt to isolate this into a standalone bug report against the compiler...?

**Comment by milessabin** [comment]
I'll take a look as soon as I have a spare minute. I think that if it is related to @retronym's companion object change it should be fairly easy to come up with a minimization.

**Comment by milessabin** [comment]
Standalone reproduction in [SI-10154](https://issues.scala-lang.org/browse/SI-10154).

**Comment by SethTisue** [comment]
this must have gotten fixed at some point
