### ISSUE TITLE
Implicit not found when compile files in two packages.

### ISSUE THREAD

**Issue by agolovko1-at-tinkoff-ru** [milessabin/shapeless#685]
Below is minimal project with sealed trait in one package (file `src/main/scala/ru/tinkoff/tcb/model/model.scala`) and usage of generic `copy` method on it in another package (file `./src/main/scala/ru/tinkoff/tcb/adapters/example.scala`). `sbt compile` gives error ("could not find implicit value for parameter update").

I expect this code compile correctly, because:

1. Same usage of copy near the trait declaration compiles well.
2. Moreover, exactly this code one _can_ compile in two passes: first, comment definitions of methods in file `./src/main/scala/ru/tinkoff/tcb/adapters/example.scala`, run `sbt compile`, uncomment definitions (reverting changes back) and `sbt compile` again.

[shapeless-implicit-not-found.zip](https://github.com/milessabin/shapeless/files/776285/shapeless-implicit-not-found.zip)

My scenario is such: I want to refactor some big class with many option fields to a sealed trait with several case classes. I can't put all in one package. Probably, it will help to move model classes to separate subproject (have not tested yet). But maybe there exists simpler way?

copySyntax object is taken from shapeless examples.

I've tried with sbt 0.13.0 on CentOS 6, oracle java 1.8.0_92.

--
Alexey Golovko, a.golovko1@tinkoff.ru

**Comment by Odomontois** [comment]
Probably related to https://github.com/scala/scala/pull/5284
You may try `scalaVersion := "2.12.1"` or `scalaOrganisation := "org.typelevel"`

**Comment by agolovko1-at-tinkoff-ru** [comment]
Thank you, have compiled successfully real project with `org.typelevel`.
Attached example also works with 2.12.1, but too many dependencies aren't built for scala 2.12.

**Comment by milessabin** [comment]
Thanks for the report ... if it's SI-7046 related then the only reliable fix is the compiler fix.
