### ISSUE TITLE
Sized & Equality

### ISSUE THREAD

**Issue by boggle** [milessabin/shapeless#687]
Today I was trying to construct a `Sized[Set](1, 2)` and then rely on equality to delegate to the Set.

(1) There is no instance of `AdditiveCollection` for `Set`, is there any particular reason for this?
(2) Sized doesn't delegate equality to the `Repr`. I kind-of expected that at least after validating that the sizes match.

I'm a new user of shapeless, so sorry if this is the wrong place to report this.

**Comment by milessabin** [comment]
Thanks for taking an interest in shapeless. General discussion of the library happens on its [gitter channel](https://gitter.im/milessabin/shapeless) rather than on issues. If you ask your questions there you'll find lots of people happy to help you explore.
