### ISSUE TITLE
ToMap cannot be materialized for case classes with a single attribute.

### ISSUE THREAD

**Issue by ashwin153** [milessabin/shapeless#690]
```scala
import shapeless._
import shapeless.labelled._
import shapeless.ops.record._

case class Foo(x: String)
case class Bar(x: String, y: Int)

def func[T, R <: HList](arg: T)(
  implicit gen: LabelledGeneric.Aux[T, R], 
  toMap: ToMap.Aux[R, Symbol, Any]
): Map[Symbol, Any] =
  toMap(gen.to(arg))

// Causes a compile error, because toMap could not be implicitly materialized.
func(Foo("test"))

// Compiles and returns Map[Symbol,Any] = Map('y -> 123, 'x -> test)
func(Bar("test", 123))
```

**Comment by milessabin** [comment]
I think most likely an issue with `ToMap` on records.

**Comment by ashwin153** [comment]
It only fails when I specify the types of toMap.Key and toMap.Value. If I do not specify them, then the code properly compiles.

```scala
import shapeless._
import shapeless.labelled._
import shapeless.ops.record._

case class Foo(x: String)
case class Bar(x: String, y: Int)

def func[T, R <: HList](arg: T)(
  implicit gen: LabelledGeneric.Aux[T, R], 
  toMap: ToMap[R]
): Map[toMap.Key, toMap.Value] =
  toMap(gen.to(arg))

// Compiles and returns.
func(Foo("test"))

// Compiles and returns.
func(Bar("test", 123))
```

**Comment by milessabin** [comment]
Ahh ... I see. Yes in your first example, you've constrained the value type to `Any`, but the actual value type in the single element case is `String`.

So this is actually as expected.

**Comment by ashwin153** [comment]
Is it expected though? Shouldn't a Map be covariant in its value?

**Comment by tkroman** [comment]
@ashwin153, I think this is due to the fact that although map is covariant, type parameters are contravariant. So, for `B <: A` `Aux[L, K, B]` is not a subtype of `Aux[L, K, A]`. I had some problems similar to this one recently and couldn't find a satisfying workaround, so if anyone has some suggestions, that would be super-useful. (Maybe going OT here)
