### ISSUE TITLE
Compiler hangs when using LabelledGeneric to convert classes 

### ISSUE THREAD

**Issue by vitorsvieira** [milessabin/shapeless#706]
Hi all,

Generic and LabelledGeneric are awesome tools to "convert" classes, but unfortunately this is not true when the classes have approx. more than 10 fields. The compiler loses the track of the implicits and it hangs.

One can easily spot such behaviour by adding more fields to the example given in the Shapeless Guide and in the exercises solutions.

I was pointed to https://github.com/scala/scala/pull/5649 when asking for a help on gitter and I understand that it is a work in progress, aiming to be delivered in scala 2.12.3. 

For now, how to use the pattern shown in the book and in recent talks with "real world" classes?

[https://github.com/underscoreio/shapeless-guide-code/tree/solutions/migrations/src/main/scala](https://github.com/underscoreio/shapeless-guide-code/tree/solutions/migrations/src/main/scala)

[Case Class Migration at Scala World, from Dave Gurnell](https://youtu.be/Zt6LjUnOcFQ?t=3795)

**Comment by milessabin** [comment]
I don't think this should be an issue until you get to ~30 fields ... do you have an example of a 10 field case class where the compilation time is unacceptable?

**Comment by vitorsvieira** [comment]
Hi Miles,

Here is an example:

https://github.com/vitorsvieira/shapeless-labelledgeneric-big-class/blob/master/src/main/scala/com/vitorsvieira/shapeless/labelledgeneric/bigclass/Main.scala

**Comment by milessabin** [comment]
Ahh ... understood. I think it's highly unlikely that the compile time cost is attributable to `LabelledGeneric` ... I think it's most likely the `Align` which is the culprit.

**Comment by Atry** [comment]
I guess a macro materializer for `Align` may help.

**Comment by Atry** [comment]
macro version `Align` will improve not only the compiler time but also run time

**Comment by milessabin** [comment]
@Atry do you have time to investigate whether `-Yinduction-heuristics` in Typelevel Scala help with this one?

**Comment by fspillner** [comment]
I have issues with compilation speed with Align too, but *only* if the implicits could not be resolved. If I put the right type, then it compiles fast.

**Comment by joroKr21** [comment]
Should be fixed by #682 - feel free to reopen otherwise.
