### ISSUE TITLE
Typeable.describe is using runtime reflection

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#707]
I was under the impression that all data was injected at compile time but I was surprised to see in ensime-server that our use of Typeable (when we started using `BigDataFormat` typeclass derivation) was causing a runtime performance problem with `Typeable.describe` calling `Class.getSimpleName`.

A manual inspection of the `typeable.scala` file shows that there are indeed cases where the lookup is at runtime. It would be good to solidify this stuff at compile time.

**Comment by milessabin** [comment]
Are you able to put any sort of numbers on the severity of the impact of this?

**Comment by fommil** [comment]
it was about 5% of our CPU time... but that's a pretty extreme throughput where we're calling this on every field in every object of the hierarchy for millions of objects. The workaround is of course trivial, by assigning the `describe` to a `lazy val` (or `val` if it's always going to be used) in a `cachedImplicit`.

**Comment by milessabin** [comment]
I think at least a couple of those can be computed at compile time and inlined as (non-lazy) Strings.
