### ISSUE TITLE
HList Schema definition

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#72]
It would be really useful (e.g. for JSON message definition) to be able to define an entire HList hierarchy in one statement, effectively an alternative to having lots of nested case classes.

**Comment by InTheNow** [comment]
@fommil The type provider link you gave refers to loading in a subset of a pre-defined owl ontology. Would this be what you had in mind?

I mention this as adding proper OWL support to banana-rdf is an ongoing project . eg see https://github.com/w3c/banana-rdf/issues/232 and https://github.com/w3c/banana-rdf/pull/229. 

But before going into too much detail, I wonder if you have some pseudo code of what you might expect, what an HList in one statement might actually look like?

**Comment by fommil** [comment]
an example of an API defined in case classes and sealed traits https://github.com/ensime/ensime-server/tree/master/api/src/main/scala/org/ensime/api

much of this is just boilerplate to define an API, although some of it is actually useful domain to pass around.

**Comment by fommil** [comment]
(btw, I'm pretty sure this doesn't need to be a core shapeless thing anymore, so closing)

to follow up some private gitter chat. What would be ideal is if an input file like so was parsed

```json
{
   "OData V1 and V2": {
      "d": {
         "__metadata": {
            "uri": "String @@ URI",
            "type": "String @@ Category"
         },
         "ID": "Number",
         "Name": "String",
         "Products": [
            {
               "__metadata": {
                  "uri": "String @@ URL",
                  "etag": "String @@ ETag",
                  "type": "String @@ Product"
               },
               "ID": "Number",
               "Name": "String",
               "Description": "String",
               "ReleaseDate": "String @@ IsoDate",
               "DiscontinuedDate": "String @@ IsoDate",
               "Rating": "Number",
               "Price": "String",
               "Concurrency": "Number",
               "Category": {
                  "__deferred": {
                     "uri": "String"
                  }
               },
               "Supplier": {
                  "__deferred": {
                     "uri": "String"
                  }
               }
            }
         ]
      }
   }
}
```

(or any JSON schema really) which produces a lens-like object into a JSON AST such as spray-json.

I say json-like because I'd like to start with a parsed `d: JsValue` and be able to type `d.__metadata.Products(0).ReleaseData` receiving a `String @@ IsoDate` (or perhaps its a case class that has a corresponding `JsonFormat`). What this would be doing is calling `d.asJsObject("__metadata").asJsObject("Products").asInstanceOf[JsArray](0).asJsObject("ReleaseData").asInstanceOf[JsString].convertTo[String]` (but with better error handling!)

**Comment by InTheNow** [comment]
FYI, even though this is now closed;

Referenced in cats - https://github.com/non/cats/issues/18, via https://github.com/snowplow/schema-guru/issues/103, is https://github.com/snowplow/schema-guru. 

@fommil Looks like this could be what you want - they even have circe support on their horizon, too https://github.com/snowplow/schema-guru/issues/104

CC/ @chuwy

**Comment by chuwy** [comment]
Hey @InTheNow
Thanks for reference. I settled that issue on far-away milestone. I think it's very interesting thing to explore in Schema Guru.
