### ISSUE TITLE
Have a Refute typeclass

### ISSUE THREAD

**Issue by zainab-ali** [milessabin/shapeless#721]
There was some talk a while back on Gitter about having a `Refute` typeclass:

```scala
/** Evidence that an implicit A is not present */
trait Refute[A]

object Refute {
  implicit def ambiguous1[A](implicit ev: A): Refute[A] = new Refute[A] {}
  implicit def ambiguous2[A](implicit ev: A): Refute[A] = new Refute[A] {}
  implicit def refute[A]: Refute[A] = new Refute[A] {}
}
```

This is a useful tool when using inductive implicits.  Should this exist in shapeless?
If so, I'd be happy to add it

**Comment by milessabin** [comment]
Yes, please do :-)

**Comment by zainab-ali** [comment]
This has now been merged in

**Comment by milessabin** [comment]
Thanks ... sorry I should have closed this earlier :-)
