### ISSUE TITLE
`AdditiveCollection` not defined for` Seq`?

### ISSUE THREAD

**Issue by dimitriye98** [milessabin/shapeless#725]
Why isn't `AdditiveCollection` defined for `Seq` itself? It makes it pretty much impossible to use sized Seqs, since all of the underlying methods require an AdditiveCollection type class.

**Comment by milessabin** [comment]
`Seq` only requires an ordering of it's elements, it doesn't require the additive behaviour that `AdditiveCollection` requires ... instances of the latter are defined ad hoc for concrete data types which do behave appropriately. `Stream` would be problematic, for instances. And there's nothing to stop someone from defining a `Seq` subtype with ordered-set-like behaviour.

**Comment by dimitriye98** [comment]
`Stream` already has an applicable `AdditiveCollection` though? `Stream` is a `LinearSeq`, for which an `AdditiveCollection` conversion exists.

**Comment by jxnu-liguobin** [comment]
It seems that this question can be used to get started? @joroKr21
