### ISSUE TITLE
Typeable in pattern matching

### ISSUE THREAD

**Issue by kamilkloch** [milessabin/shapeless#739]
The latest published shapeless release (2.3.2) does not support type arguments on patterns, as described in https://github.com/typelevel/scala/blob/typelevel-readme/notes/typelevel-4.md#type-arguments-on-patterns-pull5774-paulp

**Comment by wheaties** [comment]
That's a bold statement, can you back it up with an example?

**Comment by kamilkloch** [comment]
Maybe I am doing something wrong, but the change is missing in these sources:
http://repo1.maven.org/maven2/com/chuusai/shapeless_2.11/2.3.2/

**Comment by milessabin** [comment]
Right. That hasn't been release yet.

**Comment by joroKr21** [comment]
It should be in 2.3.3 now?

**Comment by milessabin** [comment]
Yup.
