### ISSUE TITLE
should shapeless have Not?

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#740]
I noticed that @zainab-ali recently contributed `Refute`

There is an old jedi mind trick I've been using for years from  https://stackoverflow.com/questions/15962743

```
  trait Not[A]
  implicit def notA[A, TC[_]]: Not[TC[A]] = new Not[TC[A]] {}
  implicit def notNotA[A: TC, TC[_]]: Not[TC[A]] = new Not[TC[A]] {}
```

(that post has two more `implicit def`s) and I wonder if it should be included in shapeless.

A usecase I had recently was that we have this ADT

```
sealed trait Loggable
final case class LValue(value: String) extends Loggable
final case class LObject(entries: Seq[(String, Loggable)]) extends Loggable
```

(just a leaf / branch structure) and these typeclasses

```
@typeclass
trait ToLoggable[A] {
  def toLoggable(a: A): Loggable
}
@typeclass
trait ValueLogger[A] extends ToLoggable[A] {
  def toLValue(a: A): LValue
  final override def toLoggable(a: A): Loggable = toLValue(a)
}
@typeclass
trait ObjectLogger[A] extends ToLoggable[A] {
  def toLObject(a: A): LObject
  final override def toLoggable(a: A): Loggable = toLObject(a)
}
```

If there is a default instance of `ValueLogger` for `Option[T]` (where there is a `ValueLogger[T]`) this causes problems for generic derivation because we get ambiguous implicits when we want to have this type signature

```
  implicit def ObjectLoggerGeneric[T, Repr](
      implicit
      G: LabelledGeneric.Aux[T, Repr],
      LER: Cached[Strict[ObjectLogger[Repr]]]
    ): ObjectLogger[T] = ObjectLogger.instance { t =>
    LER.value.value.toLObject(G.to(t))
  }
```

which can be fixed by adding in `NOT: Not[ValueLogger[T]]` evidence, stopping generic derivation from trying to derive the `Option[T]`.

**Comment by zainab-ali** [comment]
Now that I've taken a better look at this, I think it can be solved by using `Refute[ValueLogger[T]]`.  `Refute` uses the same jedi magic as `Not` as far as I can tell.
Have you given it a try?

**Comment by fommil** [comment]
yes it did work, sorry I wasn't very clear... `Not` has these two extra implicits that I'm not sure what they do

```
  implicit def notM[M[_], TC[_[_]]] = new Not[TC[M]] {}
  implicit def notNotM[M[_] : TC, TC[_[_]]] = new Not[TC[M]] {}
```

**Comment by zainab-ali** [comment]
I'm not sure either - `Refute` (or `Not`) works for typeclasses without those extra implicits

**Comment by fommil** [comment]
yeah, it would appear so. Must be for higher order things. Ok, well that's settled! Looking forward to `Refute`, should save me a few lines of copy/paste and it'll probably make it into my book under an advanced generic derivation example.
