### ISSUE TITLE
CSV Example

### ISSUE THREAD

**Issue by captainobscure** [milessabin/shapeless#741]
I have taken a look at the csv.scala example file and attempted to use in 2.11 and 2.12 I have been getting a diverging implicit expansion for type CSVConverter[this.Repr] starting with method deriveClass in object CSVConverter.  I have also seen not enough arguments for method implicitly CSVConverter[List[Person]]...  Not sure exactly why this isn't working for me, or if something has changed since the last check in.  Does anyone have some tips on what I am doing wrong or if something has changed.  Cheers

**Comment by milessabin** [comment]
Is this the exact example in `examples/src/main/scala/shapeless/examples/csv.scala` or have you modified it in some way? Have you extracted it to a standalone project? In which case, what does your build.sbt look like?

**Comment by joroKr21** [comment]
Not enough details to be actionable.
