### ISSUE TITLE
cachedImplicit for defs

### ISSUE THREAD

**Issue by fommil** [milessabin/shapeless#746]
(well, not really *cached*, more like a `doThisDerivationHerePlease`)

Motivation: we are wanting to introduce Haskell-style `deriving` support in stalagmite https://github.com/fommil/stalagmite/issues/1 and https://github.com/fommil/stalagmite/issues/40

```scala
@data(deriving = Functor)
class Cat[Food](food: Option[Food], foods: List[Food])
```

There are a lot of advantages to doing this besides compiletime and runtime performance, not least that it means that instances are defined on the implicit scope of `Cat` rather than being orphaned.

For basic data types, this means putting a `implicit val ... = cachedImplicit` on the companion for whatever the user wants.

This works (in the sense that it correctly fails to compile)

```scala
import cats.Functor

case class Cat[Food](food: Option[Food], foods: List[Food])
object Cat {
  implicit val CatFunctor: Functor[Cat] = shapeless.cachedImplicit
}
```

But the following does not (i.e. it compiles but it should not)

```scala
import _root_.io.circe
import circe._

case class Cat[Food](food: Option[Food], foods: List[Food])
object Cat {
  implicit def CatEncoder[A: Encoder]: Encoder[Cat[A]] = {
    def CatEncoder = ???
    implicitly[Encoder[Cat[A]]]
  }
}
```

It compiles because the `implicitly` recurses on itself via `Cat`'s implicit scope (where we are defining `CatEncoder`), it's not actually finding the generic instance. This is a big problem because it's easy to make and we want the compiler to catch it rather than recurse.

What we need is something that `cachedImplicit` but for `def`s which stops the recursion, and any other gotchas that `cachedImplicit` is working around.

Would it be as "simple" as copy/pasting the `cachedImplicit` macro and changing it to support `def` with type parameters? The caching bit is not so important, it's really just support for this kind of thing that we need https://github.com/milessabin/shapeless/commit/ffe50c8da741f1b0adf1436e0a17bd93ac076964

**Comment by milessabin** [comment]
Can you explain your `Cat` functor example some more? Why isn't `val CatFunctor` what you want there?

**Comment by fommil** [comment]
Because cat has a type variable

**Comment by fommil** [comment]
Or maybe Functor is a bad example, any implicit that needs a type parameter.

**Comment by milessabin** [comment]
Your circe example fails because `Dog` isn't a case class.

I'm going to close this for now. Please reopen when you have a small, self contained example of the problem.

**Comment by fommil** [comment]
I'm working on editing the text.

**Comment by fommil** [comment]
it is updated

**Comment by milessabin** [comment]
The update makes your question a lot clearer. Thanks.

Could you turn that example into a standalone (ie. no circe dependency) failing test. Thanks.

**Comment by fommil** [comment]
I guess I could use something from the stdlib like `Numeric`

**Comment by fommil** [comment]
standalone

```
case class Complex[T](real: T, img: T)
object Complex {
  implicit def n[T: Numeric]: Numeric[Complex[T]] = {
    def n = ??? // shadow
    implicitly[Numeric[Complex[T]]]
  }
}
```

it would be great to have something like this negative example:

```case class Complex[T](real: T, img: T)
object Complex {
  implicit def n[T: Numeric]: Numeric[Complex[T]] = cachedImplicit
}
```

that failed to compile. To give you a small self-contained positive example, I'd need access to something with a generic deriver from shapeless. Maybe the sexp example? Or is this enough?

**Comment by fommil** [comment]
what am I talking about... I already have something like this that can be used. The above should *succeed* when this is in scope

```
implicit def numericComplex[T: Numeric]: Numeric[Complex[T]] =
  new Numeric[Complex[T]] {
    type CT = Complex[T]
    def plus(x: CT, y: CT): CT = Complex(x.r + y.r, x.i + y.i)
    def times(x: CT, y: CT): CT =
      Complex(x.r * y.r + (-x.i * y.i), x.r * y.i + x.i * y.r)
    def negate(x: CT): CT = Complex(-x.r, -x.i)
    def zero: CT = Complex(Numeric[T].zero, Numeric[T].zero)
    def compare(x: CT, y: CT): Int = {
      val real = (Numeric[T].compare(x.r, y.r))
      if (real != 0) real
      else Numeric[T].compare(x.i, y.i)
    }
  }
```

**Comment by milessabin** [comment]
OK, that helps.

But, with that in mind, can you try and reduce this some more, if only as an exercise in minimization so that you know the kind of thing I'm looking for in future. For instance, it doesn't have to be `Numeric` per se, and none of the `Numeric` method implementations above are relevant.

Try and reduce the example to the bare minimum so that it can form the basis of a test for the fix.

**Comment by milessabin** [comment]
For instance, [this](https://github.com/milessabin/shapeless/issues/747) is exemplary.

**Comment by fommil** [comment]
well, excepting that it doesn't have imports :wink:

**Comment by fommil** [comment]
Negative case, should not compile due to missing implicit (doesn't need to be `cachedImplicit`, can also be a new method)

```
import shapeless._

trait Foo[T]

case class Bar[T](a: T)
object Complex {
  implicit def foo[T: Foo]: Foo[Bar[T]] = cachedImplicit
}
```

positive case, should compile. Add

```
object Foo {
  implicit def bar[T: Foo]: Foo[Bar[T]] = new Foo[Bar[T]] {}
}
```

**Comment by milessabin** [comment]
Hmm ... interesting. However I don't think the positive case _should_ compile. `foo` and `bar` are ambiguous and have the same relative priority.

**Comment by milessabin** [comment]
I take that back ... not sure. Will investigate.

**Comment by fommil** [comment]
this is why I find it easier to create examples that I can verify with the compiler.

**Comment by fommil** [comment]
I've read it again and I'm pretty sure this should work. It's weird that I'm defining an instance for `Foo[Bar[T]]` on the `Bar` companion because the realistic case is that there would be generic derivation for `Foo` and I didn't want to add the 50 LOC of boilerplate for that.

**Comment by fommil** [comment]
swap `cachedImplicit` out for

```scala
  implicit def foo[T: Foo]: Foo[Bar[T]] = {
    def foo = ??? // shadow
    implicitly[Foo[Bar[T]]]
  }
```

to see both compiling. To verify the behaviours of this simple trick (sadly only verified runtime), define a `Foo[String]` on the `Foo` companion and request an instance of `Foo[Bar[String]]`. You'll get a stackoverflow for the first case.

```scala
implicit val string: Foo[String] = new Foo[String] { }
```

**Comment by fommil** [comment]
I'm not sure this is a "bug" since `cachedImplicit` is only supposed to work for `val`, rather a feature request to support `implicit def`.

BTW, perhaps the example is better like this:

```scala
import shapeless._

trait Foo[T]

case class Bar[T](a: T)
object Bar {
  implicit def foo[T: Foo]: Foo[Bar[T]] = cachedImplicit
}
```

positive case, should compile. Add

```
import Derived._

object Derived {
  // not really generic derivation, but good enough for our purposes
  implicit def bar[T: Foo]: Foo[Bar[T]] = new Foo[Bar[T]] {}
}
```

**Comment by fommil** [comment]
I don't think I need this anymore. If anybody else is interested, I'm happy for it to be reopened but it's not something I'll be working on.
