### ISSUE TITLE
Implicit Default[] instantiation fails when base trait with abstract method is used for companion object

### ISSUE THREAD

**Issue by grindvoll** [milessabin/shapeless#747]
The following example doesn't compile with Scala 2.11 and shapeless 2.3.2 (implicit Default[Sample] not found):

```scala
case class Sample(a: Int)
trait Companion {
  def default: Default[Sample]
}
object Sample extends Companion {
  val default = Default[Sample]  // Error: No Default[Sample] found
}
```

The compile error is triggered by defining the default method in the base trait and implementing it as a `val` in the object that derives from the trait. One of the following changes makes the code compile:
  
  * Removing the method in the base trait
  * Adding an explicit type for the val; e.g. `val default: Default[Sample] = ...`
  * Changing the `val` to a `def`
 
The code compiles with Scala 2.12.3.

**Comment by joroKr21** [comment]
That's really fascinating. It's another case of "recursive value needs type". The difference between Scala 2.11 and 2.12 can be illustrated by this:
```scala
case class Sample(a: Int)
trait Companion {
  def default: Stream[Sample]
}
object Sample extends Companion {
  val default = Sample(0) #:: default // Works in 2.12, but needs type in 2.11
}
```
The type signature of `default` is forced [here](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/default.scala#L227) in the macro, which apparently solves #474. All in all I'm not sure if this is a Scala bug, a Shapeless bug or even a bug at all.

**Comment by milessabin** [comment]
@joroKr21 can you confirm that #760 fixes this issue as well? If so, please add this test case to your PR.

**Comment by joroKr21** [comment]
It doesn't fix this, because `DefaultMacros` explicitly forces the type signature of the companion object on [line 227](https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/default.scala#L227), but we cannot remove that line because it fixes another issue.

**Comment by joroKr21** [comment]
Actually removing that line doesn't break any tests, but it doesn't fix this issue either, because a few lines below we call `.decls` on the companion object. I think calling `.decl("apply")` instead won't force the signature of all declarations. Another question is whether we want to call `.decl` or `.member` (do we want to check `.apply` methods coming from a super class?

**Comment by joroKr21** [comment]
Another question is - should `Default[Nil.type]` exist or not?
