### ISSUE TITLE
Typeable should check the owner of nested types

### ISSUE THREAD

**Issue by Atry** [milessabin/shapeless#748]
``` scalaWelcome to the Ammonite Repl 1.0.0
(Scala 2.12.2 Java 1.8.0_131)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`com.chuusai::shapeless:2.3.2` 
import $ivy.$                             
@ import shapeless.syntax.typeable._ 
import shapeless.syntax.typeable._
@  
@ class Outer {
    class Inner
    val inner: Inner = new Inner
  } 
defined class Outer
@  
@ val outer1 = new Outer 
outer1: Outer = ammonite.$sess.cmd2$Outer@5ca006ac
@ val outer2 = new Outer 
outer2: Outer = ammonite.$sess.cmd2$Outer@4e8036bb
@  
@ println(outer1.inner.cast[outer2.Inner]) 
Some(ammonite.$sess.cmd2$Outer$Inner@174bbe8e)

```

`outer1.inner.cast[outer2.Inner]` should be `None` because the owner does not match. However, `Typeable` does not check the owner, and returns a `Some`.

**Comment by milessabin** [comment]
Good spot. I see two ways of fixing this,
+ Exclude cast targets with a dependent prefix (ie. there would be no `Typeable` instance for `outer2.Inner`).
+ Allow cast targets with a dependent prefix and verify it. That would involve digging out the outer reference from the inner instance and verifying that it is identical to the requested prefix.

Would you like to give either of these a try?

**Comment by Atry** [comment]
Should the prefix be checked via `eq` or `==`?

**Comment by milessabin** [comment]
`eq`.

**Comment by Atry** [comment]
The `Typeable` type class may contain a `Witness.Aux[outer2.type]`. However, I have no idea to get a `Witness.Aux[outer1.type]` in the `cast` method.

**Comment by milessabin** [comment]
The `Typeable` macro should be able to dig the prefix term directly out of the `SingleType` that you'll find somewhere in the cast target. You won't need a `Witness`.

**Comment by Atry** [comment]
Unfortunately `cast` is not a macro.

**Comment by milessabin** [comment]
`Typeable` instances are materialized via a macro.

**Comment by Atry** [comment]
> Exclude cast targets with a dependent prefix (ie. there would be no Typeable instance for outer2.Inner).

Given:
``` scala
class Outer {
  class Inner
  val inner: Inner = new Inner
} 
package object mypackage extends Outer
```

Will the following code be forbidden in this approach?
``` scala
implicitly[Typeable[mypackage.Inner]]
```

**Comment by Atry** [comment]
So how to witness `outer1` when invoking `outer1.inner.cast[xxxx]`?

**Comment by milessabin** [comment]
> So how to witness outer1 when invoking outer1.inner.cast[Xxx]?

You'd have to did the outer reference out of the instance using runtime reflection.

**Comment by joroKr21** [comment]
How about using pattern matching?
```scala
(outer1.inner: Any) match {
  case _: outer2.Inner => "yes"
  case _ => "no"
} // => no
```
