### ISSUE TITLE
Generic fails to materialize ADT defined in trait

### ISSUE THREAD

**Issue by alexarchambault** [milessabin/shapeless#758]
A bit similar to https://github.com/milessabin/shapeless/issues/212, but with an ADT instead of a case class.

```scala
trait Defs {
  sealed abstract class Foo extends Product with Serializable

  object Foo {
    case object A extends Foo
    case object B extends Foo
  }
}

class Inst extends Defs {
  val gen = Generic[Foo]
}
```
fails to compile with
```
could not find implicit value for parameter gen: shapeless.Generic[Inst.this.Foo]
```

Changing `Generic[Foo]` to `Generic.materialize[Foo, Foo.A.type :+: Foo.B.type :+: CNil]` gives more details:
```
Sealed trait Inst.this.Foo has no case class subtypes
```

Changing the definition of `Defs` above to
```scala
trait Defs {
  sealed abstract class Foo extends Product with Serializable

  case object A extends Foo
  case object B extends Foo
}
```
gives the same errors.

**Comment by milessabin** [comment]
This looks more like (a variant of) https://github.com/scala/bug/issues/7046 ... what version of scalac are you using?

**Comment by alexarchambault** [comment]
I'm using scala 2.12.3.

I'm not sure it's a variant of https://github.com/scala/bug/issues/7046. If a case class constructor is added, like
```scala
trait Defs {
  sealed abstract class Foo extends Product with Serializable

  case object A extends Foo
  case object B extends Foo
  final case class C() extends Foo
}
```
and the definition of the class changed to
```scala
class Inst extends Defs {
  val gen = Generic.materialize[Foo, A.type :+: B.type :+: C :+: CNil]
}
```
one gets the following error:
```
type mismatch;
[error]  found   : shapeless.Generic[Inst.this.Foo]{type Repr = Inst.this.C :+: shapeless.CNil}
[error]  required: shapeless.Generic.Aux[Inst.this.Foo,Inst.this.A.type :+: Inst.this.B.type :+: Inst.this.C :+: shapeless.CNil]
[error]     (which expands to)  shapeless.Generic[Inst.this.Foo]{type Repr = Inst.this.A.type :+: Inst.this.B.type :+: Inst.this.C :+: shapeless.CNil}
[error]   val gen = Generic.materialize[Foo, A.type :+: B.type :+: C :+: CNil]
[error]                                ^
```

Only the case objects are not seen, the case classes are fine.

**Comment by alexarchambault** [comment]
Some quick debugging showed that `A` and `B` are "seen", but are filtered out by [this condition](https://github.com/milessabin/shapeless/blob/2f284a6e58d688c985e6798994185f696e3fbaff/core/src/main/scala/shapeless/generic.scala#L451).
