### ISSUE TITLE
Add support for Generic case-like classes with vars

### ISSUE THREAD

**Issue by joroKr21** [milessabin/shapeless#767]
... or drop case-like classes altogether. Either way make it consistent:
```scala
case class A(i: Int); Generic[A] // ok
case class B(var i: Int); Generic[B] // ok
class C(val i: Int); Generic[C] // ok
class D(var i: Int); Generic[D] // mutable AND no case? No Generic for you sir!
```

**Comment by joroKr21** [comment]
An argument for the latter:
```scala
object Tetration extends App {
  import shapeless._

  class Squared(x: Long) {
    val x2 = x * x
    override def toString = x2.toString
  }

  def id[A](x: A)(implicit gen: Generic[A]) = gen.from(gen.to(x))
  println(Seq.iterate(new Squared(2), 5)(id(_)))
  // List(4, 16, 256, 65536, 4294967296)
}
```

**Comment by joroKr21** [comment]
Skimming #360 suggests the former.

**Comment by milessabin** [comment]
That's a nice example, but it looks orthogonal to this issue as currently titled.

**Comment by milessabin** [comment]
FWIW, I could be persuaded to either remove support for vars in case classes or add support for vars in case-like classes.

**Comment by joroKr21** [comment]
Personally I'm :+1: for adding var support in both cases. Mutability doesn't really change anything regarding `Generic`. And I don't think we should drop support for something with no good reason.

**Comment by milessabin** [comment]
Both cases it is then :-)
