### ISSUE TITLE
Compiler generated names leak via LabelledGeneric

### ISSUE THREAD

**Issue by joroKr21** [milessabin/shapeless#768]
```scala
object Main extends App {
  import shapeless._
  case class C(private val i: Int)
  val gen = LabelledGeneric[C]
  val keys = ops.record.Keys[gen.Repr]
  println(keys()) // 'i$access$0 :: HNil
}
```
Is it better to present the user with a convenient lie (`i`) or the ugly truth (`i$access$0`)? I don't know.

**Comment by milessabin** [comment]
Interesting. I'm reluctant to complicate things to accommodate access control in general, and in this case in particular.

What's the motivation for making a case class field private? It would leak via unapply,
```scala
scala> case class C(private val i: Int)
defined class C

scala> C(23)
res0: C = C(23)

scala> res0.i
<console>:13: error: value i in class C cannot be accessed in C
       res0.i
            ^

scala> val C(i) = res0
i: Int = 23
```

**Comment by joroKr21** [comment]
To be honest I have no idea why someone would define a case class like this. But it's in the [stdlib cons](https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/immutable/List.scala#L447). I noticed this in one of the tests for `Generic[List[Int]]`

**Comment by joroKr21** [comment]
I wanted to see if I can add a check for field name = constructor parameter name to avoid things like [this](https://github.com/milessabin/shapeless/issues/767#issuecomment-330111026).

**Comment by milessabin** [comment]
Gotcha. I'm pretty sure I investigated making constructor argument names line up with accessor names, and I think I decided that in practice there were too many ad hoc differences between the names to make it feasible. Even with a rule restricting `Generic` instances to cases were the names exactly match it would be possible to come up with cases similar to #767.
