### ISSUE TITLE
Dynamic extractor syntax for Unions

### ISSUE THREAD

**Issue by joroKr21** [milessabin/shapeless#769]
Would there be interest in adding syntax sugar for pattern matching unions?
```scala
sealed trait Fruit
case class Banana(ripe: Boolean) extends Fruit
case class Apple(color: Color) extends Fruit

val gen = LabelledGeneric[Fruit]
val union = gen.to(Banana(true))
val buy = union match {
  case Key.Banana.Val(b) => b.ripe
  case Key.Apple.Val(a) => a.color == Color.red
}
```
I guess it is subsumed by `.fold`, but it doesn't require a `Poly` definition. The downside is that scalac can't possibly check exhaustivity.

**Comment by milessabin** [comment]
I'm not opposed, but I'm not completely convinced that it offers all that much over nested `Inl`/`Inr` ... under what circumstances would you be pattern matching on the `Generic` representation, but using ADT specific information (ie. `Banana`, `Apple` etc.) rather than pattern matching directly on an ADT value?

**Comment by joroKr21** [comment]
Yes, you are right, there aren't many use cases for this. I was experimenting with automatically deriving a fixpoint of functors representation for an ADT, but then I realized that writing an algebra for a morphism is not feasible unless I have the syntax outlined above. Ofc I can add it to my own code instead of shapeless. Just curious if other people find it useful (probably not many know it's even possible).

**Comment by milessabin** [comment]
Maybe add it as an example?

**Comment by joroKr21** [comment]
:+1: If my experiments yield something self-contained I will add it.

**Comment by joroKr21** [comment]
Closing this issue since said extractors are use case specific.
Usage can be seen in the recursion schemes example added with #788
