### ISSUE TITLE
Casting with implicit classtags

### ISSUE THREAD

**Issue by amitpaz** [milessabin/shapeless#770]
Hello, 
I'm trying to do the following: 
```
import shapeless.syntax.typeable._
import scala.reflect.ClassTag

class Example {
    def doSomething[T](implicit tag: ClassTag[T]) = {
        var items: Any = List("item1")
        items.cast[T]
    }
}

val ex = new Example
ex.doSomething
```
i'm getting the following compilation error: 

> Error:(8, 20) class type required but T found
>         items.cast[T]
>                   ^

Thanks

**Comment by milessabin** [comment]
For future reference, questions about usage should be asked by opening issues ... you'll find lots of people to help out on shapeless's [gitter channel](https://gitter.im/milessabin/shapeless).

shapeless's `Typeable` is largely unrelated to scala.reflect. In your example you need something along these lines instead,
```scala
def doSomething[T](implicit typeable: Typeable[T]): Option[T] = {
  val items: Any = ...
  items.cast[T] // yields an Option[T]
}
```
