### ISSUE TITLE
ZipOne on coproducts throws runtime exceptions in most cases

### ISSUE THREAD

**Issue by SystemFw** [milessabin/shapeless#772]
Coproduct ops include a `ZipOne` typeclass, witnessing that zipping two coproducts is the coproduct of tuples of elements taken pairwise, e.g. 
```scala
ZipOne[Int :+: String :+CNil, Boolean :+: Double :+: CNil]
res0: ZipOne {type Out = (Int, Boolean) :+: (String, Double) :+: CNil
```
However, this evidence is clearly false, as you can't guarantee that you'll always have both elements when you zip. Matter of fact, it only compiles due to the use of  `Option#get` on the Coproduct head.

As a result, if you pass in anything but two `Inl`, it throws an exception.

Is this intended behaviour? Imho this op should either be removed, or changed to return a more meaningful type, i.e. a Coproduct of cats `Ior`. WDYT?

**Comment by milessabin** [comment]
Oh! That's definitely not right!

A coproduct `ZipOne` can definitely be defined, analogous to the hlist `ZipOne`, but this very definitely isn't it. I think that it was probably intended as a step in the direction of a coproduct `Transpose`, as was the case with hlist `ZipOne` (for generalized products zip == unzip == transpose), which misfired.

I think removing it is probably the best bet, with bonus marks for actually adding coproduct transpose ;-)

**Comment by SystemFw** [comment]
I'll do a quick PR to remove it (and add transpose to my never-ending todo list ;))
