### ISSUE TITLE
Implicit Generic.Aux failing to resolve without explicit type parameters

### ISSUE THREAD

**Issue by alexfoxgill** [milessabin/shapeless#785]
I'm trying to create generic `Gen[T]` instances from the scalacheck library. The problem seems to be that the `Repr` parameter of `Generic.Aux` isn't inferred automatically. Am I missing something?

```scala
import shapeless._

object AutoGenerate {

  implicit def stringGen: Gen[String] = Arbitrary.arbString.arbitrary

  implicit def hNilGen: Gen[HNil] = Gen.const(HNil)

  implicit def hListGen[H, T <: HList](implicit hGen: Lazy[Gen[H]], tGen: Gen[T]): Gen[H :: T] =
    for {
      h ← hGen.value
      t ← tGen
    } yield h :: t

  implicit def genericGen[A, R](implicit aux: Generic.Aux[A, R], rGen: Lazy[Gen[R]]): Gen[A] =
    rGen.value.map(x ⇒ aux.from(x))

  case class Foo(x: String)

  val implicitTest = {
    implicitly[Gen[String]] // fine
    implicitly[Gen[HNil]] // fine
    implicitly[Gen[String :: HNil]] // fine
    implicitly[Generic.Aux[Foo, String :: HNil]] // fine
    implicitly[Generic[Foo]] // fine
    genericGen[Foo, String :: HNil] // fine
    implicitly[Gen[Foo]] // could not find implicit value for parameter e: org.scalacheck.Gen[AutoGenerate.Foo]

    implicit val withRepr = genericGen[Foo, String :: HNil] // fine
    implicitly[Gen[Foo]] // fine now that the Repr parameter has been specified explicitly
  }
}
```

Scala version: `2.11.8`
Shapeless version: `2.3.2`

**Comment by alexfoxgill** [comment]
Further experimentation reveals that this problem seems to be specific to the `Gen` type. Perhaps because it comes from a third-party library? Either way I was able to workaround by creating a wrapper class

**Comment by alexfoxgill** [comment]
Another update: I believe this is caused by `Gen` being covariant in its type parameter, in which case I'm not sure if this is a bug or not

**Comment by milessabin** [comment]
I think the behaviour is surprising, but probably not a bug. You might want to compare notes with @alexarchambault and also take a look at https://github.com/alexarchambault/scalacheck-shapeless.

**Comment by joroKr21** [comment]
This is one reason among others why typeclasses should be invariant in general.
Note that in Scalacheck `Gen` is not a typeclass, but `Arbitrary` (invariant) is.
I don't think there is anything we can do in shapeless about that.
