### ISSUE TITLE
Why newtype(m).isInstanceOf[MType] and how to circumvent this?

### ISSUE THREAD

**Issue by schlichtanders** [milessabin/shapeless#786]
Dear team,

I stumbled upon creating a newtype following the example on https://github.com/milessabin/shapeless/blob/master/examples/src/main/scala/shapeless/examples/newtype.scala

however I am unable to tweak it such that ``ms.isInstanceOf[String]`` will return ``false``. Actually I thought this would be one of the usecases of a newtype operator, but maybe I am confusing some haskell here.

What would you do to create something which *behaves* like String, but looks like something completely new? I tried to change the Repr Type, i.e. doing ``type MyString = Newtype[Any, MyStringOps]`` but that doesn't work unfortunately.

**Comment by joroKr21** [comment]
There's nothing wrong with `isInstanceOf[String]`. It means no runtime cost (`isInstanceOf` is a runtime check that has no equivalent in Haskell). At compile time `String` and `MyString` are not related (`ms: String` and `"str": MyString` don't work). This is pretty much in line with Haskell's `newtype`.

**Comment by milessabin** [comment]
As @joroKr21 observes, this is as intended ... shapeless's newtype is a compile-time construct and if you do dynamic coercions at runtime then all bets are off.

**Comment by schlichtanders** [comment]
thank you very much for your time and explanation. Yeah, that makes totally sense. Unfortunate, that scala's case matching is also a runtime thing... unlike haskell

**Comment by milessabin** [comment]
Fair comment wrt pattern matching.
