### ISSUE TITLE
Forcing instance from companion object

### ISSUE THREAD

**Issue by gaydenko** [milessabin/shapeless#796]
Hi! 

I'd want to bring you attention to ambiguity I have met recently.
Here https://scastie.scala-lang.org/gaydenko/Erq9WXYiROq689JuQZBVjg short
test case takes place, and almost all code is just a `CsvEncoder` from
the shapeless guide. The test case output is:
```
List(with data)
List(Something special)
```
You see, we just get `Data` having special `CsvEncoder` instance and two
case classes using this `Data`. The only difference is for the second
one (`WithData2`) we import `Data.encoder` just before summoning
`WithData2.encoder`.

As a result, at the first case we get shapeless-generated
`CsvEncoder` instance for `Data`, and at the second case we get
specialized `CsvEncoder` for `Data`.

So, the question is: what is that robust way to use specialized
encoder (would it exists in the companion object) at any case, that
is without remembering to bring `Data.encoder` to nearest scope
```
  implicit val dataEncoder = Data.encoder
  implicit val encoder: CsvEncoder[WithData2] = cachedImplicit
```
? I mean `CsvEncoder` code modification and keeping `Data`-using
code intact.

**Comment by gaydenko** [comment]
Unfortunately import deleting isn't a decision. You see, it is "don't" (that is don't import this, this and that in the file header even you are using it here twenty times) which must be spread among all the project team (and transferred on team change). It would be a constant possibility of fatal errors (say, companion object's instance uses some validation on the fly or hides secret data, but shapeless generated instance was accidentally  used). 

Can we modify `CvsEncoder` the way forcing a developer explicitly select which instance to use (that is result in compilation error at such vague situations)?

**Comment by joroKr21** [comment]
Nothing actionable here
