### ISSUE TITLE
Release for 2.13.0-M3

### ISSUE THREAD

**Issue by fthomas** [milessabin/shapeless#811]
This requires https://github.com/scalamacros/paradise/issues/112 and https://github.com/milessabin/macro-compat/issues/77.

**Comment by SethTisue** [comment]
both paradise and macro-compat are now available for M3. @milessabin time to publish Shapeless...?

**Comment by SethTisue** [comment]
ah I see you've commented at https://github.com/scala/scala-dev/issues/431#issuecomment-363364170

**Comment by milessabin** [comment]
Report/PR for a bug which breaks usages of shapeless's `Zipper` here: https://github.com/scala/bug/issues/10714.

I'll release shapeless with the `Zipper` tests and examples temporarily tweaked to work around the problem. They're not widely used in the wild, so I don't think them being broken will cause too much grief.

**Comment by milessabin** [comment]
Done.

I found a workaround for the `Zipper` failures.
