### ISSUE TITLE
Generic representations may not have unique keys

### ISSUE THREAD

**Issue by travisbrown** [milessabin/shapeless#817]
The following sealed trait hierarchy is one example:

```scala
sealed trait Base
object Foo { case object Qux extends Base }
object Bar { case object Qux extends Base }
```

The `LabelledGeneric` representation will be a union that contains the key `'Qux` twice. This causes [issues](https://github.com/circe/circe/issues/855#issuecomment-372502585) for circe's generic derivation, for example, where the behavior unexpectedly changed between 0.8 and 0.9 because of the invalid assumption that the keys in these unions would always be unique.

In circe we're likely just to have generic derivation fail in these cases (this is accidentally the current behavior, anyway). I don't have a strong opinion on what Shapeless itself should do, and would be happy to see this issue closed as "won't fix"—providing the instances even if unique keys can't be guaranteed seems reasonable, since users can always decide to check for uniqueness if they require it.

**Comment by joroKr21** [comment]
It's the same with normal `toString`. I think the alternatives are worse.
