### ISSUE TITLE
No field String("x") in record

### ISSUE THREAD

**Issue by jilen** [milessabin/shapeless#827]
Following code complains 
```
No field String("data") in record Playground.this.Data with shapeless.labelled.KeyTag[Symbol with shapeless.tag.Tagged[String("data")],Playground.this.Data] :: shapeless.HNil
```
```scala
import shapeless._
import shapeless.syntax.singleton._
import shapeless.record._

case class Data(a: Int, b: Int)

type P = Record.`'data->Data`.T

def encode(p: P) = p("data")
```

https://scastie.scala-lang.org/4ZETdquzQeiYQwoqAdaHJw

**Comment by guersam** [comment]
Try `p('data)` instead of `p("data")`. You'd better to ask questions in the [gitter channel](https://gitter.im/milessabin/shapeless) than in github issues.

**Comment by milessabin** [comment]
Thanks for that @guersam ... yup, the gitter channel is the best place to ask questions :-)
