### ISSUE TITLE
Regression in shapeless 2.3.3 with Scala 2.10 SBT console 

### ISSUE THREAD

**Issue by ruippeixotog** [milessabin/shapeless#831]
I'm trying to update [pureconfig](https://github.com/pureconfig/pureconfig) to shapeless version 2.3.3, but I bumped into an apparent regression. With shapeless 2.3.2 and Scala 2.10, I was executing the following code in the SBT `console` (actually, running it through `tut`, which uses the `console` engine):

```scala
import pureconfig._
import shapeless._

case class MyConfig(a: Int, b: String)

/*
implicit final def deriveProductInstance[F, Repr <: HList, DefaultRepr <: HList](
    implicit
    gen: LabelledGeneric.Aux[F, Repr],
    default: Default.AsOptions.Aux[F, DefaultRepr],
    cc: Lazy[ConfigReader.WrappedDefaultValue[F, Repr, DefaultRepr]]): ConfigReader[F] = ???
*/

// <console>:33: error: could not find implicit value for parameter gen: shapeless.LabelledGeneric.Aux[F,Repr]
val instance: ConfigReader[MyConfig] = ConfigReader.deriveProductInstance
```

In Scala 2.10, the code above runs fine when run compiled normally, but fails when compiled through the SBT console. This runs fine, though:

```scala
val lg = LabelledGeneric[MyConfig]
val ao = Default.AsOptions[MyConfig]
implicitly[ConfigReader.WrappedDefaultValue[MyConfig, lg.Repr, ao.Out]]
```

Do you have any idea of what the problem might be?

**Comment by milessabin** [comment]
shapeless on Scala 2.10.x requires macro paradise ... do you have that enabled for your SBT console session?

**Comment by ruippeixotog** [comment]
Yes, I can confirm that console/tut is running with macro paradise enabled:

```
Running tut.TutMain /Users/rui/Documents/Dev/others/pureconfig/macros/src/main/tut
/Users/rui/Documents/Dev/others/pureconfig/macros/target/scala-2.10/tut .*\.
(md|markdown|txt|htm|html) -deprecation -encoding UTF-8 -feature -unchecked -Xfatal-
warnings -Yno-adapted-args -Ywarn-dead-code
-Xplugin:/Users/rui/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scalamacros/paradise_2.10.7/2.1.1/paradise_2.10.7-2.1.1.jar
```

Note that I didn't change my SBT setup at all. Given the same SBT setup, my code is executing without errors when run with shapeless 2.3.2 but is failing with 2.3.3.

**Comment by milessabin** [comment]
I'm not really sure what's happening here. Can you confirm that the SBT console is running with 2.10.7 to match the version of macro-paradise that you're using (rather than, say 2.10.6)? Beyond that, could you see if you can reproduce the problem on the scala repl?

**Comment by ruippeixotog** [comment]
Hi @milessabin, sorry for the delay in the response.

I managed to create a minimal example where this problem manifests itself. Please take a look at this Gist: https://gist.github.com/ruippeixotog/957a7c7f693e63cdd730c4aa2489d6df.

You can reproduce the issue by opening a Scala REPL in the project above and try `val instance: MyTC[MyCaseClass] = MyTC.genInstance`. `macro.scala` is there just to check that macro paradise is enabled - executing `@identity class C` in the REPL should define `C` and print its AST. You can also check that this works in 2.3.2 by changing the shapeless version in `build.sbt`.

I also found out that this only happens when implicit params are defined with `Lazy`. I was unable to debug it further than this... Hope it helps :)

**Comment by joroKr21** [comment]
I'm afraid this won't fixed. Shapeless doesn't support Scala 2.10 anymore.
