### ISSUE TITLE
Compile time considerations when utilizing Coproducts

### ISSUE THREAD

**Issue by mvdstam** [milessabin/shapeless#839]
Hey all,
I'm currently building an application where the bulk of the models are generated by [ScalaPB](https://github.com/scalapb/ScalaPB). One of these models is, for example, generated as follows:

```scala
final case class AuthenticateUserRequest(val identity : scala.Predef.String = { /* compiled code */ }, val credential : scala.Predef.String = { /* compiled code */ }) extends scala.AnyRef with scalapb.GeneratedMessage with scalapb.Message[com.organisation.app.protobuf.service.authentication.AuthenticateUserRequest] with scalapb.lenses.Updatable[com.organisation.app.protobuf.service.authentication.AuthenticateUserRequest] with scala.Product with scala.Serializable
```
Although it is possible to have scalapb generate custom traits for generated case classes, I'd rather not add complexity and context that are specific to my application being one of the consumers of these models. Instead, I want to utilize Coproducts to create types consisting of arbitrary types:

```scala
type Request = authentication.AuthenticateUserRequest :+: otherdomain.SomeOtherRequest :+: differentdomain.SomeDifferentRequest :+: (..) :+: CNil
```
That way, I can for example, parse and process incoming requests:

```scala
def authenticate(request: authentication.AuthenticateUserRequest): Unit = {
  process Coproduct[Request](request)
}

def doSomethingElse(request: otherdomain.SomeOtherRequest): Unit = {
  process Coproduct[Request](request)
}

// Etcetera

private def process(request: Request) // Process everything henceforth as a Request
```

Although this approach works, the compilation time seems to grow exponentially when the amount of types in `Request` increases. I'm now looking at ~10 minutes of compilation time with less than 10 types within the `Request` Coproduct. When looking at the compiler logs, almost all of the time is spent solving implicits for `shapeless.ops.coproduct.Inject#hdInject`.

What I did as a "workaround", is to introduce intermediary types per package/domain:

```scala
type Authentication = authentication.AuthenticateUserRequest :+: CNil
type OtherDomain = otherdomain.SomeOtherRequest :+: CNil
type DifferentDomain = differentdomain.SomeDifferentRequest :+: CNil

type Request = Authentication :+: OtherDomain :+: DifferentDomain :+: CNil
```
This allows me to still have type safety with unrelated models that have to be processed in a consistent way while keeping compilation times acceptable, although there still is some boilerplate to translate between Coproducts.

Is it expected that compilation times get this high when using Coproducts in this way? Or perhaps am I overlooking something?

Cheers! :smile:

**Comment by mvdstam** [comment]
Hi @milessabin, I was wondering if you could shed some light on this.

**Comment by mvdstam** [comment]
Thanks for your comment @milessabin, I'm looking forward to those performance improvements. I'll report back in this issue when its out for future reference. :+1:

**Comment by milessabin** [comment]
Awesome ... thanks!

**Comment by mvdstam** [comment]
@milessabin Great news! Using `2.12.7` which _just_ came out for one of our projects which uses coproducts quite intensively, we went from 340 seconds compilation time to a mere 41 seconds with a cold cache.

Amazing work, thanks a lot!

**Comment by milessabin** [comment]
Awesome! Thanks for the update :smile:

**Comment by milessabin** [comment]
I guess I can close this issue as fixed now :smiley_cat:
