### ISSUE TITLE
could not find implicit value for parameter mapper: shapeless.ops.tuple.FlatMapper

### ISSUE THREAD

**Issue by doofin** [milessabin/shapeless#842]
This do not work.Where can i find the required implicits?
```
import shapeless.poly._
    import shapeless._
    import ops.tuple.FlatMapper._
    import syntax.std.tuple._

((1, 2, 3), true,()) flatMap identity 
```

which complains `could not find implicit value for parameter mapper: shapeless.ops.tuple.FlatMapper[((Int, Int, Int), Boolean, Unit),shapeless.poly.identity.type]
`

**Comment by milessabin** [comment]
Every element of the outermost tuple must itself be a tuple or `Unit` and `Boolean` isn't a tuple, hence the error you're seeing. If you wrap your `Boolean` in a `Tuple1` it'll work as expected,
```scala
scala> ((1, 2, 3), Tuple1(true),()) flatMap identity
res0: (Int, Int, Int, Boolean) = (1,2,3,true)
```

**Comment by doofin** [comment]
wow,huge thanks! This problem cost me a week and still find no solution!
