### ISSUE TITLE
recent change breaks case-app downstream

### ISSUE THREAD

**Issue by SethTisue** [milessabin/shapeless#849]
this turned up in the Scala 2.12 community build, but it's also reproducible independently by doing `publishLocal` on shapeless master and then in the case-app repo, on the 1.1.x branch, changing the shapeless dependency from `2.3.2` to `2.4.0-SNAPSHOT`

then

```
> utilJVM/compile
[info] Compiling 4 Scala sources to /Users/tisue/case-app/util/jvm/target/scala-2.12/classes...
[warn] -target is deprecated: -target:jvm-1.6 is deprecated, forcing use of jvm-1.8
[error] /Users/tisue/case-app/util/shared/src/main/scala/caseapp/util/AnnotationListMacros.scala:8: macro annotation could not be expanded (the most common reason for that is that you need to enable the macro paradise plugin; another possibility is that you try to use macro annotation in the same compilation run that defines it)
[error] class AnnotationListMacros(val c: whitebox.Context) extends CaseClassMacros {
[error]       ^
```

could this somehow be some effect of shapeless dropping the macro-compat dependency? case-app declares an explicit macro-compat dependency, so it's not like macro-compat is missing from the compilation classpath, we'd get a different error if it were

I'm stumped what could be causing this, wondering if I'm missing something obvious.

**Comment by milessabin** [comment]
Reported here: https://github.com/alexarchambault/case-app/issues/87.

**Comment by alexarchambault** [comment]
I'm going to try to just remove the dependency on macro-compat in scala > 2.10, on the case-app side. Hopefully, it'll be easy to report that in its 1.1.x branch too.

**Comment by alexarchambault** [comment]
Both the `master` and the `1.1.x` branch of case-app don't depend anymore on macro-compat in 2.11+ (and master seemed to compile fine with the current master of shapeless - haven't tried 1.1.x).

Does this need a release somehow?

**Comment by SethTisue** [comment]
no release needed.

testing the change here: https://github.com/scala/community-builds/pull/774
