### ISSUE TITLE
Higher-kinded `GenericK[F[_]]`

### ISSUE THREAD

**Issue by letalvoj** [milessabin/shapeless#851]
I tried to implement an automatic derivation for `Traverse[F[_]]` and I failed because it seems that to do so you need to convert instances of the arbitrary higher-kinded type `F[_]` to a `L <: HList`.

I.e. I'd need
```scala
trait GenericK[F[_]] {
  type Repr[T]
  def to[T](ft : F[T]) : Repr[T]
  def from[T](r : Repr[T]) : F[T]
}
```

How difficult would it be to refactor the current macro to be able to produce both `Generic` and `GenericK`? Is it feasible?

**Comment by letalvoj** [comment]
Oh ... God damned, there is `Generic1`, close it please 🙄 ...

**Comment by milessabin** [comment]
You should also take a look at [Kittens](https://github.com/typelevel/kittens).

**Comment by letalvoj** [comment]
As of now kittens do not support `Traverse`, right? That's why I tried to implement it myself.

@milessabin Could you please tell me whether it is necesseary to tie a particular application of `Generic1` (deriving typeclasses) together with it's implementation (the requirement of having the `fr: FR[R]`  field)?

I'd love to be able to do the same stuff with `Generic` which I do with `Generic1` - simple to use it to convert higer-kinded classes to HLists - yet I can not.

**Comment by milessabin** [comment]
Both those examples work with the `Functor` derivation in kittens.

I think it would make sense to move any discussion around this to that project. If you going for a `Traverse` derivation there it might be useful to discuss on the PR as you work on it?

**Comment by letalvoj** [comment]
Yup, sorry. Already done: https://github.com/typelevel/kittens/pull/103
