### ISSUE TITLE
Proposal to refactor annotation.scala

### ISSUE THREAD

**Issue by edrevo** [milessabin/shapeless#866]
The current implementation of Annotation and Annotations provide an `apply` method that returns the annotation. The fact that the annotations needs to be instantiated forces the macro to check whether the annotation is "case class-like", and fails if that precondition isn't met. This limits the usefulness of these traits, since you can't check if a class is `@deprecated`, for example.

I think the `Annotation` trait should be split into:

1. `HasAnnotation`, which just provides evidence that an annotation exists, and
2. `Annotation`, which also allows retrieving the annotation through the `apply` method.

Furthermore, I propose that `HasAnnotation` has an output type of `Option[A]` which would allow this to be used as evidence both that a annotation is present or absent. E.g.

```scala
def antiDeprecated[T](foo: T)(implicit ev: HasAnnotation.Aux[deprecated, T, None.type]) = ???

def onlyDeprecated[T](foo: T)(implicit ev: HasAnnotation.Aux[deprecated, T, Some[deprecated]]) = ???
```

I am happy to change the code (I have already copied and modified the code for my project) and open a PR if this sounds goods.

cc @alexarchambault, since he's the original author of the code.

**Comment by guersam** [comment]
I was about to propose a slightly different suggestion with an optional annotation support which allows 
 `Annotation[Option[deprecated], T]`, instead of always aborting compilation for not found one. Yours sound great too :)

**Comment by alexarchambault** [comment]
Adding a `HasAnnotation` type class sounds fine to me.

I'm not too sure about its output type though... I guess one can always use implicit priorities to handle cases where an annotation is not present, like with the current `Annotation`.

**Comment by edrevo** [comment]
Thanks for the feedback 😄  I'm not very familiar with implicit priorities (I know they exist, but I've never actually used them for anything). How would one implement a function like `antiDeprecated` with implicit priorities?

**Comment by guersam** [comment]
I'm adding documentation support for generic schema derivation in [endpoints](https://github.com/julienrf/endpoints/blob/d3d0250be166635a0ea9b2369de9fd84c2fb09d1/json-schema/json-schema-generic/src/main/scala/endpoints/generic/JsonSchemas.scala#L131-L155). It currently has field documentation generation feature using `Annotations`, and I want to add whole class documentation with `Annotation` as well.

Current code:
```scala
trait GenericJsonSchema {

    implicit def recordGeneric[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      record: GenericRecord[R],
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericRecord[A] =
      new GenericRecord[A] {
        def jsonSchema(docs: List[Option[documentation]]): Record[A] =
          nameSchema(record.jsonSchema(docsToList(docAnns.apply)).invmap[A](gen.from)(gen.to))
      }

    implicit def taggedGeneric[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      tagged: GenericTagged[R],
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericTagged[A] =
      new GenericTagged[A] {
        def jsonSchema(docs: List[Option[documentation]]): Tagged[A] =
          nameSchema(tagged.jsonSchema(docsToList(docAnns.apply)).invmap[A](gen.from)(gen.to))
      }
}
```

Support for class documentation with implicit priorities:
```scala
trait GenericJsonSchema extends GenericJsonSchema0 {

    implicit def recordGeneric[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      record: GenericRecord[R],
      classDoc: Annotation[documentation, A], // added evidence for class doc
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericRecord[A] =
      new GenericRecord[A] {
        def jsonSchema(docs: List[Option[documentation]]): Record[A] =
          nameSchema(record.jsonSchema(docsToList(docAnns.apply), /* use classDoc */).invmap[A](gen.from)(gen.to))
      }

    implicit def taggedGeneric[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      tagged: GenericTagged[R],
      classDoc: Annotation[documentation, A], // added evidence for class doc
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericTagged[A] =
      new GenericTagged[A] {
        def jsonSchema(docs: List[Option[documentation]]): Tagged[A] =
          nameSchema(tagged.jsonSchema(docsToList(docAnns.apply), /* use classDoc */).invmap[A](gen.from)(gen.to))
      }
}

trait GenericJsonSchema0 {

    implicit def recordGenericNoClassDoc[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      record: GenericRecord[R],
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericRecord[A] =
      new GenericRecord[A] {
        def jsonSchema(docs: List[Option[documentation]]): Record[A] =
          nameSchema(record.jsonSchema(docsToList(docAnns.apply)).invmap[A](gen.from)(gen.to))
      }

    implicit def taggedGenericNoClassDoc[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      tagged: GenericTagged[R],
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericTagged[A] =
      new GenericTagged[A] {
        def jsonSchema(docs: List[Option[documentation]]): Tagged[A] =
          nameSchema(tagged.jsonSchema(docsToList(docAnns.apply)).invmap[A](gen.from)(gen.to))
      }
}
```

What I'd prefer:
```scala
trait GenericJsonSchema {

    implicit def recordGeneric[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      record: GenericRecord[R],
      classDoc: Annotation[Option[documentation], A], // note Option[documentation] here
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericRecord[A] =
      new GenericRecord[A] {
        def jsonSchema(docs: List[Option[documentation]]): Record[A] =
          nameSchema(record.jsonSchema(docsToList(docAnns.apply), /* use classDoc */).invmap[A](gen.from)(gen.to))
      }

    implicit def taggedGeneric[A, R, D <: HList](implicit
      gen: LabelledGeneric.Aux[A, R],
      tagged: GenericTagged[R],
      classDoc: Annotation[Option[documentation], A], // note Option[documentation] here
      docAnns: Annotations.Aux[documentation, A, D],
      docsToList: ToList[D, Option[documentation]],
      ct: ClassTag[A]
    ): GenericTagged[A] =
      new GenericTagged[A] {
        def jsonSchema(docs: List[Option[documentation]]): Tagged[A] =
          nameSchema(tagged.jsonSchema(docsToList(docAnns.apply), /* use classDoc */).invmap[A](gen.from)(gen.to))
      }
}
```

It's slightly different from the goal of this ticket, but I'm just describing my use case.

**Comment by guersam** [comment]
I still want `Annotation[A, T]` to abort compilation when it's not annotated as it gives strong compile time guarantee.

**Comment by guersam** [comment]
Opened #867 for further discussion.

**Comment by guersam** [comment]
Regarding @edrevo's usecase, how about  splitting `HasAnnotation` into positive/negative types instead of involving Some/None in Aux? Using aux pattern for constraint looks a bit inconsistent to me.

Candidates:
  - Annotated / NotAnnotated
  - HasAnnotation / NotHasAnnotation
  - or something else

**Comment by guersam** [comment]
Adding `IsAnnotated` / `IsNotAnnotated` to the list.

**Comment by joroKr21** [comment]
#867 was merged
