### ISSUE TITLE
[Wiki] Link to spray-json-shapeless is broken

### ISSUE THREAD

**Issue by aka-bash0r** [milessabin/shapeless#913]
The link is broken aka leads to a 404 not found on GitHub.

https://github.com/milessabin/shapeless/wiki/Built-with-shapeless#spray-json-shapeless

**Comment by milessabin** [comment]
Thanks. It's a dead project ... I've removed the link.

If you're looking for a high-quality, high-performance, well-maintained json library, I recommend [Circe](https://github.com/circe/circe).
