### ISSUE TITLE
Support scala.js 1.0.0-RC2

### ISSUE THREAD

**Issue by cquiroz** [milessabin/shapeless#951]
I tested it but maybe blocked by https://github.com/scala-js/scala-js/issues/3924

**Comment by milessabin** [comment]
I very much want to do this, but I'm currently a bit confused about sjs version compatibility ... I think I would need to add both 0.6.x and 1.0.0-RC2 to the build matrix?

@travisbrown you've been doing a lot of this recently ... any pointers?

**Comment by larsrh** [comment]
Closed by #967
